# command line: 
# cp platformio_release.resonancer.ini platformio_release.ini
# platformio run -e esp32s3dev_16MB_opi_resonancer --target upload -upload-port /dev/ttyUSB0
[env:esp32s3dev_16MB_opi_resonancer]
extends = env:esp32s3dev_16MB_opi
custom_usermods = ${env:esp32s3dev_16MB_opi.custom_usermods} user_fx Resonancer
build_unflags = ${env:esp32s3dev_16MB_opi.build_unflags} -D ARDUINO_USB_CDC_ON_BOOT=1
build_flags = ${env:esp32s3dev_16MB_opi.build_flags} -D ARDUINO_USB_CDC_ON_BOOT=0 -D WLED_NTP_ENABLED=1 -D RESONANCER_ENABLE_BLE=1
lib_deps = ${env:esp32s3dev_16MB_opi.lib_deps} 
  h2zero/NimBLE-Arduino @ ^1.4.3
upload_port = /dev/ttyUSB0