/*
 * Embed resonancer_uikit.js into a C++ header.
 *
 * The library is written as a real JavaScript file so it can be linted, unit tested and
 * read in a browser dev tools session; the firmware needs it as a PROGMEM string that
 * appendConfigData() streams to the settings page. This tool is the bridge between the
 * two, and test/header.test.js fails when the committed header is out of date.
 *
 * Usage:
 *   node usermods/Resonancer/tools/uikit_header.js          # regenerate
 *   node usermods/Resonancer/tools/uikit_header.js --check   # exit 1 when stale
 */
// AI: below section was generated by an AI
'use strict';

const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, '..');
const SOURCE = path.join(DIR, 'resonancer_uikit.js');
const TARGET = path.join(DIR, 'resonancer_uikit_js.h');

// Raw string literal delimiter: the JavaScript must not contain this sequence.
const DELIM = 'UKITJS';

/**
 * Strip what only helps a human reader: comment-only lines and the indentation that
 * follows them. Line breaks are kept so a stack trace from the device still points at
 * roughly the same line as the source file.
 */
function compact(text) {
	const out = [];
	for (const raw of String(text).split('\n')) {
		const line = raw.replace(/\t/g, '  ').replace(/\s+$/, '');
		const probe = line.trim();
		if (!probe) continue;
		if (probe.startsWith('//') || probe.startsWith('/*') || probe.startsWith('*') || probe.startsWith('*/')) continue;
		out.push(line.replace(/^\s+/, ''));
	}
	return out.join('\n');
}

/** Build the full header text for a JavaScript source string. */
function generate(js) {
	const body = compact(js);
	const lines = [];
	lines.push('// Auto-generated by usermods/Resonancer/tools/uikit_header.js - do not edit.');
	lines.push('// Source: usermods/Resonancer/resonancer_uikit.js');
	lines.push('// Regenerate with: node usermods/Resonancer/tools/uikit_header.js');
	lines.push('#pragma once');
	lines.push('');
	lines.push('#include <Arduino.h>');
	lines.push('');
	lines.push(`static const char RESONANCER_UKIT_JS[] PROGMEM = R"${DELIM}(`);
	lines.push(body);
	lines.push(`)${DELIM}";`);
	lines.push('');
	return lines.join('\n');
}

function read() {
	return fs.readFileSync(SOURCE, 'utf8');
}

function main() {
	const expected = generate(read());
	const check = process.argv.indexOf('--check') >= 0;
	let current = null;
	try { current = fs.readFileSync(TARGET, 'utf8'); } catch (e) { current = null; }

	if (check) {
		if (current !== expected) {
			console.error('resonancer_uikit_js.h is stale, run: node usermods/Resonancer/tools/uikit_header.js');
			process.exit(1);
		}
		console.log('resonancer_uikit_js.h is up to date');
		return;
	}
	fs.writeFileSync(TARGET, expected);
	console.log(`wrote ${path.relative(process.cwd(), TARGET)} (${expected.length} bytes)`);
}

if (require.main === module) main();

module.exports = { generate, compact, SOURCE, TARGET, DELIM };
// AI: end
