#pragma once

#include <stddef.h>
#include <stdint.h>

/*
 * LumaFlow serial protocol - frame constants and decoders.
 *
 * This part is intentionally free of any WLED dependency so it can be unit
 * tested on a host and reused by other input transports (UDP, BLE).
 *
 * Wire format (little endian fields, length excludes the framing bytes):
 *
 *   +------+------+--------+-----+-------------+----------+------+
 *   | 0xEB | 0x90 | length | cmd | payload     | checksum | 0xED |
 *   +------+------+--------+-----+-------------+----------+------+
 *
 *   length   = 1 + payload length             (1..128)
 *   checksum = (length + cmd + sum(payload)) & 0xFF
 *
 * Commands:
 *   STREAM (0xD8) : 20 byte payload = 10 channels x 2 bytes
 *                   byte 0 = (function << 4) | red
 *                   byte 1 = (green    << 4) | blue
 *                   every field is a 4 bit value (0..15)
 *   AUTH   (0xE0) : host_time(4, LE) | expire_time(4, LE) | sig_len(1) | signature
 *
 * Reference: LumaFlow host application TLV implementation.
 */
// AI: below section was generated by an AI
namespace LumaFlow {

  constexpr uint8_t HEAD0 = 0xEB;           // first framing byte
  constexpr uint8_t HEAD1 = 0x90;           // second framing byte
  constexpr uint8_t TAIL  = 0xED;           // closing framing byte

  constexpr uint8_t CMD_STREAM = 0xD8;      // 10 channel RGB frame
  constexpr uint8_t CMD_AUTH   = 0xE0;      // license / time payload

  constexpr uint8_t CHANNEL_COUNT = 10;     // channels carried by a STREAM frame
  constexpr uint8_t STREAM_PAYLOAD_LEN = CHANNEL_COUNT * 2;
  constexpr uint8_t AUTH_SIG_MAX = 72;      // signature upper bound from the host implementation
  constexpr uint8_t MAX_PAYLOAD_LEN = 127;  // length byte is 1 + payload

  // Largest possible frame: head(2) + length(1) + cmd+payload(128) + checksum(1) + tail(1)
  constexpr uint16_t MAX_FRAME_LEN = 2 + 1 + MAX_PAYLOAD_LEN + 1 + 1 + 1;

  // Per-channel blink pattern carried in the upper nibble of the first byte.
  enum ChannelFunction : uint8_t {
    FUNC_SOLID = 0,   // steady on
    FUNC_BLINK_1HZ = 1,
    FUNC_BLINK_2HZ = 2,
    FUNC_BLINK_4HZ = 3,
  };

  // One decoded STREAM channel. Colour components are expanded to 8 bit
  // (nibble * 17) so they can be handed to WLED without further conversion.
  struct Channel {
    uint8_t function = FUNC_SOLID;
    uint8_t red = 0;
    uint8_t green = 0;
    uint8_t blue = 0;
  };

  // Decoded AUTH payload. Signature verification is not implemented; the raw
  // bytes are kept so it can be added without changing the wire parsing.
  struct Auth {
    uint32_t hostTime = 0;       // host clock at frame creation (unix seconds)
    uint32_t expireTime = 0;     // licence expiry (unix seconds)
    uint8_t  sigLen = 0;
    uint8_t  signature[AUTH_SIG_MAX] = {0};
  };

  // Frame layout shared by all commands. The payload pointer refers to the
  // caller's buffer, no copy is made.
  struct Frame {
    uint8_t cmd = 0;
    const uint8_t* payload = nullptr;
    uint8_t payloadLen = 0;
  };

  /**
   * Decode a complete TLV frame (including head and tail bytes).
   *
   * @param buf        raw frame bytes
   * @param len        number of bytes available in buf
   * @param out        receives the decoded frame on success
   * @param consumed   optional, receives the number of bytes belonging to the frame
   * @return true when a structurally valid frame with a matching checksum was decoded
   */
  bool decodeFrame(const uint8_t* buf, size_t len, Frame& out, size_t* consumed = nullptr);

  /**
   * Decode a STREAM payload into CHANNEL_COUNT channels.
   *
   * @param payload      STREAM payload (STREAM_PAYLOAD_LEN bytes)
   * @param payloadLen   payload length as reported by the frame
   * @param channels     destination array of at least CHANNEL_COUNT entries
   * @return true when the payload length matches STREAM_PAYLOAD_LEN
   */
  bool decodeStream(const uint8_t* payload, uint8_t payloadLen, Channel* channels);

  /**
   * Decode an AUTH payload.
   *
   * @param payload      AUTH payload
   * @param payloadLen   payload length as reported by the frame
   * @param out          receives the decoded licence data
   * @return true when the payload is structurally valid
   */
  bool decodeAuth(const uint8_t* payload, uint8_t payloadLen, Auth& out);

  /**
   * Case insensitive hex decoder used by the JSON transport, where the payload
   * is forwarded as a hex string.
   *
   * @param hex      NUL terminated hex text, upper or lower case
   * @param out      destination buffer
   * @param outSize  capacity of out
   * @return number of decoded bytes, 0 on malformed input or insufficient space
   */
  size_t hexToBytes(const char* hex, uint8_t* out, size_t outSize);

} // namespace LumaFlow
// AI: end
