#include "lumaflow_protocol.h"

// AI: below section was generated by an AI
namespace LumaFlow {

  // Convert one ASCII hex digit, returns 0xFF for non hex characters.
  static inline uint8_t hexDigit(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    return 0xFF;
  }

  bool decodeFrame(const uint8_t* buf, size_t len, Frame& out, size_t* consumed) {
    // smallest frame: head(2) + length(1) + cmd(1) + checksum(1) + tail(1)
    constexpr size_t MIN_FRAME_LEN = 6;
    if (buf == nullptr || len < MIN_FRAME_LEN) return false;
    if (buf[0] != HEAD0 || buf[1] != HEAD1) return false;

    const uint8_t length = buf[2];            // 1 + payload length
    if (length == 0 || length > MAX_PAYLOAD_LEN + 1) return false;

    // layout: head(2) | length(1) | cmd(1) | payload(length-1) | checksum(1) | tail(1)
    // so: cmd at 3, checksum at 3 + length, tail at 2 + length + 2
    const size_t total = 2 + length + 3;
    if (len < total) return false;
    if (buf[total - 1] != TAIL) return false;

    // checksum covers exactly the length byte value worth of bytes: cmd + payload
    uint8_t checksum = length;
    for (size_t i = 0; i < length; i++) checksum += buf[3 + i];
    if (checksum != buf[3 + length]) return false;

    out.cmd = buf[3];
    out.payload = (length > 1) ? &buf[4] : nullptr;
    out.payloadLen = length - 1;
    if (consumed) *consumed = total;
    return true;
  }

  bool decodeStream(const uint8_t* payload, uint8_t payloadLen, Channel* channels) {
    if (payload == nullptr || channels == nullptr) return false;
    if (payloadLen != STREAM_PAYLOAD_LEN) return false;

    for (uint8_t i = 0; i < CHANNEL_COUNT; i++) {
      const uint8_t b0 = payload[i * 2];
      const uint8_t b1 = payload[i * 2 + 1];
      Channel& ch = channels[i];
      ch.function = (b0 >> 4) & 0x0F;
      // 4 bit components are expanded to 8 bit so downstream code works in one colour space
      ch.red   = (uint8_t)((b0 & 0x0F) * 17);
      ch.green = (uint8_t)(((b1 >> 4) & 0x0F) * 17);
      ch.blue  = (uint8_t)((b1 & 0x0F) * 17);
    }
    return true;
  }

  bool decodeAuth(const uint8_t* payload, uint8_t payloadLen, Auth& out) {
    // host_time(4) + expire_time(4) + sig_len(1) + signature(1..72)
    constexpr uint8_t HEADER_LEN = 9;
    if (payload == nullptr || payloadLen < HEADER_LEN) return false;

    out.hostTime   = (uint32_t)payload[0] | ((uint32_t)payload[1] << 8) | ((uint32_t)payload[2] << 16) | ((uint32_t)payload[3] << 24);
    out.expireTime = (uint32_t)payload[4] | ((uint32_t)payload[5] << 8) | ((uint32_t)payload[6] << 16) | ((uint32_t)payload[7] << 24);

    const uint8_t sigLen = payload[8];
    if (sigLen == 0 || sigLen > AUTH_SIG_MAX) return false;
    if ((uint16_t)payloadLen != (uint16_t)HEADER_LEN + sigLen) return false;

    out.sigLen = sigLen;
    for (uint8_t i = 0; i < sigLen; i++) out.signature[i] = payload[HEADER_LEN + i];
    return true;
  }

  size_t hexToBytes(const char* hex, uint8_t* out, size_t outSize) {
    if (hex == nullptr || out == nullptr) return 0;

    size_t n = 0;
    // decode pairs, skipping nothing: the host implementation emits a dense string.
    // Invalid characters abort the decode so a truncated frame cannot be accepted.
    while (hex[0] != '\0' && hex[1] != '\0') {
      const uint8_t hi = hexDigit(hex[0]);
      const uint8_t lo = hexDigit(hex[1]);
      if (hi == 0xFF || lo == 0xFF) return 0;
      if (n >= outSize) return 0;             // does not fit
      out[n++] = (uint8_t)((hi << 4) | lo);
      hex += 2;
    }
    if (hex[0] != '\0') return 0;             // odd number of digits
    return n;
  }

} // namespace LumaFlow
// AI: end
