/*
 * resonancer_uikit.h - C++ side of the data driven usermod settings page.
 *
 * The page itself is rendered by resonancer_uikit.js (embedded from the generated
 * header resonancer_uikit_js.h). This header only provides the data: a small set of
 * builder helpers that turn component, rule, hint and check tables into the JSON
 * description the JavaScript engine consumes, plus the OEM key registry that an
 * output implementation uses to publish its own preset buttons.
 *
 * Everything here is public and reusable: a different usermod may copy this pair of
 * files, and an output implementation may register keys without knowing anything about
 * how the button is drawn.
 *
 * See resonancer_uikit.js for the data model and the rule semantics.
 */
// AI: below section was generated by an AI
#pragma once

#include <Arduino.h>
#include "wled.h"

namespace ResonancerUi {

// --- values shared with the JavaScript engine ------------------------------
// The names must match the switch statements in resonancer_uikit.js.
enum Op : uint8_t {
  OP_EQ, OP_NE, OP_IN, OP_NOTIN, OP_TRUE, OP_FALSE,
  OP_GE, OP_GT, OP_LE, OP_LT, OP_EXISTS, OP_MISSING, OP_ACTIVE,
};

enum Prop : uint8_t { PROP_VISIBLE, PROP_EDITABLE, PROP_REQUIRED };

enum Widget : uint8_t { W_AUTO, W_PIN, W_DROPDOWN, W_FOLD, W_STATUS, W_GRID };

// Hint levels: i = explanation, g = confirmation, w = trade-off, e = blocking problem.
constexpr char HINT_INFO  = 'i';
constexpr char HINT_GOOD  = 'g';
constexpr char HINT_WARN  = 'w';
constexpr char HINT_ERROR = 'e';

/** Upper bound of registered preset keys; registration order is the preset index. */
#ifndef RESONANCER_OEM_MAX_KEYS
  #define RESONANCER_OEM_MAX_KEYS 24
#endif

/**
 * One preset button published by an output implementation.
 *
 * The slot an implementation gets back from registerOEMKey() is the index its own
 * preset table must use in RFDevice::setOemCommand(), so the button order on the page
 * and the preset order in the device stay aligned.
 */
struct OemKey {
  const char* key;     // stable identifier, used by the JSON API and the DOM
  const char* label;   // display name
  uint8_t     color;   // index into oemColors()
  uint8_t     span;    // grid columns (1 = default width)
  uint8_t     flags;   // reserved for future use, 0 for now
};

/** Stripe colours of the preset buttons, public so implementations can pick an index. */
const char* const* oemColors();
uint8_t oemColorCount();

/**
 * Publish one preset button.
 * @return true when the key was accepted (false when the table is full or the key exists)
 */
bool registerOEMKey(const OemKey& key);

uint8_t oemKeyCount();
const OemKey* oemKeyAt(uint8_t index);
/** @return slot index of a key, or -1 when it is not registered */
int8_t oemKeyIndex(const char* key);

// --- page builder ----------------------------------------------------------

/** Add an input component (a field WLED generates itself). */
JsonObject component(JsonObject page, const char* id, const char* kind, Widget widget = W_AUTO);

/**
 * Add a component that holds one entry per HTML element, e.g. a repeated row.
 * @param each optional caption template, '$i' is replaced by the row number
 */
JsonObject arrayComponent(JsonObject page, const char* id, const char* kind, Widget widget = W_AUTO);

/** Add one restricting rule: when <whenKey> <op> <value> then <target>.<prop> = on. */
JsonObject rule(JsonObject page, const char* whenKey, Op op, const char* value,
                const char* target, Prop prop, bool on, const char* reason = nullptr);

/** Add a hint box below the row of a field. index < 0 = last element of the field. */
void hint(JsonObject page, const char* id, int8_t index, char level, const char* text);

/** Element level validation: a numeric range. */
void checkRange(JsonObject page, const char* target, float min, float max, const char* message);

/** Element level validation: a named predicate implemented by the engine. */
void checkValidator(JsonObject page, const char* target, const char* name, const char* message);

/** Extra state that is not a form field (device status), fed to the rules. */
void value(JsonObject page, const char* key, const char* text);

/**
 * Add one option to a dropdown component.
 *
 * The label is copied into the document, so a buffer built on the stack is safe here. The
 * other helpers store their text by address (that is what ArduinoJson v6 does with a
 * const char*), so they expect a literal or another persistent string.
 */
JsonObject option(JsonObject comp, const char* label, int16_t value, bool disabled = false);

/** Add one polled field rendered by a status component and fed to the rules. */
void pollField(JsonObject comp, const char* label, const char* path, const char* valueKey = nullptr);

/**
 * Build the preset grid component from the registry.
 *
 * @param payloadKey JSON path the clicked key is substituted into; the payload is
 *                   always {"Resonancer":{"<payloadKey>":"<key>"}}
 */
JsonObject oemGrid(JsonObject page, const char* id, const char* label, const char* payloadKey);

/** Set the label of a fold's reveal control ('$n' is replaced by the hidden count). */
void foldLabels(JsonObject comp, const char* more, const char* less);

// --- emit ------------------------------------------------------------------

/**
 * Callback that fills the page description.
 *
 * A plain function pointer plus a context keeps the JSON document inside the library
 * (where its size is known) without pulling a template or the embedded script into
 * every translation unit that includes this header.
 */
typedef void (*PageBuilder)(JsonObject& page, void* ctx);

/**
 * Print the library followed by the page description, inside a guard.
 *
 * The description is built in a temporary document: it is a few kB and lives only for
 * this call, which is once per settings page request.
 */
void emit(Print& out, PageBuilder build, void* ctx);

/**
 * Capacity of the temporary document.
 *
 * ArduinoJson v6 copies keys and strings into one pool, which needs roughly 1.5 to 2.5
 * times the serialised size, and it drops what does not fit *silently*. The RF build
 * serialises ~4.6 kB, so the budget is generous on purpose: a truncated description
 * leaves the settings page half decorated with no visible reason.
 */
constexpr size_t UKIT_PAGE_JSON_SIZE = 24576;

} // namespace ResonancerUi
// AI: end
