#include "wled.h"
#include "lumaflow_protocol.h"
#include "resonancer_rfdevice.h"
#include "resonancer_uikit.h"

// AI: below section was generated by an AI
/*
 * Reference output device.
 *
 * Compiled when no concrete implementation is present (RESONANCER_ENABLE_RF == 0).
 * It is a working template for a community implementation rather than a placeholder:
 * it accepts the configuration, reports itself active, counts the packets it is given
 * and answers preset commands, but it transmits nothing.
 *
 * Copy this file, implement the RFDevice methods for your own hardware and register
 * your preset keys, then build with RESONANCER_ENABLE_RF=1 and your own
 * createRfDevice()/resonancerCheckLicence()/resonancerRegisterOemKeys().
 */
#if !RESONANCER_ENABLE_RF

// A build without output hardware has no reference pins, so the pre-fill values stay
// neutral. Their settings are not part of such a build anyway (see resonancer_rfdevice.h).
const int8_t RESONANCER_DEFAULT_SCK  = RESONANCER_PIN_UNUSED;
const int8_t RESONANCER_DEFAULT_MISO = RESONANCER_PIN_UNUSED;
const int8_t RESONANCER_DEFAULT_MOSI = RESONANCER_PIN_UNUSED;
const int8_t RESONANCER_DEFAULT_SS   = RESONANCER_PIN_UNUSED;
const int8_t RESONANCER_DEFAULT_GD0  = RESONANCER_PIN_UNUSED;
const int8_t RESONANCER_DEFAULT_GD2  = RESONANCER_PIN_UNUSED;
const float  RESONANCER_DEFAULT_RF_FREQ = 0.0f;      // MHz

namespace {

class RfDeviceReference : public RFDevice {
  public:
    // The reference device has no bus and no chip select, so any configuration is
    // acceptable: it exists to exercise the pipeline, not to talk to hardware.
    bool InitConfig(uint8_t, int8_t, int8_t, int8_t, int8_t, int8_t, int8_t) override {
      _configured = true;
      return true;
    }

    bool DeviceInit() override {
      _active = true;
      DEBUG_PRINTLN(F("Resonancer: reference output active (nothing is transmitted)"));
      return true;
    }

    void changeRuntimeConfig(const RFRuntimeConfig& cfg) override { _config = cfg; }

    void submitRGBPacket(uint8_t channelCount, const RgbColor* arr) override {
      if (!_active || arr == nullptr || channelCount == 0) return;
      _packets++;
      _channels = channelCount;
    }

    void setAuthentication(AuthResult result) override { (void)result; }

    void setOemCommand(uint8_t index) override {
      if (!_active) return;
      _presets++;
      DEBUG_PRINTF_P(PSTR("Resonancer: reference preset %u\n"), (unsigned)index);
    }

    void DeviceUnInit() override {
      _active = false;
      _configured = false;
    }

    const char* getName() const override { return "reference"; }
    bool isActive() const override { return _active; }
    bool isConfigured() const { return _configured; }
    uint32_t packets() const { return _packets; }
    uint32_t presets() const { return _presets; }

  private:
    bool _active = false;
    bool _configured = false;
    uint8_t _channels = 0;
    uint32_t _packets = 0;
    uint32_t _presets = 0;
    RFRuntimeConfig _config;
};

RfDeviceReference referenceDevice;

} // namespace

RFDevice* createRfDevice() { return &referenceDevice; }

/*
 * Licence policy of the reference build: a structurally valid AUTH frame is accepted,
 * nothing is verified. A real deployment replaces this function - the signature
 * check, the expiry rules and the hardware restriction live outside this repository.
 */
AuthResult resonancerCheckLicence(const LumaFlow::Auth& auth) {
  if (auth.sigLen == 0 || auth.hostTime == 0) return AuthResult::NotAuthenticated;
  return AuthResult::RfRestricted;   // the reference build is not allowed to transmit
}

/*
 * Demo presets so the settings page shows a working grid without any implementation
 * specific knowledge. Registration order is the preset index.
 */
void resonancerRegisterOemKeys() {
  ResonancerUi::registerOEMKey({ "demo-red",   "Demo Red",   0, 1, 0 });
  ResonancerUi::registerOEMKey({ "demo-green", "Demo Green", 1, 1, 0 });
  ResonancerUi::registerOEMKey({ "demo-loop",  "Demo Loop",  15, 1, 0 });
  ResonancerUi::registerOEMKey({ "demo-stop",  "Demo Stop",  16, 1, 0 });
}

#endif // !RESONANCER_ENABLE_RF
// AI: end
