// Auto-generated by usermods/Resonancer/tools/uikit_header.js - do not edit.
// Source: usermods/Resonancer/resonancer_uikit.js
// Regenerate with: node usermods/Resonancer/tools/uikit_header.js
#pragma once

#include <Arduino.h>

static const char RESONANCER_UKIT_JS[] PROGMEM = R"UKITJS(
(function (root, factory) {
const api = factory();
if (typeof module === 'object' && module.exports) module.exports = api;
else root.UKIT = root.UKIT || api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
'use strict';
const MAX_PASSES = 3;
const DEFAULT_BASE = { visible: true, editable: true, required: false };
const REASON_PRIORITY = ['visible', 'editable', 'required'];
function num(v) {
if (typeof v === 'number') return Number.isFinite(v) ? v : null;
if (typeof v === 'boolean') return v ? 1 : 0;
if (typeof v === 'string' && v.trim() !== '') {
const n = Number(v);
if (Number.isFinite(n)) return n;
}
return null;
}
function same(a, b) {
const na = num(a), nb = num(b);
if (na !== null && nb !== null) return na === nb;
return a === b;
}
function truthy(v) {
return v === true || v === 1 || v === '1' || v === 'true';
}
function present(v) {
return v !== undefined && v !== null && v !== '';
}
function list(v) {
if (Array.isArray(v)) return v;
if (typeof v === 'string') return v.split(',').map((s) => s.trim()).filter((s) => s !== '');
return [];
}
function condMet(cond, ctx) {
if (!cond) return true;
const actual = cond.prop ? (ctx.matrix[cond.key] ? ctx.matrix[cond.key][cond.prop] : undefined)
: ctx.values[cond.key];
switch (cond.op) {
case 'eq':      return same(actual, cond.value);
case 'ne':      return !same(actual, cond.value);
case 'in':      return list(cond.value).some((v) => same(actual, v));
case 'notin':   return !list(cond.value).some((v) => same(actual, v));
case 'true':    return truthy(actual);
case 'false':   return !truthy(actual);
case 'ge':      return num(actual) !== null && num(actual) >= num(cond.value);
case 'gt':      return num(actual) !== null && num(actual) >  num(cond.value);
case 'le':      return num(actual) !== null && num(actual) <= num(cond.value);
case 'lt':      return num(actual) !== null && num(actual) <  num(cond.value);
case 'exists':  return present(actual);
case 'missing': return !present(actual);
case 'active':  return ctx.activeKey === cond.key;   // the field the user just touched
default:        return false;                        // unknown op never matches
}
}
function applyRule(state, rule) {
if (!state || !rule) return false;
if (rule.prop === 'visible' || rule.prop === 'editable') {
if (rule.value !== false || state[rule.prop] === false) return false;
state[rule.prop] = false;
} else if (rule.prop === 'required') {
if (rule.value !== true || state.required === true) return false;
state.required = true;
} else {
return false;
}
return true;
}
function finalize(state, component, reasons) {
if (component.kind && component.kind !== 'input') state.required = false;
if (!state.visible) state.required = false;
state.reason = '';
for (const prop of REASON_PRIORITY) {
if (reasons && reasons[prop]) { state.reason = reasons[prop]; break; }
}
}
function cloneMatrix(matrix) {
const out = {};
for (const id in matrix) out[id] = Object.assign({}, matrix[id]);
return out;
}
function sameMatrix(a, b) {
const ka = Object.keys(a), kb = Object.keys(b);
if (ka.length !== kb.length) return false;
for (const id of ka) {
const x = a[id], y = b[id];
if (!y) return false;
if (x.visible !== y.visible || x.editable !== y.editable ||
x.required !== y.required || x.reason !== y.reason) return false;
}
return true;
}
function derive(opts) {
const components = (opts && opts.components) || [];
const rules = (opts && opts.rules) || [];
const values = (opts && opts.values) || {};
const activeKey = (opts && opts.activeKey) || null;
let matrix = {};
let converged = false;
let pass = 0;
for (; pass < MAX_PASSES; pass++) {
const next = {};
const reasons = {};
for (const c of components) {
next[c.id] = Object.assign({ reason: '' }, DEFAULT_BASE, c.base || {});
reasons[c.id] = { visible: '', editable: '', required: '' };
}
const ctx = { values, matrix, activeKey };
for (const rule of rules) {
if (!condMet(rule.when, ctx)) continue;
const state = next[rule.target];
if (!state) continue;                     // unknown target: ignore, never throw
const reason = reasons[rule.target];
if (applyRule(state, rule) && !reason[rule.prop]) reason[rule.prop] = rule.reason || '';
}
for (const c of components) finalize(next[c.id], c, reasons[c.id]);
if (sameMatrix(next, matrix)) { matrix = next; converged = true; break; }
matrix = next;
}
return { matrix, passes: converged ? pass + 1 : MAX_PASSES, converged };
}
const validators = {
distinct(ctx, check) {
const seen = [], dup = [];
for (const v of list(ctx.values[check.target])) {
if (!present(v) || Number(v) < 0) continue;
if (seen.indexOf(String(v)) >= 0) dup.push(v);
else seen.push(String(v));
}
return dup.length ? (check.message || 'Value used twice') : '';
},
};
function evalCheck(check, ctx) {
const value = ctx.values[check.target];
if (check.when && !condMet(check.when, ctx)) return '';
switch (check.kind) {
case 'range': {
const n = num(value);
if (n === null) return '';
if (check.min !== undefined && n < num(check.min)) return check.message || 'Below the minimum';
if (check.max !== undefined && n > num(check.max)) return check.message || 'Above the maximum';
return '';
}
case 'pattern': {
if (value === undefined || value === null) return '';
let re = null;
try { re = new RegExp(check.pattern, check.flags || ''); } catch (e) { return ''; }
return re.test(String(value)) ? '' : (check.message || 'Malformed value');
}
case 'enum':
return list(check.values).some((v) => same(value, v)) ? '' : (check.message || 'Unsupported value');
case 'notEmpty':
return present(value) ? '' : (check.message || 'Required');
case 'validator': {
const fn = validators[check.name];
return fn ? fn(ctx, check) : '';
}
default:
return '';
}
}
function validate(opts) {
const checks = (opts && opts.checks) || [];
const components = (opts && opts.components) || [];
const matrix = (opts && opts.matrix) || {};
const values = (opts && opts.values) || {};
const activeKey = (opts && opts.activeKey) || null;
const ctx = { values, matrix, activeKey };
const validity = {};
let ok = true;
for (const check of checks) {
const message = evalCheck(check, ctx);
if (!message) continue;
for (const id of (Array.isArray(check.target) ? check.target : [check.target])) {
const state = matrix[id];
const c = components.find((x) => x.id === id);
if (!state || !state.visible || (c && c.kind !== 'input')) continue;
if (!present(values[id]) && !state.required) continue;   // optional and empty
if (!validity[id]) validity[id] = message;
ok = false;
}
}
return { validity, ok };
}
function coerce(el) {
if (!el) return undefined;
if (el.type === 'checkbox') return !!el.checked;
if (el.tagName === 'SELECT') {
const n = num(el.value);
return n === null ? el.value : n;
}
if (el.type === 'number' || el.type === 'int') return num(el.value);
return el.value;
}
function values(components, adapter, extra) {
const out = {};
for (const c of (components || [])) {
if (c.kind && c.kind !== 'input') continue;
const all = (adapter && adapter.elements ? adapter.elements(c) : null) || [];
const real = all.filter((e) => e && e.type !== 'hidden');
if (!real.length) { out[c.id] = undefined; continue; }
if (c.array === true || real.length > 1) out[c.id] = real.map(coerce);
else out[c.id] = coerce(real[0]);
}
if (extra) for (const k in extra) out[k] = extra[k];
return out;
}
function applyState(opts) {
const components = (opts && opts.components) || [];
const matrix = (opts && opts.matrix) || {};
const validity = (opts && opts.validity) || {};
const prev = (opts && opts.prev) || null;
const prevValidity = (opts && opts.prevValidity) || null;
const adapter = opts && opts.adapter;
const applied = [];
if (!adapter) return applied;
for (const c of components) {
const now = matrix[c.id];
if (!now) continue;
const was = prev ? prev[c.id] : null;
if (!was || was.visible !== now.visible) {
adapter.setVisible(c, now.visible);
applied.push({ id: c.id, prop: 'visible', value: now.visible });
}
if (!was || was.editable !== now.editable) {
adapter.setEditable(c, now.editable);
applied.push({ id: c.id, prop: 'editable', value: now.editable });
}
if (!was || was.required !== now.required) {
adapter.setRequired(c, now.required);
applied.push({ id: c.id, prop: 'required', value: now.required });
}
const message = now.visible ? (validity[c.id] || '') : '';
const before = prevValidity ? (prevValidity[c.id] || '') : null;
if (before === null || before !== message) {
adapter.setValidity(c, message);
applied.push({ id: c.id, prop: 'validity', value: message });
}
}
return applied;
}
function engine(opts) {
const components = (opts && opts.components) || [];
const rules = (opts && opts.rules) || [];
const checks = (opts && opts.checks) || [];
const adapter = opts && opts.adapter;
let prev = null, prevValidity = null, passes = 0, converged = true;
return {
components, rules, checks,
values: (extra) => values(components, adapter, extra),
matrix: () => prev,
validity: () => prevValidity,
refresh(activeKey, extra) {
const v = values(components, adapter, extra);
const d = derive({ components, rules, values: v, activeKey: activeKey || null });
const check = validate({ components, checks, matrix: d.matrix, values: v, activeKey: activeKey || null });
const applied = applyState({
components, matrix: d.matrix, validity: check.validity,
prev, prevValidity, adapter,
});
prev = cloneMatrix(d.matrix);
prevValidity = check.validity;
passes = d.passes;
converged = d.converged;
return { values: v, matrix: prev, validity: prevValidity, ok: check.ok, applied, passes, converged };
},
converged: () => converged,
passes: () => passes,
};
}
function dependents(activeKey, rules) {
const out = [];
for (const r of (rules || [])) {
if (!r || !r.when || r.when.key !== activeKey) continue;
if (out.indexOf(r.target) < 0) out.push(r.target);
}
return out;
}
function createDom(root, doc) {
const attached = {};        // component id -> [extra nodes that belong to the row]
let section = null;         // the usermod's own <div class="sec">
function byName(name) {
if (!name) return [];
const list = doc.getElementsByName(name);
return list ? Array.prototype.slice.call(list) : [];
}
function controls(name) {
return byName(name).filter((e) => e.type !== 'hidden');
}
function rowEnd(x) {
let n = x;
while (n && n.nodeName !== 'BR') n = n.nextSibling;
return n || x;
}
function capNode(x) {
let a = x.previousSibling;
while (a && a.nodeName !== 'BR') {
if (a.nodeType === 3 && a.data && a.data.trim()) return a;
if (a.nodeType === 1 && a.nodeName === 'SPAN' && a.className.indexOf('rn') < 0) return a;
a = a.previousSibling;
}
return null;
}
function capText(c, txt) {
if (!c) return;
const s = ' ' + txt + ' ';
if (c.nodeType === 3) c.data = s; else c.textContent = s;
}
function setCap(name, txt) {
for (const e of controls(name)) capText(capNode(e), txt);
}
function capEach(name, fn) {
let r = 0;
for (const e of controls(name)) { capText(capNode(e), fn(r)); r++; }
}
function capHide(x, display) {
let c = capNode(x);
if (!c) return;
if (c.nodeType === 3) {
const sp = doc.createElement('span');
c.parentNode.insertBefore(sp, c);
sp.appendChild(c);
c = sp;
}
c.style.display = display;
}
function unitHide(x, display) {
let n = x.nextSibling;
while (n && n.nodeName !== 'BR') {
const nx = n.nextSibling;
if (n.nodeType === 3 && n.data.trim()) {
const sp = doc.createElement('span');
n.parentNode.insertBefore(sp, n);
sp.appendChild(n);
sp.style.display = display;
}
n = nx;
}
}
function rowShow(x, on) {
const display = on ? '' : 'none';
x.style.display = display;
capHide(x, display);
unitHide(x, display);
const br = rowEnd(x);
if (br && br.nodeName === 'BR') br.style.display = display;
}
function attach(id, node) {
if (!node) return node;
const list = attached[id] || (attached[id] = []);
list.push(node);
return node;
}
function attachedRows(id) {
return attached[id] || [];
}
function showAttached(id, on) {
const display = on ? '' : 'none';
for (const n of attachedRows(id)) n.style.display = display;
}
function appendToRow(name, node, index) {
const els = controls(name);
if (!els.length) return null;
const el = (index === undefined || index < 0) ? els[els.length - 1] : els[index];
if (!el) return null;
let last = attachedRows(name).length ? attachedRows(name)[attachedRows(name).length - 1] : rowEnd(el);
last.parentNode.insertBefore(node, last.nextSibling);
return node;
}
function insertHeading(name, title) {
const els = byName(name);
let el = null;
for (const e of els) { if (e.type !== 'hidden') { el = e; break; } }
if (!el) return false;
const cap = capNode(el);
const anchor = cap || el;
const hr = doc.createElement('hr');
hr.className = 'sml';
const p = doc.createElement('p');
const u = doc.createElement('u');
u.textContent = title;
p.appendChild(u);
anchor.parentNode.insertBefore(hr, anchor);
anchor.parentNode.insertBefore(p, anchor);
return true;
}
function dropPinClass(name) {
for (const e of byName(name)) if (e.classList) e.classList.remove('pin');
}
function markSection(anchor) {
const el = controls(anchor)[0] || byName(anchor)[0];
const sec = el && el.closest ? el.closest('.sec') : null;
if (sec) sec.classList.add('rsec');
section = sec;
return sec;
}
function appendToSection(node) {
if (!section) return null;
section.appendChild(node);
return node;
}
return {
byName, controls, rowEnd, capNode, capText, setCap, capEach, capHide, unitHide,
rowShow, attach, attachedRows, showAttached, appendToRow, appendToSection,
insertHeading, dropPinClass, markSection,
section: () => section,
};
}
function wledAdapter(root) {
const doc = (root && root.nodeType === 9) ? root
: (root && root.ownerDocument) || (typeof document !== 'undefined' ? document : null);
const dom = createDom(root, doc);
function mine(node, kind) {
if (node && node.setAttribute) node.setAttribute('data-ukit', kind);
return node;
}
return {
doc, dom,
elements: (c) => dom.byName(c.id),
setVisible(c, visible) {
for (const el of dom.controls(c.id)) dom.rowShow(el, visible);
dom.showAttached(c.id, visible);
},
setVisibleAt(id, index, visible) {
const el = dom.controls(id)[index];
if (el) dom.rowShow(el, visible);
},
setEditable(c, editable) {
for (const el of dom.controls(c.id)) {
if (el.tagName === 'SELECT') {
for (const opt of el.options) opt.disabled = !editable && !opt.selected;
} else if (el.type === 'checkbox') {
el.disabled = !editable;
} else {
el.readOnly = !editable;
}
}
},
setRequired(c, required) {
for (const el of dom.controls(c.id)) el.required = !!required;
},
setValidity(c, message) {
const msg = message || '';
for (const el of dom.controls(c.id)) {
if (el.setCustomValidity) el.setCustomValidity(msg);
}
let box = null;
for (const n of dom.attachedRows(c.id)) {
if (n.getAttribute && n.getAttribute('data-ukit') === 'error') { box = n; break; }
}
if (!msg) {
if (box) box.style.display = 'none';
return;
}
if (!box) {
box = mine(doc.createElement('span'), 'error');
box.className = 'rn e';
if (!dom.appendToRow(c.id, box)) return;
dom.attach(c.id, box);
}
box.textContent = msg;
box.style.display = '';
},
};
}
function mountHint(adapter, comp, hint) {
const doc = adapter.doc;
if (!doc) return null;
const box = doc.createElement('span');
box.className = 'rn ' + (hint.level || 'i');
box.setAttribute('data-ukit', 'hint');
box.innerHTML = hint.text || '';
if (!adapter.dom.appendToRow(comp.id, box, hint.index)) return null;
adapter.dom.attach(comp.id, box);
return box;
}
const LEVELS = { i: 'i', g: 'g', w: 'w', e: 'e' };
function mountPin(adapter, comp, root) {
const dom = adapter.dom;
if (!adapter.doc || typeof root.addDropdown !== 'function') return null;
const page = root.d || {};
const maxGpio = present(page.max_gpio) ? page.max_gpio : 50;
const pinsData = page.pinsData || [];
const reserved = page.rsvd || [];
const readOnly = page.ro_gpio || [];
const ownerName = typeof root.getOwnerName === 'function' ? root.getOwnerName : () => '';
const control = typeof root.addOption === 'function' ? root.addOption : null;
const made = [];
const wanted = dom.controls(comp.id).length;
for (let i = 0; i < wanted; i++) {
const before = dom.controls(comp.id)[i];
const current = before ? parseInt(before.value, 10) : NaN;
const sel = root.addDropdown(comp.id, i);   // the numeric argument keeps the pin class
if (!sel || !control) break;
made.push(sel);
for (let gpio = -1; gpio < maxGpio; gpio++) {
if (gpio > -1 && reserved.indexOf(gpio) >= 0) continue;
const info = pinsData.find ? pinsData.find((p) => p.p === gpio) : null;
const used = gpio > -1 && info && info.a && gpio !== current;   // not "our" pin
let text = (gpio === -1) ? 'unused' : String(gpio);
if (used) text += ' (' + ownerName(info.o, info.t, info.n) + ')';
if (gpio > -1 && readOnly.indexOf(gpio) >= 0) text += ' (input only)';
const opt = control(sel, text, gpio);
if (!opt) continue;
if (gpio === current) opt.selected = true;
else if (used) opt.disabled = true;
}
}
return made;
}
function mountFold(adapter, comp) {
const dom = adapter.dom;
const doc = adapter.doc;
if (!doc) return null;
const members = comp.members || [];
const state = { open: false };
const control = doc.createElement('button');
control.type = 'button';
control.className = 'btn btn-xs';
control.setAttribute('data-ukit', 'fold');
if (!dom.appendToSection(control)) return null;
dom.attach(comp.id, control);
function sync(host) {
if (host && host.visible === false) {
for (const id of members) {
const rows = dom.controls(id);
for (let i = 0; i < rows.length; i++) adapter.setVisibleAt(id, i, false);
}
control.style.display = 'none';
return;
}
let hidden = 0;
for (const id of members) {
const els = dom.controls(id);
for (let i = 0; i < els.length; i++) {
const used = String(els[i].value) !== '-1' && String(els[i].value) !== '';
const show = used || state.open;
if (!show) hidden++;
adapter.setVisibleAt(id, i, show);
}
}
const label = state.open
? (comp.labelOpen || '- hide unused')
: (comp.label || '+ $n unused').replace('$n', hidden);
control.textContent = label;
control.style.display = (hidden === 0 && !state.open) ? 'none' : '';
}
control.addEventListener('click', () => { state.open = !state.open; sync(); });
return { sync, control };
}
function mountStatus(adapter, comp, transport) {
const dom = adapter.dom;
const doc = adapter.doc;
if (!doc) return null;
const fields = (comp.poll && comp.poll.fields) || [];
const rows = [];
const live = {};
const box = doc.createElement('span');
box.className = 'ukit-status';
box.setAttribute('data-ukit', 'status');
for (const f of fields) {
const line = doc.createElement('span');
line.className = 'rn i';
line.style.display = 'none';
box.appendChild(line);
rows.push({ node: line, field: f });
if (f.value) live[f.value] = undefined;
}
if (!dom.appendToSection(box)) return null;
dom.attach(comp.id, box);
return {
async fetch() {
const info = await transport.getInfo();
if (!info) return live;
let shown = 0;
for (const r of rows) {
const v = transport.pluck(info, r.field.path);
if (present(v)) {
r.node.textContent = r.field.label + ': ' + v;
r.node.style.display = '';
shown++;
} else {
r.node.style.display = 'none';
}
if (r.field.value) live[r.field.value] = v;
}
box.style.display = shown ? '' : 'none';
return live;
},
values: () => live,
box,
};
}
function mountGrid(adapter, comp, transport, onDone) {
const dom = adapter.dom;
const doc = adapter.doc;
if (!doc) return null;
const wrap = doc.createElement('span');
wrap.className = 'ukit-grid';
wrap.setAttribute('data-ukit', 'grid');
wrap.style.cssText = 'display:inline-flex;flex-wrap:wrap;gap:2px;align-items:center;justify-content:center';
const buttons = [];
const note = doc.createElement('span');
note.className = 'rn w';
note.setAttribute('data-ukit', 'grid-note');
note.style.display = 'none';
for (const b of (comp.buttons || [])) {
const btn = doc.createElement('button');
btn.type = 'button';
btn.className = 'btn btn-xs';
btn.textContent = b.label;
btn.title = b.title || b.label;
if (comp.colors && comp.colors[b.color]) btn.style.borderLeftColor = comp.colors[b.color];
if (b.span && b.span > 1) btn.style.gridColumn = 'span ' + b.span;
btn.addEventListener('click', async () => {
const payload = substitute(comp.payload, '$key', b.key);
btn.disabled = true;
const res = await transport.postState(payload);
btn.disabled = false;
btn.classList.toggle('ukit-err', res === false);
setNote(res === false ? 'e' : 'g', res === false ? 'Request failed' : 'Sent: ' + b.label, 2000);
if (typeof onDone === 'function') onDone(b.key, res);
});
wrap.appendChild(btn);
buttons.push({ key: b.key, node: btn });
}
let host = wrap;
if (comp.heading) {
host = doc.createElement('span');
const hr = doc.createElement('hr');
hr.className = 'sml';
const p = doc.createElement('p');
const u = doc.createElement('u');
u.textContent = comp.heading;
p.appendChild(u);
host.appendChild(hr);
host.appendChild(p);
host.appendChild(wrap);
}
host.appendChild(note);
if (!dom.appendToSection(host)) return null;
dom.attach(comp.id, host);
let noteTimer = null;
function setNote(level, text, clearAfterMs) {
if (noteTimer) { clearTimeout(noteTimer); noteTimer = null; }
if (!text) { note.style.display = 'none'; return; }
note.className = 'rn ' + (level || 'i');
note.textContent = text;
note.style.display = '';
if (clearAfterMs) noteTimer = setTimeout(() => { note.style.display = 'none'; }, clearAfterMs);
}
function setEnabled(enabled, reason) {
for (const b of buttons) b.node.disabled = !enabled;
if (!enabled) setNote('w', reason || 'The output is not running', 0);
else if (note.className === 'rn w') setNote(null, '', 0);
}
return { setEnabled, wrap, buttons, note: setNote };
}
function substitute(template, token, value) {
if (!template) return null;
const json = JSON.stringify(template).split(token).join(value);
try { return JSON.parse(json); } catch (e) { return null; }
}
function api(root) {
const base = (root && root.getURL) ? root.getURL : (p) => p;
async function postState(payload) {
if (!payload) return false;
try {
const res = await fetch(base('/json/state'), {
method: 'POST',
headers: { 'Content-Type': 'application/json' },
body: JSON.stringify(payload),
});
return !!res && res.ok;
} catch (e) {
return false;
}
}
async function getInfo() {
try {
const res = await fetch(base('/json/info'));
if (!res || !res.ok) return null;
return await res.json();
} catch (e) {
return null;
}
}
function pluck(obj, path) {
let cur = obj;
for (const part of String(path || '').split('.')) {
if (cur === null || cur === undefined) return undefined;
cur = cur[part];
}
return cur;
}
return { postState, getInfo, pluck };
}
const STYLE_ID = 'ukit-style';
function injectStyle(doc) {
if (!doc || doc.getElementById(STYLE_ID)) return;
const css = [
'.rsec .rn{display:block;margin:3px auto 2px;padding:2px 8px;text-align:left;',
'max-width:34em;font-size:.9em;line-height:1.35;border-left:4px solid #888;',
'border-radius:3px;background:rgba(255,255,255,.05)}',
'.rsec .rn.i{border-left-color:#4a90d9}',   // explanation
'.rsec .rn.g{border-left-color:#5ac26a}',   // confirmation
'.rsec .rn.w{border-left-color:#d9a441}',   // trade-off
'.rsec .rn.e{border-left-color:#d9534f}',   // blocking problem
'.rsec .ukit-grid{display:inline-flex;flex-wrap:wrap;gap:2px;align-items:center;',
'justify-content:center;margin-top:2px}',
'.rsec .ukit-grid button.ukit-err{border-color:#d9534f}',
'.rsec .ukit-status{display:block;margin-top:2px}',
'.rsec button[data-ukit="fold"]{display:block;margin:4px auto 2px}',
].join('');
const style = doc.createElement('style');
style.id = STYLE_ID;
style.textContent = css;
(doc.head || doc.documentElement).appendChild(style);
}
function qualify(cfg) {
const prefix = cfg.prefix ? (String(cfg.prefix).slice(-1) === ':' ? String(cfg.prefix) : cfg.prefix + ':') : '';
const already = (id) => prefix !== '' && id.indexOf(prefix) === 0;
const components = (cfg.components || []).map((c) => Object.assign({}, c));
const byId = {};
for (const c of components) byId[c.id] = c;
const q = (id) => {
if (!id || typeof id !== 'string' || id.charAt(0) === '#' || already(id)) return id;
const c = byId[id];
if (!c) return id;
return prefix + id + (c.array ? '[]' : '');
};
for (const c of components) {
if (Array.isArray(c.members)) c.members = c.members.map(q);
if (c.id.charAt(0) === '#' || already(c.id)) continue;
c.id = prefix + c.id + (c.array ? '[]' : '');
}
const rules = (cfg.rules || []).map((r) => {
const copy = Object.assign({}, r);
if (copy.target) copy.target = q(copy.target);
if (copy.when) copy.when = Object.assign({}, copy.when, { key: q(copy.when.key) });
return copy;
});
const checks = (cfg.checks || []).map((k) => {
const copy = Object.assign({}, k);
if (Array.isArray(copy.target)) copy.target = copy.target.map(q);
else if (copy.target) copy.target = q(copy.target);
return copy;
});
const hints = (cfg.hints || []).map((h) => Object.assign({}, h, { id: q(h.id) }));
return Object.assign({}, cfg, {
components, rules, checks, hints,
anchor: cfg.anchor ? q(cfg.anchor) : cfg.anchor,
});
}
function page(config) {
const raw = config || {};
const win = typeof window !== 'undefined' ? window : null;
const doc = raw.document || (win ? win.document : (typeof document !== 'undefined' ? document : null));
if (!doc) return null;
if (doc.__ukitPage) { doc.__ukitPage.refresh(null); doc.__ukitPage.poll(); return doc.__ukitPage; }
const cfg = qualify(raw);
injectStyle(doc);
const root = cfg.root || win || globalThis;
const adapter = cfg.adapter || wledAdapter(doc);
const transport = cfg.api || api(root);
const components = cfg.components || [];
const eng = engine({ components, rules: cfg.rules, checks: cfg.checks, adapter });
const widgets = {};
const section = adapter.dom.markSection(cfg.anchor);
const live = Object.assign({}, cfg.values || {});
let stopped = false;
for (const c of components) {
if (c.heading && adapter.dom.controls(c.id).length) adapter.dom.insertHeading(c.id, c.heading);
if (c.widget === 'dropdown' && Array.isArray(c.options)) {
const wanted = adapter.dom.controls(c.id).length;
for (let i = 0; i < wanted && root.addDropdown; i++) {
const dd = root.addDropdown(c.id, wanted > 1 ? i : undefined);
if (!dd) break;
for (const o of c.options) {
const opt = root.addOption ? root.addOption(dd, o.label, o.value) : null;
if (opt && o.disabled) opt.disabled = true;
}
const want = dd.getAttribute ? dd.getAttribute('data-val') : null;
if (want !== null && want !== undefined && dd.options) {
for (const opt of dd.options) {
if (String(opt.value) === String(want)) { dd.value = String(opt.value); break; }
}
}
}
adapter.dom.dropPinClass(c.id);
}
if (c.widget === 'pin') mountPin(adapter, c, root);
if (c.label) adapter.dom.setCap(c.id, c.label);
if (c.captionEach) adapter.dom.capEach(c.id, (i) => c.captionEach.replace('$i', i));
if (Array.isArray(c.captions)) {
const els = adapter.dom.controls(c.id);
for (let i = 0; i < els.length && i < c.captions.length; i++) {
adapter.dom.capText(adapter.dom.capNode(els[i]), c.captions[i]);
}
}
}
for (const h of (cfg.hints || [])) {
const c = components.find((x) => x.id === h.id) || { id: h.id, kind: 'input' };
mountHint(adapter, c, h);
}
for (const c of components) {
if (c.widget === 'fold') widgets[c.id] = mountFold(adapter, c);
else if (c.widget === 'status') widgets[c.id] = mountStatus(adapter, c, transport);
else if (c.widget === 'grid') widgets[c.id] = mountGrid(adapter, c, transport, () => poll());
}
let lastOk = true;
function refresh(activeKey) {
const res = eng.refresh(activeKey, live);
lastOk = res.ok;
for (const id in widgets) {
const w = widgets[id];
if (w && w.sync) w.sync(res.matrix[id]);
if (w && w.setEnabled) {
const st = res.matrix[id];
w.setEnabled(!st || st.editable, st ? st.reason : '');
}
}
return res;
}
async function poll() {
if (stopped) return;
for (const id in widgets) {
const w = widgets[id];
if (!w || !w.fetch) continue;
const vals = await w.fetch();
if (vals) for (const k in vals) live[k] = vals[k];
}
refresh(null);
}
if (section) {
section.addEventListener('change', (ev) => {
refresh(componentIdOf(ev.target));
poll();
});
section.addEventListener('invalid', (ev) => {
const id = componentIdOf(ev.target);
if (!id) return;
const c = components.find((x) => x.id === id);
if (c) adapter.setValidity(c, ev.target.validationMessage || 'Invalid value');
}, true);
}
function componentIdOf(el) {
if (!el || !el.name) return null;
const c = components.find((x) => x.id === el.name);
return c ? c.id : null;
}
if (typeof root.pinDD === 'function' && !root.pinDD.__ukitWrapped) {
const original = root.pinDD;
const wrapped = function () { const r = original.apply(this, arguments); refresh(null); return r; };
wrapped.__ukitWrapped = true;
root.pinDD = wrapped;
}
refresh(null);
poll();
if (win && win.requestAnimationFrame) win.requestAnimationFrame(() => refresh(null));
let timer = null;
const every = cfg.pollEvery === undefined ? 1000 : cfg.pollEvery;
if (every > 0) {
timer = setInterval(() => {
if (win && win.document && win.document.hidden) return;
poll();
}, every);
}
return (doc.__ukitPage = {
engine: eng,
adapter,
widgets,
refresh,
poll,
section,
ok: () => lastOk,
componentIdOf,
getValues: (extra) => eng.values(extra),
stop() { stopped = true; if (timer) clearInterval(timer); },
});
}
return {
version: 2,
MAX_PASSES,
derive,
validate,
values,
applyState,
engine,
dependents,
condMet,
same,
num,
list,
validators,
createDom,
qualify,
injectStyle,
wledAdapter,
api,
page,
mountHint,
mountPin,
mountFold,
mountStatus,
mountGrid,
substitute,
LEVELS,
};
});
)UKITJS";
