#pragma once

#include <stddef.h>
#include <stdint.h>
#include "lumaflow_protocol.h"

/*
 * BLE peripheral input, compiled in with RESONANCER_ENABLE_BLE.
 *
 * The LumaFlow host connects to this device as a GATT client and writes raw
 * protocol frames to a single characteristic. These identifiers come from the
 * host implementation and must stay in sync with it.
 */
#ifndef RESONANCER_ENABLE_BLE
  #define RESONANCER_ENABLE_BLE 0
#endif

#define RESONANCER_BLE_SERVICE_UUID        "7e570001-3e74-4b1e-b6f4-1a91f7080001"
#define RESONANCER_BLE_CHARACTERISTIC_UUID "7e570002-3e74-4b1e-b6f4-1a91f7080002"

// AI: below section was generated by an AI
namespace ResonancerBle {

  /**
   * Start the BLE peripheral.
   *
   * @param suffix text appended to the fixed "LumaFlow" name prefix
   * @return true when the peripheral is advertising
   */
  bool start(const char* suffix);

  /** Stop advertising and release the BLE stack. */
  void stop();

  /**
   * Control advertising while the stack stays initialised. Used for the WiFi/BLE
   * coexistence policy: advertising is what makes the device discoverable, so
   * pausing it during web activity costs only the discovery window.
   */
  void setAdvertising(bool on);

  /** True while a host is connected. */
  bool isConnected();

  /** True while the peripheral is running. */
  bool isStarted();

  /**
   * True while the usermod had to enable WiFi modem sleep for coexistence.
   * ESP-IDF only allows the Bluetooth controller to run when WiFi modem sleep is
   * on, so this reflects a forced setting rather than the user's own choice.
   */
  bool isModemSleepForced();

  /**
   * Re-assert modem sleep. WLED applies its own "disable WiFi sleep" setting on
   * every connection attempt, which would bring back the coexistence error, so
   * the usermod calls this from loop() while BLE is in use.
   */
  void keepModemSleepAlive();

  /**
   * Implemented by the usermod: hands raw bytes from a BLE write to the staging
   * queue that the frame parser drains in loop(). A write carries an arbitrary
   * chunk, not a whole frame, and the callback runs in the NimBLE host task, so
   * nothing is parsed here. Declared in this header so the BLE translation unit
   * does not need to know the usermod type.
   */
  void deliverBytes(const uint8_t* data, size_t len);

} // namespace ResonancerBle
// AI: end
