/*
 * resonancer_uikit.js - data driven form engine for a WLED usermod settings page.
 *
 * The engine turns a component table plus a rule table into the three properties a
 * form element can have - visible, editable, required - and applies them through a
 * small adapter interface. Everything except the adapter is a pure function, so the
 * engine is unit tested without a browser (see test/uikit.test.js) and additionally
 * against a real settings page markup fixture (see test/page.test.js).
 *
 * Why the state is derived instead of rendered: WLED generates the settings markup on
 * its own (wled00/data/settings_um.htm, addField()) and posts the whole form back on
 * Save. A usermod therefore cannot own the controls; it adopts the generated rows and
 * annotates them. Deriving the three properties from the current values is what turns
 * that annotation into data instead of a pile of hand written event handlers.
 *
 * ---------------------------------------------------------------------------
 * Page description (built by the C++ side, see resonancer_uikit.cpp)
 * ---------------------------------------------------------------------------
 *
 *   {
 *     anchor: 'outputEnabled',        // field used to find the usermod's <div class="sec">
 *     values: { status: 'Running' },  // extra state that is not a form field
 *     components: [ {
 *        id:      'rfFreq',           // exact HTML form field name, arrays keep '[]'
 *        kind:    'input',            // 'input' | 'action' | 'display'
 *        widget:  'auto',             // 'auto'|'pin'|'dropdown'|'heading'|'hint'|'fold'|'status'|'grid'
 *        array:   false,              // field holds one entry per HTML element
 *        label:   'Frequency',        // caption override (optional)
 *        heading: 'Output',           // subsection heading inserted before the row
 *        position:'before'|'after',   // where the heading/attached nodes go
 *        options: [{ label:'Serial', value:0, disabled:false }],   // widget 'dropdown'
 *        members: ['outSeg[]'],       // widget 'fold': rows that fold away
 *        buttons: [{ key:'red', label:'Red', color:0, span:1 }],    // widget 'grid'
 *        payload: { Resonancer:{ oem:'$key' } },                    // widget 'grid'/'action'
 *        poll:    { url:'/json/info', every:1000,
 *                   fields:[{ label:'Output', path:'um.Resonancer.output' }] }
 *     } ],
 *     rules: [ {                      // restricting rules, see semantics below
 *        when:  { key:'comm', op:'eq', value:1 },   // or { key, prop, op, value }
 *        target:'udpPort', prop:'visible', value:false, reason:'UDP only'
 *     } ],
 *     checks: [ {                     // validation, see validate()
 *        target:'rfFreq', kind:'range', min:300, max:1000, message:'Out of band'
 *     } ],
 *     hints: [ { id:'bleCoexist', index:1, level:'w', text:'One radio for both.' } ]
 *   }
 *
 * Rule semantics are monotonic (fail safe): a rule may only restrict.
 *   - visible:  only value === false takes effect, combined with AND
 *   - editable: only value === false takes effect, combined with AND
 *   - required: only value === true  takes effect, combined with OR
 * A rule that would loosen a property is ignored, so the outcome never depends on the
 * order of the rule table. "Show only while X" is written as a hide rule whose
 * condition is negated (op 'ne' / 'false' / 'notin').
 *
 * A hidden component is never required and never validated: keeping it required would
 * make the browser block Save with no visible feedback, because the core submit path is
 * `if (d.Sf.checkValidity()) d.Sf.submit()` and checkValidity() renders nothing.
 *
 * ---------------------------------------------------------------------------
 * Adapter interface (implemented by wledAdapter() below, replaceable for tests)
 * ---------------------------------------------------------------------------
 *   elements(component)            -> array of elements carrying the field name
 *   setVisible(component, visible)
 *   setEditable(component, editable)
 *   setRequired(component, required)
 *   setValidity(component, message)   // '' clears
 */
// AI: below section was generated by an AI
(function (root, factory) {
	// The file is evaluated inside WLED's GetV() function body, which runs again when
	// the settings script is reloaded, so the namespace is attached only once.
	const api = factory();
	if (typeof module === 'object' && module.exports) module.exports = api;
	else root.UKIT = root.UKIT || api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
	'use strict';

	// Fixed point passes: with ~30 components re-evaluating the whole table is cheaper
	// than sorting it into a dependency graph.
	const MAX_PASSES = 3;

	const DEFAULT_BASE = { visible: true, editable: true, required: false };

	const REASON_PRIORITY = ['visible', 'editable', 'required'];

	// =========================================================================
	// pure: value helpers
	// =========================================================================

	/** Number or null. Booleans become 0/1 so a checkbox can be compared numerically. */
	function num(v) {
		if (typeof v === 'number') return Number.isFinite(v) ? v : null;
		if (typeof v === 'boolean') return v ? 1 : 0;
		if (typeof v === 'string' && v.trim() !== '') {
			const n = Number(v);
			if (Number.isFinite(n)) return n;
		}
		return null;
	}

	/** Compare a form value with a rule value: numerically when both sides are numeric. */
	function same(a, b) {
		const na = num(a), nb = num(b);
		if (na !== null && nb !== null) return na === nb;
		return a === b;
	}

	function truthy(v) {
		return v === true || v === 1 || v === '1' || v === 'true';
	}

	function present(v) {
		return v !== undefined && v !== null && v !== '';
	}

	/** Split a comma separated value list, used by the 'in' / 'notin' operators. */
	function list(v) {
		if (Array.isArray(v)) return v;
		if (typeof v === 'string') return v.split(',').map((s) => s.trim()).filter((s) => s !== '');
		return [];
	}

	// =========================================================================
	// pure: conditions
	// =========================================================================

	/** Test one condition against the current values and the previous derivation pass. */
	function condMet(cond, ctx) {
		if (!cond) return true;
		const actual = cond.prop ? (ctx.matrix[cond.key] ? ctx.matrix[cond.key][cond.prop] : undefined)
		                         : ctx.values[cond.key];
		switch (cond.op) {
			case 'eq':      return same(actual, cond.value);
			case 'ne':      return !same(actual, cond.value);
			case 'in':      return list(cond.value).some((v) => same(actual, v));
			case 'notin':   return !list(cond.value).some((v) => same(actual, v));
			case 'true':    return truthy(actual);
			case 'false':   return !truthy(actual);
			case 'ge':      return num(actual) !== null && num(actual) >= num(cond.value);
			case 'gt':      return num(actual) !== null && num(actual) >  num(cond.value);
			case 'le':      return num(actual) !== null && num(actual) <= num(cond.value);
			case 'lt':      return num(actual) !== null && num(actual) <  num(cond.value);
			case 'exists':  return present(actual);
			case 'missing': return !present(actual);
			case 'active':  return ctx.activeKey === cond.key;   // the field the user just touched
			default:        return false;                        // unknown op never matches
		}
	}

	// =========================================================================
	// pure: derive the three properties
	// =========================================================================

	/**
	 * Apply one restricting rule to a component state.
	 * Loosening rules are ignored, so rule order can never change the outcome.
	 * @returns true when the rule actually restricted the field
	 */
	function applyRule(state, rule) {
		if (!state || !rule) return false;
		if (rule.prop === 'visible' || rule.prop === 'editable') {
			if (rule.value !== false || state[rule.prop] === false) return false;
			state[rule.prop] = false;
		} else if (rule.prop === 'required') {
			if (rule.value !== true || state.required === true) return false;
			state.required = true;
		} else {
			return false;
		}
		return true;
	}

	// A field can be restricted by several rules. Which one explains the restriction is
	// decided by property priority (a hidden field matters more than a locked one), and
	// within one property by rule order.
	function finalize(state, component, reasons) {
		if (component.kind && component.kind !== 'input') state.required = false;
		if (!state.visible) state.required = false;
		state.reason = '';
		for (const prop of REASON_PRIORITY) {
			if (reasons && reasons[prop]) { state.reason = reasons[prop]; break; }
		}
	}

	function cloneMatrix(matrix) {
		const out = {};
		for (const id in matrix) out[id] = Object.assign({}, matrix[id]);
		return out;
	}

	function sameMatrix(a, b) {
		const ka = Object.keys(a), kb = Object.keys(b);
		if (ka.length !== kb.length) return false;
		for (const id of ka) {
			const x = a[id], y = b[id];
			if (!y) return false;
			if (x.visible !== y.visible || x.editable !== y.editable ||
			    x.required !== y.required || x.reason !== y.reason) return false;
		}
		return true;
	}

	/**
	 * Derive { visible, editable, required, reason } for every component.
	 *
	 * @param opts.components component table
	 * @param opts.rules      rule table
	 * @param opts.values     current values (see values())
	 * @param opts.activeKey  field the user just touched, may be null
	 * @returns {{matrix: Object, passes: number, converged: boolean}}
	 */
	function derive(opts) {
		const components = (opts && opts.components) || [];
		const rules = (opts && opts.rules) || [];
		const values = (opts && opts.values) || {};
		const activeKey = (opts && opts.activeKey) || null;

		let matrix = {};
		let converged = false;
		let pass = 0;

		for (; pass < MAX_PASSES; pass++) {
			// Every pass starts from the declared defaults, so the result never depends
			// on the previous pass having partially applied rules.
			const next = {};
			const reasons = {};
			for (const c of components) {
				next[c.id] = Object.assign({ reason: '' }, DEFAULT_BASE, c.base || {});
				reasons[c.id] = { visible: '', editable: '', required: '' };
			}
			const ctx = { values, matrix, activeKey };
			for (const rule of rules) {
				if (!condMet(rule.when, ctx)) continue;
				const state = next[rule.target];
				if (!state) continue;                     // unknown target: ignore, never throw
				const reason = reasons[rule.target];
				if (applyRule(state, rule) && !reason[rule.prop]) reason[rule.prop] = rule.reason || '';
			}
			for (const c of components) finalize(next[c.id], c, reasons[c.id]);

			if (sameMatrix(next, matrix)) { matrix = next; converged = true; break; }
			matrix = next;
		}

		// A converged run reports the pass it settled on, an unconverged one the cap it hit.
		return { matrix, passes: converged ? pass + 1 : MAX_PASSES, converged };
	}

	// =========================================================================
	// pure: validation
	// =========================================================================

	/**
	 * Named predicates. They are the closed extension point for rules that need more
	 * than a range comparison, e.g. WLED pin ownership. Each one receives the check
	 * and a context with the current values and the component table.
	 */
	const validators = {
		/** List elements that repeat a value, e.g. two output channels on one pin. */
		distinct(ctx, check) {
			const seen = [], dup = [];
			for (const v of list(ctx.values[check.target])) {
				if (!present(v) || Number(v) < 0) continue;
				if (seen.indexOf(String(v)) >= 0) dup.push(v);
				else seen.push(String(v));
			}
			return dup.length ? (check.message || 'Value used twice') : '';
		},
	};

	function evalCheck(check, ctx) {
		const value = ctx.values[check.target];
		if (check.when && !condMet(check.when, ctx)) return '';
		switch (check.kind) {
			case 'range': {
				const n = num(value);
				if (n === null) return '';
				if (check.min !== undefined && n < num(check.min)) return check.message || 'Below the minimum';
				if (check.max !== undefined && n > num(check.max)) return check.message || 'Above the maximum';
				return '';
			}
			case 'pattern': {
				if (value === undefined || value === null) return '';
				let re = null;
				try { re = new RegExp(check.pattern, check.flags || ''); } catch (e) { return ''; }
				return re.test(String(value)) ? '' : (check.message || 'Malformed value');
			}
			case 'enum':
				return list(check.values).some((v) => same(value, v)) ? '' : (check.message || 'Unsupported value');
			case 'notEmpty':
				return present(value) ? '' : (check.message || 'Required');
			case 'validator': {
				const fn = validators[check.name];
				return fn ? fn(ctx, check) : '';
			}
			default:
				return '';
		}
	}

	/**
	 * Run the element level checks.
	 *
	 * A component that is hidden is never validated, and an empty value only fails when
	 * the derivation marked the field required, so an untouched optional field cannot
	 * block the Save button.
	 *
	 * @returns {{validity: Object, ok: boolean}} validity maps component id -> message
	 */
	function validate(opts) {
		const checks = (opts && opts.checks) || [];
		const components = (opts && opts.components) || [];
		const matrix = (opts && opts.matrix) || {};
		const values = (opts && opts.values) || {};
		const activeKey = (opts && opts.activeKey) || null;
		const ctx = { values, matrix, activeKey };
		const validity = {};
		let ok = true;

		for (const check of checks) {
			const message = evalCheck(check, ctx);
			if (!message) continue;
			for (const id of (Array.isArray(check.target) ? check.target : [check.target])) {
				const state = matrix[id];
				const c = components.find((x) => x.id === id);
				if (!state || !state.visible || (c && c.kind !== 'input')) continue;
				if (!present(values[id]) && !state.required) continue;   // optional and empty
				if (!validity[id]) validity[id] = message;
				ok = false;
			}
		}
		return { validity, ok };
	}

	// =========================================================================
	// pure: values
	// =========================================================================

	/** Coerce one element to a form value: checkboxes read their checked state. */
	function coerce(el) {
		if (!el) return undefined;
		if (el.type === 'checkbox') return !!el.checked;
		if (el.tagName === 'SELECT') {
			const n = num(el.value);
			return n === null ? el.value : n;
		}
		if (el.type === 'number' || el.type === 'int') return num(el.value);
		return el.value;
	}

	/**
	 * Read the current value of every input component.
	 *
	 * The hidden type sentinel WLED emits next to each scalar field is skipped: it holds
	 * the JavaScript type of the field, never its value. An unchecked checkbox pairs with
	 * a hidden field whose value is the string "false", which is why reading
	 * element.value instead of element.checked would be wrong.
	 *
	 * @param extra additional values that are not form fields (device state)
	 */
	function values(components, adapter, extra) {
		const out = {};
		for (const c of (components || [])) {
			if (c.kind && c.kind !== 'input') continue;
			const all = (adapter && adapter.elements ? adapter.elements(c) : null) || [];
			const real = all.filter((e) => e && e.type !== 'hidden');
			if (!real.length) { out[c.id] = undefined; continue; }
			if (c.array === true || real.length > 1) out[c.id] = real.map(coerce);
			else out[c.id] = coerce(real[0]);
		}
		if (extra) for (const k in extra) out[k] = extra[k];
		return out;
	}

	// =========================================================================
	// pure: apply
	// =========================================================================

	/**
	 * Push the derivation result to the adapter, touching only what changed.
	 *
	 * @returns array of applied changes, useful for tests and for a debug log.
	 */
	function applyState(opts) {
		const components = (opts && opts.components) || [];
		const matrix = (opts && opts.matrix) || {};
		const validity = (opts && opts.validity) || {};
		const prev = (opts && opts.prev) || null;
		const prevValidity = (opts && opts.prevValidity) || null;
		const adapter = opts && opts.adapter;
		const applied = [];
		if (!adapter) return applied;

		for (const c of components) {
			const now = matrix[c.id];
			if (!now) continue;
			const was = prev ? prev[c.id] : null;

			if (!was || was.visible !== now.visible) {
				adapter.setVisible(c, now.visible);
				applied.push({ id: c.id, prop: 'visible', value: now.visible });
			}
			if (!was || was.editable !== now.editable) {
				adapter.setEditable(c, now.editable);
				applied.push({ id: c.id, prop: 'editable', value: now.editable });
			}
			if (!was || was.required !== now.required) {
				adapter.setRequired(c, now.required);
				applied.push({ id: c.id, prop: 'required', value: now.required });
			}

			const message = now.visible ? (validity[c.id] || '') : '';
			const before = prevValidity ? (prevValidity[c.id] || '') : null;
			if (before === null || before !== message) {
				adapter.setValidity(c, message);
				applied.push({ id: c.id, prop: 'validity', value: message });
			}
		}
		return applied;
	}

	// =========================================================================
	// engine: read, derive, validate, apply
	// =========================================================================

	/**
	 * Stateful wrapper. It keeps the previous matrix and validity so that only real
	 * changes reach the DOM, which also makes repeated calls idempotent.
	 */
	function engine(opts) {
		const components = (opts && opts.components) || [];
		const rules = (opts && opts.rules) || [];
		const checks = (opts && opts.checks) || [];
		const adapter = opts && opts.adapter;
		let prev = null, prevValidity = null, passes = 0, converged = true;

		return {
			components, rules, checks,
			values: (extra) => values(components, adapter, extra),
			matrix: () => prev,
			validity: () => prevValidity,
			/**
			 * @param activeKey field the user just touched (optional)
			 * @param extra     non form values, e.g. device state (optional)
			 */
			refresh(activeKey, extra) {
				const v = values(components, adapter, extra);
				const d = derive({ components, rules, values: v, activeKey: activeKey || null });
				const check = validate({ components, checks, matrix: d.matrix, values: v, activeKey: activeKey || null });
				const applied = applyState({
					components, matrix: d.matrix, validity: check.validity,
					prev, prevValidity, adapter,
				});
				prev = cloneMatrix(d.matrix);
				prevValidity = check.validity;
				passes = d.passes;
				converged = d.converged;
				return { values: v, matrix: prev, validity: prevValidity, ok: check.ok, applied, passes, converged };
			},
			converged: () => converged,
			passes: () => passes,
		};
	}

	/** Ids whose state may change when activeKey is edited - for debug output and logs. */
	function dependents(activeKey, rules) {
		const out = [];
		for (const r of (rules || [])) {
			if (!r || !r.when || r.when.key !== activeKey) continue;
			if (out.indexOf(r.target) < 0) out.push(r.target);
		}
		return out;
	}

	// =========================================================================
	// DOM runtime: the row surgery WLED's generated markup needs
	// =========================================================================

	/**
	 * WLED writes every field of a usermod straight into one <div class="sec"> with no
	 * per row wrapper, so a row is defined by what surrounds the control: the caption
	 * text before it, the text nodes (units) up to the next <br>, that <br>, and the
	 * hint boxes attached after it. Hiding a row means hiding all of those pieces, and
	 * text nodes have to be wrapped in a span before they can be hidden at all.
	 */
	function createDom(root, doc) {
		const attached = {};        // component id -> [extra nodes that belong to the row]
		let section = null;         // the usermod's own <div class="sec">

		function byName(name) {
			if (!name) return [];
			const list = doc.getElementsByName(name);
			return list ? Array.prototype.slice.call(list) : [];
		}

		function controls(name) {
			return byName(name).filter((e) => e.type !== 'hidden');
		}

		function rowEnd(x) {
			let n = x;
			while (n && n.nodeName !== 'BR') n = n.nextSibling;
			return n || x;
		}

		/** Nearest caption before the control, skipping other rows' line breaks. */
		function capNode(x) {
			let a = x.previousSibling;
			while (a && a.nodeName !== 'BR') {
				if (a.nodeType === 3 && a.data && a.data.trim()) return a;
				if (a.nodeType === 1 && a.nodeName === 'SPAN' && a.className.indexOf('rn') < 0) return a;
				a = a.previousSibling;
			}
			return null;
		}

		function capText(c, txt) {
			if (!c) return;
			const s = ' ' + txt + ' ';
			if (c.nodeType === 3) c.data = s; else c.textContent = s;
		}

		function setCap(name, txt) {
			for (const e of controls(name)) capText(capNode(e), txt);
		}

		function capEach(name, fn) {
			let r = 0;
			for (const e of controls(name)) { capText(capNode(e), fn(r)); r++; }
		}

		/** A caption must be an element before it can be hidden. */
		function capHide(x, display) {
			let c = capNode(x);
			if (!c) return;
			if (c.nodeType === 3) {
				const sp = doc.createElement('span');
				c.parentNode.insertBefore(sp, c);
				sp.appendChild(c);
				c = sp;
			}
			c.style.display = display;
		}

		/** Trailing units ("MHz") belong to the row and have to follow it. */
		function unitHide(x, display) {
			let n = x.nextSibling;
			while (n && n.nodeName !== 'BR') {
				const nx = n.nextSibling;
				if (n.nodeType === 3 && n.data.trim()) {
					const sp = doc.createElement('span');
					n.parentNode.insertBefore(sp, n);
					sp.appendChild(n);
					sp.style.display = display;
				}
				n = nx;
			}
		}

		function rowShow(x, on) {
			const display = on ? '' : 'none';
			x.style.display = display;
			capHide(x, display);
			unitHide(x, display);
			const br = rowEnd(x);
			if (br && br.nodeName === 'BR') br.style.display = display;
		}

		/** Extra nodes attached to a row (hints, errors) follow its visibility. */
		function attach(id, node) {
			if (!node) return node;
			const list = attached[id] || (attached[id] = []);
			list.push(node);
			return node;
		}

		function attachedRows(id) {
			return attached[id] || [];
		}

		function showAttached(id, on) {
			const display = on ? '' : 'none';
			for (const n of attachedRows(id)) n.style.display = display;
		}

		/** Insert a node after the row of a field, i.e. below its control. */
		function appendToRow(name, node, index) {
			const els = controls(name);
			if (!els.length) return null;
			const el = (index === undefined || index < 0) ? els[els.length - 1] : els[index];
			if (!el) return null;
			let last = attachedRows(name).length ? attachedRows(name)[attachedRows(name).length - 1] : rowEnd(el);
			last.parentNode.insertBefore(node, last.nextSibling);
			return node;
		}

		/** Subsection heading, the same markup the built-in settings pages use. */
		function insertHeading(name, title) {
			const els = byName(name);
			let el = null;
			for (const e of els) { if (e.type !== 'hidden') { el = e; break; } }
			if (!el) return false;
			const cap = capNode(el);
			const anchor = cap || el;
			const hr = doc.createElement('hr');
			hr.className = 'sml';
			const p = doc.createElement('p');
			const u = doc.createElement('u');
			u.textContent = title;
			p.appendChild(u);
			anchor.parentNode.insertBefore(hr, anchor);
			anchor.parentNode.insertBefore(p, anchor);
			return true;
		}

		/** The dropdown converter marks converted rows with the 'pin' class. */
		function dropPinClass(name) {
			for (const e of byName(name)) if (e.classList) e.classList.remove('pin');
		}

		function markSection(anchor) {
			const el = controls(anchor)[0] || byName(anchor)[0];
			const sec = el && el.closest ? el.closest('.sec') : null;
			if (sec) sec.classList.add('rsec');
			section = sec;
			return sec;
		}

		/** Widgets this usermod owns live at the end of its own section. */
		function appendToSection(node) {
			if (!section) return null;
			section.appendChild(node);
			return node;
		}

		return {
			byName, controls, rowEnd, capNode, capText, setCap, capEach, capHide, unitHide,
			rowShow, attach, attachedRows, showAttached, appendToRow, appendToSection,
			insertHeading, dropPinClass, markSection,
			section: () => section,
		};
	}

	// =========================================================================
	// adapter: the WLED settings page
	// =========================================================================

	function wledAdapter(root) {
		// Accept a document (nodeType 9) or any node inside one.
		const doc = (root && root.nodeType === 9) ? root
			: (root && root.ownerDocument) || (typeof document !== 'undefined' ? document : null);
		const dom = createDom(root, doc);

		/** Mark a node as ours so a re-run of the settings script does not duplicate it. */
		function mine(node, kind) {
			if (node && node.setAttribute) node.setAttribute('data-ukit', kind);
			return node;
		}

		return {
			doc, dom,
			elements: (c) => dom.byName(c.id),

			setVisible(c, visible) {
				for (const el of dom.controls(c.id)) dom.rowShow(el, visible);
				dom.showAttached(c.id, visible);
			},

			/** Per element visibility, for repeated rows handled by a fold widget. */
			setVisibleAt(id, index, visible) {
				const el = dom.controls(id)[index];
				if (el) dom.rowShow(el, visible);
			},

			setEditable(c, editable) {
				for (const el of dom.controls(c.id)) {
					if (el.tagName === 'SELECT') {
						// A disabled control is not submitted, so the select stays enabled
						// and only its alternatives are locked (the core does the same for
						// pins owned by another module).
						for (const opt of el.options) opt.disabled = !editable && !opt.selected;
					} else if (el.type === 'checkbox') {
						// No readonly for checkboxes; a disabled one is dropped from the
						// form post, which is only safe with the containsKey guards in
						// readFromConfig().
						el.disabled = !editable;
					} else {
						el.readOnly = !editable;
					}
				}
			},

			setRequired(c, required) {
				for (const el of dom.controls(c.id)) el.required = !!required;
			},

			setValidity(c, message) {
				const msg = message || '';
				for (const el of dom.controls(c.id)) {
					if (el.setCustomValidity) el.setCustomValidity(msg);
				}
				// The reason is rendered next to the row, because checkValidity() shows
				// nothing on its own: without this the Save button would fail silently.
				let box = null;
				for (const n of dom.attachedRows(c.id)) {
					if (n.getAttribute && n.getAttribute('data-ukit') === 'error') { box = n; break; }
				}
				if (!msg) {
					if (box) box.style.display = 'none';
					return;
				}
				if (!box) {
					box = mine(doc.createElement('span'), 'error');
					box.className = 'rn e';
					if (!dom.appendToRow(c.id, box)) return;
					dom.attach(c.id, box);
				}
				box.textContent = msg;
				box.style.display = '';
			},
		};
	}

	// =========================================================================
	// components: the widgets this usermod adds on top of the generated form
	// =========================================================================

	/**
	 * Hint box below the row it belongs to: the one part of this form the generated
	 * markup has no equivalent for.
	 *   level i = explanation, g = confirmation, w = trade-off, e = blocking problem
	 */
	function mountHint(adapter, comp, hint) {
		const doc = adapter.doc;
		if (!doc) return null;
		const box = doc.createElement('span');
		box.className = 'rn ' + (hint.level || 'i');
		box.setAttribute('data-ukit', 'hint');
		box.innerHTML = hint.text || '';
		if (!adapter.dom.appendToRow(comp.id, box, hint.index)) return null;
		adapter.dom.attach(comp.id, box);
		return box;
	}

	const LEVELS = { i: 'i', g: 'g', w: 'w', e: 'e' };

	/**
	 * Pin rows.
	 *
	 * The core's pinDD() only converts fields whose name contains "pin", so a usermod
	 * field called rfPins stays a plain number input and loses the pin owner information.
	 * This mirrors what the core does for its own pin fields: one option per GPIO, used
	 * pins named and disabled, read-only pins marked, and the 'pin' class kept so the
	 * core's own UI() handler keeps the ownership in sync between rows.
	 */
	function mountPin(adapter, comp, root) {
		const dom = adapter.dom;
		if (!adapter.doc || typeof root.addDropdown !== 'function') return null;
		const page = root.d || {};
		const maxGpio = present(page.max_gpio) ? page.max_gpio : 50;
		const pinsData = page.pinsData || [];
		const reserved = page.rsvd || [];
		const readOnly = page.ro_gpio || [];
		const ownerName = typeof root.getOwnerName === 'function' ? root.getOwnerName : () => '';
		const control = typeof root.addOption === 'function' ? root.addOption : null;
		const made = [];

		const wanted = dom.controls(comp.id).length;
		for (let i = 0; i < wanted; i++) {
			const before = dom.controls(comp.id)[i];
			const current = before ? parseInt(before.value, 10) : NaN;
			const sel = root.addDropdown(comp.id, i);   // the numeric argument keeps the pin class
			if (!sel || !control) break;
			made.push(sel);
			for (let gpio = -1; gpio < maxGpio; gpio++) {
				if (gpio > -1 && reserved.indexOf(gpio) >= 0) continue;
				const info = pinsData.find ? pinsData.find((p) => p.p === gpio) : null;
				const used = gpio > -1 && info && info.a && gpio !== current;   // not "our" pin
				let text = (gpio === -1) ? 'unused' : String(gpio);
				if (used) text += ' (' + ownerName(info.o, info.t, info.n) + ')';
				if (gpio > -1 && readOnly.indexOf(gpio) >= 0) text += ' (input only)';
				const opt = control(sel, text, gpio);
				if (!opt) continue;
				if (gpio === current) opt.selected = true;
				else if (used) opt.disabled = true;
			}
		}
		return made;
	}

	/**
	 * Fold: repeated rows (one per segment or channel) whose untouched entries are hidden
	 * behind a small reveal control, so the list stays short without losing the ability
	 * to edit an entry.
	 */
	function mountFold(adapter, comp) {
		const dom = adapter.dom;
		const doc = adapter.doc;
		if (!doc) return null;
		const members = comp.members || [];
		const state = { open: false };

		const control = doc.createElement('button');
		control.type = 'button';
		control.className = 'btn btn-xs';
		control.setAttribute('data-ukit', 'fold');
		if (!dom.appendToSection(control)) return null;
		dom.attach(comp.id, control);

		function sync(host) {
			// The host component decides first: while it is hidden (the output is off, for
			// example) the fold hides its rows instead of revealing the mapped ones.
			if (host && host.visible === false) {
				for (const id of members) {
					const rows = dom.controls(id);
					for (let i = 0; i < rows.length; i++) adapter.setVisibleAt(id, i, false);
				}
				control.style.display = 'none';
				return;
			}
			let hidden = 0;
			for (const id of members) {
				// A repeated field has one row per element, so the fold works element by
				// element: an entry that was never mapped hides, a mapped one stays.
				const els = dom.controls(id);
				for (let i = 0; i < els.length; i++) {
					const used = String(els[i].value) !== '-1' && String(els[i].value) !== '';
					const show = used || state.open;
					if (!show) hidden++;
					adapter.setVisibleAt(id, i, show);
				}
			}
			const label = state.open
				? (comp.labelOpen || '- hide unused')
				: (comp.label || '+ $n unused').replace('$n', hidden);
			control.textContent = label;
			// A reveal control with nothing to reveal is noise: the whole control only
			// exists while something is folded away or while it is open.
			control.style.display = (hidden === 0 && !state.open) ? 'none' : '';
		}

		control.addEventListener('click', () => { state.open = !state.open; sync(); });
		return { sync, control };
	}

	/**
	 * Status: values the form does not hold, read from the device while the page is
	 * open. Used for the live output state and for the result of the last preset
	 * command, and it feeds those values back into the rule values so a rule can depend
	 * on the device state.
	 */
	function mountStatus(adapter, comp, transport) {
		const dom = adapter.dom;
		const doc = adapter.doc;
		if (!doc) return null;
		const fields = (comp.poll && comp.poll.fields) || [];
		const rows = [];
		const live = {};

		const box = doc.createElement('span');
		box.className = 'ukit-status';
		box.setAttribute('data-ukit', 'status');
		for (const f of fields) {
			const line = doc.createElement('span');
			line.className = 'rn i';
			// Hidden until the device has something to report: an empty "Preset: -" row
			// is noise, and the box disappears entirely while nothing is known.
			line.style.display = 'none';
			box.appendChild(line);
			rows.push({ node: line, field: f });
			if (f.value) live[f.value] = undefined;
		}
		if (!dom.appendToSection(box)) return null;
		dom.attach(comp.id, box);

		return {
			/** Read the device state and render it; returns the values for the rules. */
			async fetch() {
				const info = await transport.getInfo();
				if (!info) return live;
				let shown = 0;
				for (const r of rows) {
					const v = transport.pluck(info, r.field.path);
					if (present(v)) {
						r.node.textContent = r.field.label + ': ' + v;
						r.node.style.display = '';
						shown++;
					} else {
						r.node.style.display = 'none';
					}
					if (r.field.value) live[r.field.value] = v;
				}
				box.style.display = shown ? '' : 'none';
				return live;
			},
			values: () => live,
			box,
		};
	}

	/**
	 * Action grid: trigger buttons built from the registry. Each button posts its own
	 * payload; the result is read back through the status poll, so a click never reloads
	 * the page and a refusal is visible instead of silent.
	 */
	function mountGrid(adapter, comp, transport, onDone) {
		const dom = adapter.dom;
		const doc = adapter.doc;
		if (!doc) return null;
		const wrap = doc.createElement('span');
		wrap.className = 'ukit-grid';
		wrap.setAttribute('data-ukit', 'grid');
		wrap.style.cssText = 'display:inline-flex;flex-wrap:wrap;gap:2px;align-items:center;justify-content:center';
		const buttons = [];

		// The reason line is what turns "the click did nothing" into "the output is not
		// running": it also reports the outcome of a command that was posted.
		const note = doc.createElement('span');
		note.className = 'rn w';
		note.setAttribute('data-ukit', 'grid-note');
		note.style.display = 'none';

		for (const b of (comp.buttons || [])) {
			const btn = doc.createElement('button');
			btn.type = 'button';
			btn.className = 'btn btn-xs';
			btn.textContent = b.label;
			btn.title = b.title || b.label;
			if (comp.colors && comp.colors[b.color]) btn.style.borderLeftColor = comp.colors[b.color];
			if (b.span && b.span > 1) btn.style.gridColumn = 'span ' + b.span;
			btn.addEventListener('click', async () => {
				const payload = substitute(comp.payload, '$key', b.key);
				btn.disabled = true;
				const res = await transport.postState(payload);
				btn.disabled = false;
				btn.classList.toggle('ukit-err', res === false);
				// Immediate feedback: the device result follows through the status poll.
				setNote(res === false ? 'e' : 'g', res === false ? 'Request failed' : 'Sent: ' + b.label, 2000);
				if (typeof onDone === 'function') onDone(b.key, res);
			});
			wrap.appendChild(btn);
			buttons.push({ key: b.key, node: btn });
		}

		// The preset grid has no config field behind it, so it brings its own heading
		// instead of inserting one in front of a generated row.
		let host = wrap;
		if (comp.heading) {
			host = doc.createElement('span');
			const hr = doc.createElement('hr');
			hr.className = 'sml';
			const p = doc.createElement('p');
			const u = doc.createElement('u');
			u.textContent = comp.heading;
			p.appendChild(u);
			host.appendChild(hr);
			host.appendChild(p);
			host.appendChild(wrap);
		}
		host.appendChild(note);
		if (!dom.appendToSection(host)) return null;
		dom.attach(comp.id, host);

		let noteTimer = null;
		function setNote(level, text, clearAfterMs) {
			if (noteTimer) { clearTimeout(noteTimer); noteTimer = null; }
			if (!text) { note.style.display = 'none'; return; }
			note.className = 'rn ' + (level || 'i');
			note.textContent = text;
			note.style.display = '';
			if (clearAfterMs) noteTimer = setTimeout(() => { note.style.display = 'none'; }, clearAfterMs);
		}

		/**
		 * @param enabled whether a preset may be sent right now
		 * @param reason  why not, shown under the buttons
		 */
		function setEnabled(enabled, reason) {
			for (const b of buttons) b.node.disabled = !enabled;
			if (!enabled) setNote('w', reason || 'The output is not running', 0);
			else if (note.className === 'rn w') setNote(null, '', 0);
		}
		return { setEnabled, wrap, buttons, note: setNote };
	}

	/** Replace $key style placeholders in a payload template. */
	function substitute(template, token, value) {
		if (!template) return null;
		const json = JSON.stringify(template).split(token).join(value);
		try { return JSON.parse(json); } catch (e) { return null; }
	}

	// =========================================================================
	// api: settings page safe transport (never uses main page globals)
	// =========================================================================

	function api(root) {
		const base = (root && root.getURL) ? root.getURL : (p) => p;

		async function postState(payload) {
			if (!payload) return false;
			try {
				const res = await fetch(base('/json/state'), {
					method: 'POST',
					headers: { 'Content-Type': 'application/json' },
					body: JSON.stringify(payload),
				});
				return !!res && res.ok;
			} catch (e) {
				return false;
			}
		}

		async function getInfo() {
			try {
				const res = await fetch(base('/json/info'));
				if (!res || !res.ok) return null;
				return await res.json();
			} catch (e) {
				return null;
			}
		}

		function pluck(obj, path) {
			let cur = obj;
			for (const part of String(path || '').split('.')) {
				if (cur === null || cur === undefined) return undefined;
				cur = cur[part];
			}
			return cur;
		}

		return { postState, getInfo, pluck };
	}

	// =========================================================================
	// page: mount the widgets, wire the events, keep everything derived
	// =========================================================================

	/**
	 * Stylesheet for the parts that are ours.
	 *
	 * WLED's generated form has no equivalent for a hint box, a preset grid or a status
	 * line, so these three get a minimal look of their own. Everything else keeps the
	 * built-in styling: the rules are scoped to the usermod's own section, which
	 * markSection() tags with 'rsec'.
	 */
	const STYLE_ID = 'ukit-style';

	function injectStyle(doc) {
		if (!doc || doc.getElementById(STYLE_ID)) return;
		const css = [
			// Hint box: centred box, left aligned text, level colour on the left edge.
			'.rsec .rn{display:block;margin:3px auto 2px;padding:2px 8px;text-align:left;',
			'max-width:34em;font-size:.9em;line-height:1.35;border-left:4px solid #888;',
			'border-radius:3px;background:rgba(255,255,255,.05)}',
			'.rsec .rn.i{border-left-color:#4a90d9}',   // explanation
			'.rsec .rn.g{border-left-color:#5ac26a}',   // confirmation
			'.rsec .rn.w{border-left-color:#d9a441}',   // trade-off
			'.rsec .rn.e{border-left-color:#d9534f}',   // blocking problem
			// Preset grid and status line.
			'.rsec .ukit-grid{display:inline-flex;flex-wrap:wrap;gap:2px;align-items:center;',
			'justify-content:center;margin-top:2px}',
			'.rsec .ukit-grid button.ukit-err{border-color:#d9534f}',
			'.rsec .ukit-status{display:block;margin-top:2px}',
			// Reveal control of a fold.
			'.rsec button[data-ukit="fold"]{display:block;margin:4px auto 2px}',
		].join('');
		const style = doc.createElement('style');
		style.id = STYLE_ID;
		style.textContent = css;
		(doc.head || doc.documentElement).appendChild(style);
	}

	/**
	 * Resolve the short ids of a page description into the form field names WLED
	 * generated: '<usermod>:<field>', plus the '[]' suffix of a repeated field.
	 *
	 * An id starting with '#' belongs to a widget this usermod draws itself and is left
	 * untouched. References that do not name a component (a device state value used by a
	 * rule, for example) are left untouched as well, so the rule table stays readable.
	 *
	 * The function is idempotent: a description that was already qualified is passed
	 * through unchanged, so re-mounting a page with the same data is harmless.
	 */
	function qualify(cfg) {
		const prefix = cfg.prefix ? (String(cfg.prefix).slice(-1) === ':' ? String(cfg.prefix) : cfg.prefix + ':') : '';
		const already = (id) => prefix !== '' && id.indexOf(prefix) === 0;

		// Copies are made on the way: the description is not modified, so mounting the
		// same data twice produces the same result.
		const components = (cfg.components || []).map((c) => Object.assign({}, c));
		const byId = {};
		for (const c of components) byId[c.id] = c;

		const q = (id) => {
			if (!id || typeof id !== 'string' || id.charAt(0) === '#' || already(id)) return id;
			const c = byId[id];
			// Only ids that name a component are form field names; anything else is a
			// value the page feeds in (device state) and keeps its name.
			if (!c) return id;
			return prefix + id + (c.array ? '[]' : '');
		};

		for (const c of components) {
			// Members are qualified first: a widget the usermod draws itself has no field
			// of its own, but the rows it folds away still belong to a component.
			if (Array.isArray(c.members)) c.members = c.members.map(q);
			if (c.id.charAt(0) === '#' || already(c.id)) continue;
			c.id = prefix + c.id + (c.array ? '[]' : '');
		}
		const rules = (cfg.rules || []).map((r) => {
			const copy = Object.assign({}, r);
			if (copy.target) copy.target = q(copy.target);
			if (copy.when) copy.when = Object.assign({}, copy.when, { key: q(copy.when.key) });
			return copy;
		});
		const checks = (cfg.checks || []).map((k) => {
			const copy = Object.assign({}, k);
			if (Array.isArray(copy.target)) copy.target = copy.target.map(q);
			else if (copy.target) copy.target = q(copy.target);
			return copy;
		});
		const hints = (cfg.hints || []).map((h) => Object.assign({}, h, { id: q(h.id) }));

		return Object.assign({}, cfg, {
			components, rules, checks, hints,
			anchor: cfg.anchor ? q(cfg.anchor) : cfg.anchor,
		});
	}

	/**
	 * Entry point. Everything the settings page needs happens here, in one call.
	 *
	 * Lifecycle facts this has to live with (see wled00/data/settings_um.htm):
	 *   - the whole decoration stream is emitted inside GetV(), which can run again
	 *   - pin rows are converted to <select> afterwards, which replaces the nodes
	 *   - the core submits through `if (d.Sf.checkValidity()) d.Sf.submit()`
	 */
	function page(config) {
		const raw = config || {};
		const win = typeof window !== 'undefined' ? window : null;
		const doc = raw.document || (win ? win.document : (typeof document !== 'undefined' ? document : null));
		if (!doc) return null;

		// The decoration stream is emitted inside GetV(), which can run more than once
		// per page visit, so a second call reuses the mounted page instead of adding a
		// duplicate set of widgets.
		if (doc.__ukitPage) { doc.__ukitPage.refresh(null); doc.__ukitPage.poll(); return doc.__ukitPage; }

		const cfg = qualify(raw);
		injectStyle(doc);

		const root = cfg.root || win || globalThis;
		const adapter = cfg.adapter || wledAdapter(doc);
		const transport = cfg.api || api(root);
		const components = cfg.components || [];
		const eng = engine({ components, rules: cfg.rules, checks: cfg.checks, adapter });
		const widgets = {};
		const section = adapter.dom.markSection(cfg.anchor);
		// Values the form does not hold (device state) are merged into the rule values.
		const live = Object.assign({}, cfg.values || {});
		let stopped = false;

		// --- mount the widgets this usermod owns ------------------------------
		for (const c of components) {
			// A heading is placed in front of a field row; a widget without a field
			// renders its own heading (see mountGrid).
			if (c.heading && adapter.dom.controls(c.id).length) adapter.dom.insertHeading(c.id, c.heading);
			if (c.widget === 'dropdown' && Array.isArray(c.options)) {
				// A repeated field needs one conversion per element: the core converts
				// the first remaining number input on every call and returns null when
				// there is none left.
				const wanted = adapter.dom.controls(c.id).length;
				for (let i = 0; i < wanted && root.addDropdown; i++) {
					const dd = root.addDropdown(c.id, wanted > 1 ? i : undefined);
					if (!dd) break;
					for (const o of c.options) {
						const opt = root.addOption ? root.addOption(dd, o.label, o.value) : null;
						if (opt && o.disabled) opt.disabled = true;
					}
					// addDropdown() carries the stored value in data-val; it has to be
					// selected explicitly once the options exist.
					const want = dd.getAttribute ? dd.getAttribute('data-val') : null;
					if (want !== null && want !== undefined && dd.options) {
						for (const opt of dd.options) {
							if (String(opt.value) === String(want)) { dd.value = String(opt.value); break; }
						}
					}
				}
				adapter.dom.dropPinClass(c.id);
			}
			if (c.widget === 'pin') mountPin(adapter, c, root);
			if (c.label) adapter.dom.setCap(c.id, c.label);
			if (c.captionEach) adapter.dom.capEach(c.id, (i) => c.captionEach.replace('$i', i));
			if (Array.isArray(c.captions)) {
				// Repeated rows with individual captions (SCK, MISO, MOSI, ...).
				const els = adapter.dom.controls(c.id);
				for (let i = 0; i < els.length && i < c.captions.length; i++) {
					adapter.dom.capText(adapter.dom.capNode(els[i]), c.captions[i]);
				}
			}
		}
		for (const h of (cfg.hints || [])) {
			const c = components.find((x) => x.id === h.id) || { id: h.id, kind: 'input' };
			mountHint(adapter, c, h);
		}
		for (const c of components) {
			if (c.widget === 'fold') widgets[c.id] = mountFold(adapter, c);
			else if (c.widget === 'status') widgets[c.id] = mountStatus(adapter, c, transport);
			else if (c.widget === 'grid') widgets[c.id] = mountGrid(adapter, c, transport, () => poll());
		}

		// --- derive, validate, apply -----------------------------------------
		let lastOk = true;
		function refresh(activeKey) {
			const res = eng.refresh(activeKey, live);
			lastOk = res.ok;
			// Widgets run after the derivation on purpose: a widget's own layout rule
			// (the reveal control of a fold) has the last word on its member rows.
			for (const id in widgets) {
				const w = widgets[id];
				if (w && w.sync) w.sync(res.matrix[id]);
				if (w && w.setEnabled) {
					const st = res.matrix[id];
					w.setEnabled(!st || st.editable, st ? st.reason : '');
				}
			}
			return res;
		}

		/** Read the device state, merge it into the rule values, then re-derive. */
		async function poll() {
			if (stopped) return;
			for (const id in widgets) {
				const w = widgets[id];
				if (!w || !w.fetch) continue;
				// A widget that reads device state hands its values back for the rules.
				const vals = await w.fetch();
				if (vals) for (const k in vals) live[k] = vals[k];
			}
			refresh(null);
		}

		// --- events -----------------------------------------------------------
		if (section) {
			section.addEventListener('change', (ev) => {
				refresh(componentIdOf(ev.target));
				poll();
			});
			// The browser reports the first invalid control here; checkValidity() itself
			// renders nothing, so the reason is written next to the row.
			section.addEventListener('invalid', (ev) => {
				const id = componentIdOf(ev.target);
				if (!id) return;
				const c = components.find((x) => x.id === id);
				if (c) adapter.setValidity(c, ev.target.validationMessage || 'Invalid value');
			}, true);
		}

		function componentIdOf(el) {
			if (!el || !el.name) return null;
			const c = components.find((x) => x.id === el.name);
			return c ? c.id : null;
		}

		// --- follow the core's own DOM churn ---------------------------------
		// pinDD() replaces the pin inputs with selects, which drops everything attached
		// to those nodes, so the derivation runs again once it has finished.
		if (typeof root.pinDD === 'function' && !root.pinDD.__ukitWrapped) {
			const original = root.pinDD;
			const wrapped = function () { const r = original.apply(this, arguments); refresh(null); return r; };
			wrapped.__ukitWrapped = true;
			root.pinDD = wrapped;
		}

		// Initial state, then again on the frame after the core loaded the form values
		// (this script runs before GetV() and before the pin rows are converted).
		refresh(null);
		poll();
		if (win && win.requestAnimationFrame) win.requestAnimationFrame(() => refresh(null));

		// Keep the status row and the grid availability live while the page is visible.
		let timer = null;
		const every = cfg.pollEvery === undefined ? 1000 : cfg.pollEvery;
		if (every > 0) {
			timer = setInterval(() => {
				if (win && win.document && win.document.hidden) return;
				poll();
			}, every);
		}

		return (doc.__ukitPage = {
			engine: eng,
			adapter,
			widgets,
			refresh,
			poll,
			section,
			ok: () => lastOk,
			componentIdOf,
			getValues: (extra) => eng.values(extra),
			stop() { stopped = true; if (timer) clearInterval(timer); },
		});
	}

	return {
		version: 2,
		MAX_PASSES,
		derive,
		validate,
		values,
		applyState,
		engine,
		dependents,
		condMet,
		same,
		num,
		list,
		validators,
		createDom,
		qualify,
		injectStyle,
		wledAdapter,
		api,
		page,
		mountHint,
		mountPin,
		mountFold,
		mountStatus,
		mountGrid,
		substitute,
		LEVELS,
	};
});
// AI: end
