#pragma once

#include <stdint.h>

#include "lumaflow_protocol.h"   // LumaFlow::Auth, handed to the licence check

/*
 * Output device abstraction.
 *
 * This header is the only part of the output path that is shipped with the open
 * source implementation. The concrete implementation lives outside this
 * repository and is compiled in only when RESONANCER_ENABLE_RF is enabled for
 * the build environment.
 *
 * Keep this file free of WLED dependencies so an implementation can be built and
 * tested without the firmware sources.
 */

// Pin selector for pins that are not used by a concrete driver.
// Pass RESONANCER_PIN_UNUSED for MISO/SS/GD0/GD2 when the board does not wire them.
constexpr int8_t RESONANCER_PIN_UNUSED = -1;

// Default pin assignment and frequency of the reference board. They only pre-fill
// the settings page and sanity check a stored value; every pin and the frequency
// stay user configurable. The numbers describe the reference hardware, so they are
// defined next to the implementation - by the implementation itself, or by the
// stub in a build without an output device (see the two definitions of these
// symbols). The implementation owns this bus and starts it itself, so the pins must
// not collide with a SPI based LED bus.
extern const int8_t RESONANCER_DEFAULT_SCK;
extern const int8_t RESONANCER_DEFAULT_MISO;
extern const int8_t RESONANCER_DEFAULT_MOSI;
extern const int8_t RESONANCER_DEFAULT_SS;
extern const int8_t RESONANCER_DEFAULT_GD0;
extern const int8_t RESONANCER_DEFAULT_GD2;
extern const float  RESONANCER_DEFAULT_RF_FREQ;   // MHz

// Runtime tunables. Everything the implementation needs beyond this is fixed in the
// implementation.
// AI: below section was generated by an AI
struct RFRuntimeConfig {
  float rf_freq = 0;   // MHz, initialised from RESONANCER_DEFAULT_RF_FREQ
};

/*
 * 8 bit colour triple handed to the output device.
 */
struct RgbColor {
  uint8_t r;
  uint8_t g;
  uint8_t b;
};

/*
 * Result of the (upper layer) licence check. The output device turns the licence
 * state into its own behaviour, so an unlicensed device can be de-initialised from
 * the implementation side if required.
 */
enum class AuthResult : uint8_t {
  Ok = 0,           // licence valid
  NotAuthenticated, // no valid licence received yet
  AuthFailed,       // licence rejected
  AuthExpired,      // licence timed out
  RfRestricted,     // regulatory restriction active
};

class RFDevice {
  public:
    virtual ~RFDevice() = default;

    /**
     * @brief Static configuration, called once at start up.
     *
     * @param channelCount number of channels handled by this device (1..10)
     * @param sckPin       SPI clock pin, RESONANCER_PIN_UNUSED when not wired
     * @param misoPin      SPI MISO pin, RESONANCER_PIN_UNUSED when not wired
     * @param mosiPin      SPI MOSI pin, RESONANCER_PIN_UNUSED when not wired
     * @param ssPin        SPI chip select pin
     * @param gd0Pin       device interrupt pin, RESONANCER_PIN_UNUSED when not wired
     * @param gd2Pin       device status pin, RESONANCER_PIN_UNUSED when not wired
     * @retval true when the configuration was accepted
     */
    virtual bool InitConfig(uint8_t channelCount, int8_t sckPin, int8_t misoPin, int8_t mosiPin,
                            int8_t ssPin, int8_t gd0Pin, int8_t gd2Pin) = 0;

    /** @brief Enable the device and enter the operating state. @retval true on success */
    virtual bool DeviceInit() = 0;

    /** @brief Runtime parameter update that does not require re-configuration. */
    virtual void changeRuntimeConfig(const RFRuntimeConfig& cfg) = 0;

    /**
     * @brief Submit one packet of RGB data.
     * @param channelCount number of entries in arr (never exceeds the configured count)
     * @param arr          colour array with at least channelCount entries
     */
    virtual void submitRGBPacket(uint8_t channelCount, const RgbColor* arr) = 0;

    /** @brief Push the licence decision (signature validation happens in the upper layer). */
    virtual void setAuthentication(AuthResult result) = 0;

    /** @brief Trigger a device built-in preset colour, index 0..16. */
    virtual void setOemCommand(uint8_t index) = 0;

    /** @brief Disable the device and leave the operating state. */
    virtual void DeviceUnInit() = 0;

    /** @brief True while the previous packet has not reached the radio yet. */
    virtual bool isBusy() const { return false; }

    /** @brief True while a submitted preset has not been transmitted yet. */
    virtual bool isOemPending() const { return false; }

    /** @brief Duration of the last transmission in microseconds, 0 when unknown. */
    virtual uint32_t lastTxMicros() const { return 0; }

    /** @brief How often the device was configured, for diagnostics. */
    virtual uint32_t configCount() const { return 0; }

    /** @brief How long the last transmitted packet waited in the queue, in milliseconds. */
    virtual uint32_t lastQueueMs() const { return 0; }

    /** @brief Number of packets actually handed to the radio. */
    virtual uint32_t txCount() const { return 0; }

    /** @brief Transmissions that needed the full GDO0 extension, i.e. ran long. */
    virtual uint32_t txTimeouts() const { return 0; }

    /** @brief Measured packet rate in packets per second. */
    virtual uint32_t txRate() const { return 0; }

    /** @brief Human readable driver name, used for status reporting. */
    virtual const char* getName() const = 0;

    /** @brief True when the device is currently enabled and operating. */
    virtual bool isActive() const = 0;
};

/*
 * Build time selection of the concrete implementation.
 *
 * RESONANCER_ENABLE_RF == 0 : only the stub implementation
 *                             (resonancer_rf_stub.cpp) is compiled, so no output
 *                             device is part of the binary.
 * RESONANCER_ENABLE_RF == 1 : the implementation provides createRfDevice(); the
 *                             contract is this header.
 */
#ifndef RESONANCER_ENABLE_RF
  #define RESONANCER_ENABLE_RF 0
#endif

// Number of built-in preset commands of the output device, index 0..16. The names
// live in the usermod (RESONANCER_OEM_NAMES); the implementation defines the wire
// level encoding.
constexpr uint8_t RESONANCER_OEM_COMMAND_COUNT = 17;

/**
 * Factory implemented outside this repository when RESONANCER_ENABLE_RF is 1.
 * Returns a statically allocated device, or nullptr when it is unavailable.
 */
RFDevice* createRfDevice();

/**
 * Publish the preset buttons this output implementation offers.
 *
 * Called once from the usermod's setup(). The registration order defines the slot
 * index that is later handed to RFDevice::setOemCommand(), so it has to match the
 * preset table of the implementation. The keys, labels and stripe colours registered
 * here are the only part of a preset that the settings page sees: the wire level
 * encoding stays in the implementation.
 *
 * A build without an output implementation leaves the registry empty, which simply
 * means the settings page shows no preset buttons.
 */
void resonancerRegisterOemKeys();

/**
 * Turn one decoded AUTH frame into a licence verdict.
 *
 * The usermod calls this for every accepted AUTH frame and hands the result to the
 * output device through setAuthentication(), so the device can stop operating on its
 * own when the licence is not valid. It is also called once at start up with an
 * empty frame, which is the verdict before any host frame arrived: an implementation
 * that needs a frame reports NotAuthenticated there, a development implementation may
 * grant the output. The policy (signature validation, expiry, restrictions) is
 * deliberately kept next to the device implementation and outside this repository.
 * 
 * The following document describes the public rules for authentication code verification
 * for implementers' reference. Rules are listed in execution order; failure of
 * any rule results in authentication failure.
 * 
 * ─────────────────────────────────────────────────────────────
 * I. Device Binding and Time Monotonicity
 * ─────────────────────────────────────────────────────────────
 *
 * 1. Verify that the device MAC address matches the one in the host message.
 *
 * 2. Verify that the host message time field is greater than or equal to
 *    the maximum time recorded by the device (to prevent time rollback).
 *
 * ─────────────────────────────────────────────────────────────
 * II. Signature String Decoding
 * ─────────────────────────────────────────────────────────────
 *
 * 3. Verify that the signature string can be correctly decoded.
 *
 * 4. Verify that the signature string length meets the minimum length requirement.
 *
 * 5. Verify that signature string decryption succeeds and the integrity check passes.
 *
 * ─────────────────────────────────────────────────────────────
 * III. Message Structure Parsing
 * ─────────────────────────────────────────────────────────────
 *
 * 6. Verify the decrypted plaintext structure (treating the third field as
 *    the message extension).
 *
 * 7. (Optional) Verify that the message extension version is numeric and within the supported range.
 *
 * ─────────────────────────────────────────────────────────────
 * IV. Time Window
 * ─────────────────────────────────────────────────────────────
 *
 * 8. Verify that the not-before lower bound is numeric and the device's current
 *    time is greater than or equal to the not-before lower bound.
 *
 * 9. Verify that the expiration upper bound is numeric and the device's current
 *    time is less than or equal to the expiration upper bound.
 *
 * 10. Verify that the not-before lower bound is less than or equal to the
 *     expiration upper bound.
 *
 * ─────────────────────────────────────────────────────────────
 * V. Immediacy and Anti-Replay
 * ─────────────────────────────────────────────────────────────
 *
 * 11. Verify that the dynamic code is a 6-digit number.
 *
 * 12. Verify that the dynamic code matches the value computed locally by the device.
 *
 * 13. Verify that dynamic code comparison uses constant-time comparison.
 *
 * 14. Verify that the unique identifier has not appeared in the device's
 *     used-identifier cache.
 *
 * ─────────────────────────────────────────────────────────────
 * VI. Signature Verification
 * ─────────────────────────────────────────────────────────────
 *
 * 15. Verify that the signature field is non-empty and can be correctly decoded.
 *
 * 16. Verify that the signature data is concatenated in the fixed order.
 *
 * 17. Verify that the digital signature passes verification.
 *
 * ─────────────────────────────────────────────────────────────
 * VII. State Update
 * ─────────────────────────────────────────────────────────────
 *
 * 18. After all checks pass, cache the expiration upper bound, record the
 *     unique identifier, and set the activation flag.
 *
 * 19. After activation, periodically check whether the device's current time
 *     exceeds the cached expiration upper bound.
 *
 * 20. When the device's current time exceeds the cached expiration upper bound,
 *     authorization must be revoked.
 *
 * ─────────────────────────────────────────────────────────────
 * VIII. Lock Semantics
 * ─────────────────────────────────────────────────────────────
 *
 * 21. After authorization revocation, the device must enter the locked state
 *     and must not return authentication success before power-on reset.
 *
 * 22. After authentication failure, the device must enter the locked state
 *     and must not return authentication success before power-on reset.
 *
 * 23. When the time-segment blacklist takes effect, the device must enter the
 *     locked state and must not return authentication success before power-on reset.
 *
 * ─────────────────────────────────────────────────────────────
 * IX. Clock Management
 * ─────────────────────────────────────────────────────────────
 *
 * 24. Any clock update or acquisition must first pass the monotonicity check.
 *
 * 25. After the check passes, the recorded maximum time must be updated.
 *
 * ─────────────────────────────────────────────────────────────
 * X. Device Driver Side and Development Constraints
 * ─────────────────────────────────────────────────────────────
 *
 * 26. Before enabling output, verify that the transmit frequency complies
 *     with national standards:
 *
 * 26.1 Allowed frequency ranges and corresponding limits:
 *   - 470-510 MHz: maximum transmit power 50 mW (e.r.p), occupied bandwidth
 *     no more than 200 kHz. This band is designated for civil radio metering
 *     instruments; single-frequency point use only, networking applications
 *     are not permitted. It may be used only when the transmitter's single
 *     operating duration does not exceed 5 seconds during data transmission.
 *   - 779-787 MHz: maximum transmit power 10 mW (e.r.p), duty cycle of the
 *     transmitted signal no more than 1%.
 *   - 314-316 MHz, 430-432 MHz, 433.05-434.79 MHz: maximum transmit power
 *     10 mW (e.r.p), occupied bandwidth no more than 400 kHz. Applicable to
 *     general radio remote control equipment; must not be used for wireless
 *     control of toys, models, etc.
 *   - 470-566 MHz, 614-698 MHz: maximum transmit power 5 mW (e.r.p), occupied
 *     bandwidth no more than 1 MHz, applicable to general radio remote control
 *     equipment.
 *   - Other micro-power frequency bands conforming to MIIT Announcement No. 52
 *     of 2019 shall be subject to the requirements of their respective categories.
 *
 * 26.2 Transmit power must not exceed the limit for the corresponding frequency
 *      band; additional RF power amplifiers are prohibited.
 *      According to Article 4 of the Announcement: "The use scenario shall not
 *      be changed without authorization, the transmit frequency range shall not
 *      be expanded, the transmit power shall not be increased (including
 *      additional RF power amplifiers), and the transmit antenna shall not be
 *      changed without authorization."
 *
 * 26.3 Occupied bandwidth must not exceed the limit for the corresponding
 *      frequency band.
 *      This constraint also falls under Article 4 of the Announcement:
 *      "Adjustment or control devices shall be limited to adjustment or control
 *      within the technical specifications specified in the technical requirements."
 *
 * 26.4 Spurious emission limits: In the frequency bands 48.5-72.5 MHz,
 *      76-108 MHz, 167-223 MHz, 470-566 MHz, and 606-798 MHz, radiated
 *      spurious emissions shall not exceed -54 dBm.
 *
 * 26.5 Transmit signal duty cycle: In the 779-787 MHz band, the duty cycle of
 *      the transmitted signal shall not exceed 1%.
 *
 * 26.6 Transmit duration and interval (applicable to general radio remote
 *      control equipment, i.e., scenarios using 314-316 MHz, 430-432 MHz,
 *      433.05-434.79 MHz, or 470-566 MHz, 614-698 MHz bands):
 *      Automatic control devices shall be provided to ensure:
 *        - For periodically operating equipment: the radio wave transmission
 *          duration shall not exceed 1 second, and the interval between two
 *          transmissions shall not be less than 60 minutes;
 *        - For non-periodically operating equipment: each radio wave transmission
 *          duration shall not exceed 5 seconds, and the interval between two
 *          transmissions shall not be less than 60 minutes.
 *
 * 26.7 If the frequency used is the same as that of a local sound or television
 *      broadcasting station, it shall not be used in that locality; if interference
 *      is caused to local sound or television broadcasting reception, use shall
 *      be stopped immediately, and it may be resumed only after the interference
 *      is eliminated or the frequency is adjusted to one without interference.
 *
 * 26.8 The use of micro-power equipment shall not cause harmful interference to
 *      other legitimate radio stations (stations), nor shall it claim protection
 *      from harmful interference. If harmful interference is caused to other
 *      legitimate radio stations (stations), use shall be stopped immediately,
 *      and it may be continued only after measures are taken to eliminate the
 *      harmful interference.
 *
 * 26.9 The use of various model remote controllers is prohibited within an area
 *      centered on the airport runway center point with a radius of 5000 meters.
 *      Without approval, model radio remote control equipment shall not be used
 *      in aviation and military control zones.

 *
 * @param auth decoded AUTH frame (host time, expiry, signature bytes)
 * @return the verdict the output half has to act on
 */
AuthResult resonancerCheckLicence(const LumaFlow::Auth& auth);
// AI: end
