/*
 * resonancer_uikit.cpp - see resonancer_uikit.h.
 */
// AI: below section was generated by an AI
#include "resonancer_uikit.h"
#include "resonancer_uikit_js.h"

namespace ResonancerUi {

// --- enum names used by the JavaScript engine ------------------------------

static const char* const OP_NAMES[] = {
  "eq", "ne", "in", "notin", "true", "false", "ge", "gt", "le", "lt", "exists", "missing", "active"
};

static const char* const PROP_NAMES[] = { "visible", "editable", "required" };

static const char* const WIDGET_NAMES[] = { "auto", "pin", "dropdown", "fold", "status", "grid" };

// --- palette and registry --------------------------------------------------

static const char* const OEM_COLORS[] = {
  "#d89090",  // 0  Red
  "#8ad06a",  // 1  Green
  "#7aa8e0",  // 2  Blue
  "#e0a0c0",  // 3  Pink
  "#e8e8e8",  // 4  White
  "#e8b070",  // 5  Orange
  "#88c8e8",  // 6  Light Blue
  "#8ad06a",  // 7  Light Green
  "#a888e0",  // 8  Purple
  "#d8c060",  // 9  Amber
  "#e8a8b8",  // 10 Light Pink
  "#60b8d8",  // 11 Aqua
  "#d8cc70",  // 12 Light Yellow
  "#a8d070",  // 13 Grass Green
  "#d89090",  // 14 Light Red
  "#bcbcbc",  // 15 Loop
  "#cfcfcf",  // 16 End control
};

static OemKey registeredKeys[RESONANCER_OEM_MAX_KEYS];
static uint8_t registeredCount = 0;

const char* const* oemColors() { return OEM_COLORS; }
uint8_t oemColorCount() { return sizeof(OEM_COLORS) / sizeof(OEM_COLORS[0]); }

bool registerOEMKey(const OemKey& key) {
  if (key.key == nullptr || key.label == nullptr) return false;
  if (oemKeyIndex(key.key) >= 0) return false;             // duplicate
  if (registeredCount >= RESONANCER_OEM_MAX_KEYS) {
    DEBUG_PRINTLN(F("Resonancer: OEM key table full"));
    return false;
  }
  registeredKeys[registeredCount] = key;
  registeredCount++;
  return true;
}

uint8_t oemKeyCount() { return registeredCount; }

const OemKey* oemKeyAt(uint8_t index) {
  if (index >= registeredCount) return nullptr;
  return &registeredKeys[index];
}

int8_t oemKeyIndex(const char* key) {
  if (key == nullptr) return -1;
  for (uint8_t i = 0; i < registeredCount; i++) {
    if (strcmp(registeredKeys[i].key, key) == 0) return (int8_t)i;
  }
  return -1;
}

// --- page builder ----------------------------------------------------------

static JsonObject addComponent(JsonObject page, const char* id, const char* kind, Widget widget, bool array) {
  JsonArray list = page["components"].is<JsonArray>() ? page["components"].as<JsonArray>()
                                                      : page.createNestedArray("components");
  JsonObject comp = list.createNestedObject();
  comp["id"] = id;
  comp["kind"] = kind;
  if (widget != W_AUTO) comp["widget"] = WIDGET_NAMES[widget];
  if (array) comp["array"] = true;
  return comp;
}

JsonObject component(JsonObject page, const char* id, const char* kind, Widget widget) {
  return addComponent(page, id, kind, widget, false);
}

JsonObject arrayComponent(JsonObject page, const char* id, const char* kind, Widget widget) {
  return addComponent(page, id, kind, widget, true);
}

JsonObject rule(JsonObject page, const char* whenKey, Op op, const char* value,
                const char* target, Prop prop, bool on, const char* reason) {
  JsonArray list = page["rules"].is<JsonArray>() ? page["rules"].as<JsonArray>()
                                                 : page.createNestedArray("rules");
  JsonObject r = list.createNestedObject();
  JsonObject when = r.createNestedObject("when");
  when["key"] = whenKey;
  when["op"] = OP_NAMES[op];
  if (value != nullptr) when["value"] = value;
  r["target"] = target;
  r["prop"] = PROP_NAMES[prop];
  r["value"] = on;
  if (reason != nullptr) r["reason"] = reason;
  return r;
}

void hint(JsonObject page, const char* id, int8_t index, char level, const char* text) {
  JsonArray list = page["hints"].is<JsonArray>() ? page["hints"].as<JsonArray>()
                                                 : page.createNestedArray("hints");
  JsonObject h = list.createNestedObject();
  h["id"] = id;
  h["index"] = index;
  // Same ownership rule as in option(): a stack buffer has to be handed over as a char*
  // so the document copies it instead of storing a pointer that is gone right after.
  char lv[2] = { level, '\0' };
  h["level"] = const_cast<char*>(lv);
  h["text"] = text;
}

void checkRange(JsonObject page, const char* target, float min, float max, const char* message) {
  JsonArray list = page["checks"].is<JsonArray>() ? page["checks"].as<JsonArray>()
                                                  : page.createNestedArray("checks");
  JsonObject c = list.createNestedObject();
  c["target"] = target;
  c["kind"] = "range";
  c["min"] = min;
  c["max"] = max;
  c["message"] = message;
}

void checkValidator(JsonObject page, const char* target, const char* name, const char* message) {
  JsonArray list = page["checks"].is<JsonArray>() ? page["checks"].as<JsonArray>()
                                                  : page.createNestedArray("checks");
  JsonObject c = list.createNestedObject();
  c["target"] = target;
  c["kind"] = "validator";
  c["name"] = name;
  c["message"] = message;
}

void value(JsonObject page, const char* key, const char* text) {
  JsonObject vals = page["values"].is<JsonObject>() ? page["values"].as<JsonObject>()
                                                    : page.createNestedObject("values");
  vals[key] = text;
}

JsonObject option(JsonObject comp, const char* label, int16_t value, bool disabled) {
  JsonArray list = comp["options"].is<JsonArray>() ? comp["options"].as<JsonArray>()
                                                   : comp.createNestedArray("options");
  JsonObject o = list.createNestedObject();
  // ArduinoJson v6 stores a const char* by address (it assumes a string literal) and only
  // copies a char*. Option labels are routinely built in a local buffer, so the pointer is
  // passed through a mutable one on purpose: the document then owns its own copy instead
  // of holding a pointer into a buffer that is gone by the time the page is serialised.
  o["label"] = const_cast<char*>(label);
  o["value"] = value;
  if (disabled) o["disabled"] = true;
  return o;
}

void pollField(JsonObject comp, const char* label, const char* path, const char* valueKey) {
  JsonObject poll = comp["poll"].is<JsonObject>() ? comp["poll"].as<JsonObject>()
                                                  : comp.createNestedObject("poll");
  if (!poll.containsKey("url")) poll["url"] = "/json/info";
  if (!poll.containsKey("every")) poll["every"] = 1000;
  JsonArray fields = poll["fields"].is<JsonArray>() ? poll["fields"].as<JsonArray>()
                                                    : poll.createNestedArray("fields");
  JsonObject f = fields.createNestedObject();
  f["label"] = label;
  f["path"] = path;
  if (valueKey != nullptr) f["value"] = valueKey;
}

JsonObject oemGrid(JsonObject page, const char* id, const char* label, const char* payloadKey) {
  JsonObject comp = component(page, id, "action", W_GRID);
  if (label != nullptr) comp["label"] = label;

  JsonArray colors = comp.createNestedArray("colors");
  const char* const* palette = oemColors();
  for (uint8_t i = 0; i < oemColorCount(); i++) colors.add(palette[i]);

  // The payload template is copied per button by the engine, '$key' is the key.
  JsonObject payload = comp.createNestedObject("payload");
  JsonObject inner = payload.createNestedObject(FPSTR("Resonancer"));
  inner[payloadKey] = "$key";

  JsonArray buttons = comp.createNestedArray("buttons");
  for (uint8_t i = 0; i < oemKeyCount(); i++) {
    const OemKey* k = oemKeyAt(i);
    JsonObject b = buttons.createNestedObject();
    b["key"] = k->key;
    b["label"] = k->label;
    b["color"] = (k->color < oemColorCount()) ? k->color : (uint8_t)(i % oemColorCount());
    if (k->span > 1) b["span"] = k->span;
  }
  return comp;
}

void foldLabels(JsonObject comp, const char* more, const char* less) {
  comp["label"] = more;
  comp["labelOpen"] = less;
}

// --- emit ------------------------------------------------------------------

void emit(Print& out, PageBuilder build, void* ctx) {
  DynamicJsonDocument doc(UKIT_PAGE_JSON_SIZE);
  JsonObject page = doc.to<JsonObject>();
  if (build != nullptr) build(page, ctx);
  if (doc.overflowed()) {
    // A truncated description would be invalid JSON, which the guard below turns into a
    // console error instead of a broken settings page. Report it so the size can be
    // raised before that happens.
    DEBUG_PRINTLN(F("Resonancer: settings page description too large"));
  }

  // The library defines the namespace on the page; the page description follows. The
  // whole thing runs inside WLED's GetV(), so a failure must not abort the rest of the
  // settings script: the call is guarded and reports to the console.
  out.print(FPSTR(RESONANCER_UKIT_JS));
  if (doc.overflowed()) {
    // Say it out loud: the page would otherwise look half decorated for no reason.
    out.print(F("\nif(window.console&&console.error)console.error('Resonancer: page description truncated');"));
  }
  out.print(F("\ntry{UKIT.page("));
  serializeJson(doc.as<JsonObjectConst>(), out);
  out.print(F(");}catch(e){if(window.console&&console.error)console.error('Resonancer UI:',e);}\n"));
}

} // namespace ResonancerUi
// AI: end
