#include "wled.h"

#if RESONANCER_ENABLE_BLE

#include "resonancer_ble.h"
#include <NimBLEDevice.h>

// AI: below section was generated by an AI
/*
 * BLE peripheral input for the Resonancer usermod.
 *
 * The LumaFlow host connects to this device directly as a GATT client and writes
 * raw protocol frames to one characteristic. The UUIDs and the advertised name
 * prefix are taken from the host implementation and must not be changed:
 *
 *   service        7e570001-3e74-4b1e-b6f4-1a91f7080001
 *   characteristic 7e570002-3e74-4b1e-b6f4-1a91f7080002  (write, no response)
 *   name           "LumaFlow" followed by the configured suffix
 *
 * A write may carry several frames or only part of one, so the bytes are handed to
 * a byte stream parser rather than being treated as one frame.
 */

namespace {

constexpr char BLE_DEVICE_NAME_PREFIX[] = "LumaFlow";

// Preferred ATT MTU. The host splits a write into (MTU - 3) byte chunks, so a
// larger MTU lets it send a whole frame in one write. 247 fits a 251 byte link
// layer packet including the 4 byte L2CAP header.
constexpr uint16_t BLE_PREFERRED_MTU = 247;

NimBLEServer*         bleServer = nullptr;
NimBLECharacteristic* bleCharacteristic = nullptr;
volatile bool         bleStarted = false;
volatile bool         bleAdvertising = false;

// ESP-IDF only enables the Bluetooth controller while WiFi modem sleep is on, and
// WLED turns modem sleep off by default. The usermod switches it on while BLE is in
// use and restores WLED's setting when BLE stops.
bool modemSleepForced = false;


/** Byte stream parser for BLE writes: a write is a chunk, not necessarily a frame. */
class BleWriteCallbacks : public NimBLECharacteristicCallbacks {
  public:
    void onWrite(NimBLECharacteristic* characteristic) override {
      if (characteristic == nullptr) return;
      NimBLEAttValue value = characteristic->getValue();
      if (value.size() == 0) return;
      // No framing here: the shared parser keeps the partial frame across writes.
      ResonancerBle::deliverBytes(value.data(), value.size());
    }
};

BleWriteCallbacks bleWriteCallbacks;

/**
 * Release a partially or fully started stack.
 *
 * Every failure path in start() runs through here: the controller occupies RAM
 * and the radio, and the forced WiFi modem sleep has to be handed back, otherwise
 * a failed attempt leaves the device in a state only a reboot clears.
 */
void teardownStack() {
  if (NimBLEDevice::getInitialized()) NimBLEDevice::deinit(true);
  bleServer = nullptr;
  bleCharacteristic = nullptr;
  bleStarted = false;
  bleAdvertising = false;
  if (modemSleepForced) {
    WiFi.setSleep(!noWifiSleep);
    modemSleepForced = false;
  }
}

/** Track connections so the usermod can report and react to them. */
class BleServerCallbacks : public NimBLEServerCallbacks {
  public:
    void onConnect(NimBLEServer* server) override {
      DEBUG_PRINTLN(F("Resonancer: BLE host connected"));
    }
    void onDisconnect(NimBLEServer* server) override {
      DEBUG_PRINTLN(F("Resonancer: BLE host disconnected"));
      // Keep the device discoverable so the host can reconnect.
      if (bleAdvertising) NimBLEDevice::getAdvertising()->start();
    }
};

BleServerCallbacks bleServerCallbacks;

} // namespace

namespace ResonancerBle {

bool isStarted() { return bleStarted; }

bool isModemSleepForced() { return modemSleepForced; }

void keepModemSleepAlive() {
  // WLED re-applies "disable WiFi sleep" on every connection attempt, which
  // would break the coexistence requirement again, so it is re-asserted while
  // the BLE transport is in use.
  if (bleStarted && !WiFi.getSleep()) WiFi.setSleep(true);
}

bool start(const char* suffix) {
  if (bleStarted) return true;

  // Advertised name is the fixed prefix plus the user suffix, e.g. "LumaFlow-66CCFF".
  char name[32];
  const char* sfx = (suffix != nullptr) ? suffix : "";
  // a suffix that already starts with the prefix must not be doubled
  if (strncmp(sfx, BLE_DEVICE_NAME_PREFIX, strlen(BLE_DEVICE_NAME_PREFIX)) == 0) sfx = "";
  snprintf(name, sizeof(name), "%s%s", BLE_DEVICE_NAME_PREFIX, sfx);

  // Must happen before the controller is enabled, see modemSleepForced above.
  modemSleepForced = !WiFi.getSleep();
  if (modemSleepForced) WiFi.setSleep(true);

  NimBLEDevice::init(name);
  NimBLEDevice::setMTU(BLE_PREFERRED_MTU);
  bleServer = NimBLEDevice::createServer();
  if (bleServer == nullptr) {
    DEBUG_PRINTLN(F("Resonancer: BLE server creation failed"));
    teardownStack();
    return false;
  }
  // The server deletes its callbacks by default, but this one is static, so
  // ownership is declined.
  bleServer->setCallbacks(&bleServerCallbacks, false);

  NimBLEService* service = bleServer->createService(RESONANCER_BLE_SERVICE_UUID);
  if (service == nullptr) {
    DEBUG_PRINTLN(F("Resonancer: BLE service creation failed"));
    teardownStack();
    return false;
  }

  bleCharacteristic = service->createCharacteristic(
      RESONANCER_BLE_CHARACTERISTIC_UUID,
      NIMBLE_PROPERTY::WRITE | NIMBLE_PROPERTY::WRITE_NR);
  if (bleCharacteristic == nullptr) {
    DEBUG_PRINTLN(F("Resonancer: BLE characteristic creation failed"));
    teardownStack();
    return false;
  }
  bleCharacteristic->setCallbacks(&bleWriteCallbacks);

  service->start();
  NimBLEAdvertising* advertising = NimBLEDevice::getAdvertising();
  if (advertising != nullptr) {
    advertising->addServiceUUID(RESONANCER_BLE_SERVICE_UUID);
    advertising->setName(name);
    advertising->start();
    bleAdvertising = true;
  }

  bleStarted = true;
  DEBUG_PRINTF_P(PSTR("Resonancer: BLE peripheral \"%s\" started\n"), name);
  return true;
}

void setAdvertising(bool on) {
  if (!bleStarted) return;
  NimBLEAdvertising* advertising = NimBLEDevice::getAdvertising();
  if (advertising == nullptr) return;
  // Never stop advertising while a host is connected: the connection is what
  // matters and the host is already talking to us.
  if (on && !bleAdvertising) {
    advertising->start();
    bleAdvertising = true;
  } else if (!on && bleAdvertising && !isConnected()) {
    advertising->stop();
    bleAdvertising = false;
  }
}

bool isConnected() {
  return (bleServer != nullptr) && (bleServer->getConnectedCount() > 0);
}

void stop() {
  if (!bleStarted) return;
  NimBLEAdvertising* advertising = NimBLEDevice::getAdvertising();
  if (advertising != nullptr) advertising->stop();
  bleAdvertising = false;

  // deinit() is not reliable while a link is up, so active links are closed first.
  // This runs once per transport change, so the short wait is acceptable.
  if (bleServer != nullptr && bleServer->getConnectedCount() > 0) {
    std::vector<uint16_t> peers = bleServer->getPeerDevices();
    for (uint16_t handle : peers) bleServer->disconnect(handle);
    for (uint8_t i = 0; i < 25 && bleServer->getConnectedCount() > 0; i++) delay(10);
  }

  // Hands the radio, the RAM and the WiFi power setting back to WLED.
  teardownStack();
  DEBUG_PRINTLN(F("Resonancer: BLE peripheral stopped"));
}

} // namespace ResonancerBle

#endif // RESONANCER_ENABLE_BLE
// AI: end
