#pragma once

#include "wled.h"

// QueueHandle_t is used by the input staging queue below.
#ifdef ARDUINO_ARCH_ESP32
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#endif

#include "lumaflow_protocol.h"
#include "resonancer_rfdevice.h"
#include "resonancer_ble.h"

/*
 * Resonancer usermod - LumaFlow input, WLED output.
 *
 * The usermod is split into two independent halves:
 *
 *   INPUT   LumaFlow frames (serial, UDP, BLE) carry 10 channels
 *           (CH0..CH9). Every WLED segment may subscribe to one channel. A
 *           subscribed segment receives the channel colour in its primary
 *           colour slot and, when the channel asks for it, a blinking WLED
 *           effect that provides the timing. Segments that are not subscribed
 *           are never touched.
 *
 *   OUTPUT  Every output channel reads the colour of one upstream segment
 *           (mirror image of the input mapping) and hands it to a local output
 *           device. The output half is only compiled in when
 *           RESONANCER_ENABLE_RF is set; its implementation lives outside this
 *           repository.
 *
 * See readme.md for the build switches.
 */

// AI: below section was generated by an AI
class ResonancerUsermod : public Usermod {
  public:
    // Number of LumaFlow channels, fixed by the protocol.
    static constexpr uint8_t CHANNEL_COUNT = LumaFlow::CHANNEL_COUNT;

    // Communication transport for incoming LumaFlow frames.
    enum CommMode : uint8_t {
      COMM_SERIAL = 0,
      COMM_UDP = 1,
      COMM_BLE = 2,
    };

    // Bluetooth and WiFi share the single 2.4 GHz radio of the ESP32. BLE keeps a
    // connection alive with periodic radio activity, which competes with the web
    // interface and the LED pipeline, so the conflict is resolved by policy
    // instead of being left to the coexistence scheduler.
    enum BleCoexistMode : uint8_t {
      BLE_COEX_ALLOW_BOTH = 0,   // BLE always discoverable, WiFi serves the web UI
      BLE_COEX_WIFI_FIRST = 1,   // advertising pauses while the web UI is in use
      BLE_COEX_BLE_FIRST  = 2,   // web sockets pause while a BLE stream is running
    };

    // Snapshot of the segment settings changed while a channel owns the segment.
    // The geometry is part of the snapshot: a segment has no stable identity, so
    // the pixel range is what tells "the same segment" from "another segment that
    // now occupies this slot" (see restoreSegment()).
    struct SegmentBackup {
      bool valid = false;
      uint16_t start = 0;
      uint16_t stop = 0;
      uint8_t mode = FX_MODE_STATIC;
      uint8_t speed = 128;
      uint8_t intensity = 128;
      uint32_t color0 = 0;
      uint32_t color1 = 0;
    };

  private:
    bool enabled = false;           // input side enable (master switch of the usermod)
    bool initDone = false;
    unsigned long lastFrameMs = 0;  // millis() of the last accepted LumaFlow frame

    // Input configuration
    uint8_t commMode = COMM_SERIAL;
    uint16_t udpPort = 32712;
    char bleSuffix[17] = {0};
    // Persisted even when BLE is compiled out: the configuration round trip must
    // not depend on the transport being present.
    uint8_t bleCoexist = BLE_COEX_WIFI_FIRST;

    // Channel state decoded from the last accepted frame
    LumaFlow::Channel channels[CHANNEL_COUNT];

    // Segment <-> channel subscription, indexed by WLED segment: a segment binds
    // one LumaFlow channel (input direction) and several segments may share the
    // same channel. SEGMENT_UNMAPPED keeps the segment untouched.
    static constexpr uint8_t SEGMENT_UNMAPPED = 0xFF;
    uint8_t segChannel[MAX_NUM_SEGMENTS];
    SegmentBackup backup[MAX_NUM_SEGMENTS];
    uint8_t appliedFunction[MAX_NUM_SEGMENTS];   // 0xFF = nothing written yet
    uint32_t appliedColor[MAX_NUM_SEGMENTS];
    bool inStream = false;                    // a stream is currently being applied

    // Output configuration
    bool outputEnabled = false;       // user intent (persisted), honoured when a licence arrives
    bool outputArmed = false;         // runtime: an explicit action or an AUTH frame happened in this boot
    bool rfConfigured = false;        // InitConfig() accepted the configuration
    bool rfInitialized = false;       // DeviceInit() succeeded
    bool rfConfigDirty = true;        // output config changed, re-apply in loop()
    unsigned long rfRetryMs = 0;      // earliest next attempt after a failed setup
    // Transition time the strip had before the usermod set it to 0; -1 = not saved.
    int16_t savedTransition = -1;
    // output channel -> source segment, 0xFF = unmapped
    uint8_t outChannelSegment[CHANNEL_COUNT];
    // Output device pin assignment. Always present so the settings page and the
    // device configuration stay uniform; a build without an output half simply
    // never allocates them.
    int8_t rfSck = RESONANCER_DEFAULT_SCK;
    int8_t rfMiso = RESONANCER_DEFAULT_MISO;
    int8_t rfMosi = RESONANCER_DEFAULT_MOSI;
    int8_t rfSs = RESONANCER_DEFAULT_SS;
    int8_t rfGd0 = RESONANCER_DEFAULT_GD0;
    int8_t rfGd2 = RESONANCER_DEFAULT_GD2;
    RFRuntimeConfig rfConfig;
    RFDevice* rfDevice = nullptr;
    AuthResult authResult = AuthResult::NotAuthenticated;
    unsigned long lastOutputMs = 0;   // timestamp of the last submitted packet
    unsigned long lastSyncMs = 0;     // timestamp of the last sync notification
    unsigned long stripTriggerMs = 0; // last forced frame

    // Preset command plumbing. The request is written by the HTTP task and consumed by
    // loop(); oemResult keeps the outcome for the info page.
    // OEM_QUEUED makes the request visible on the info page as soon as it arrived: it
    // tells "the request never reached the usermod" from "the usermod refused it".
    enum OemResult : uint8_t { OEM_NONE, OEM_QUEUED, OEM_SENT, OEM_OFF, OEM_UNLICENSED, OEM_NOT_RUNNING, OEM_UNKNOWN };
    int8_t pendingOemSlot = -1;        // -1 = nothing queued
    uint8_t oemResult = OEM_NONE;      // outcome of the last command
    uint8_t oemResultSlot = 0;         // slot the outcome belongs to
    unsigned long oemResultMs = 0;
    unsigned long presetGuardUntilMs = 0;   // stream pauses until a preset is on the air
    // An executed preset pauses the input: the device is under preset control, so the bridge
    // stops forwarding colours - the next colour packet would put it straight back under
    // stream control, which is what a preset is meant to override. Cleared by an explicit
    // action: re-arming the output, a saved mapping change, or {"Resonancer":{"stream":true}}.
    bool outputHeld = false;

    // Wall clock used for the output expiry check.
    // Filled from NTP when available, otherwise from the AUTH frame host time.
    bool clockSynced = false;
    uint32_t wallClock = 0;         // unix seconds
    unsigned long wallClockMs = 0;  // millis() when wallClock was taken

    // Counters exposed on the info page
    uint32_t framesReceived = 0;
    uint32_t framesRejected = 0;
    uint32_t framesDuplicate = 0;

    // The host repeats each frame to survive packet loss (UDP 2x by default, AUTH
    // 3x), so an identical frame arriving right after the previous one is treated
    // as a duplicate and skipped instead of being applied again.
    uint8_t lastStream[LumaFlow::STREAM_PAYLOAD_LEN];
    bool    lastStreamValid = false;
    uint32_t packetsSent = 0;

#if RESONANCER_ENABLE_BLE
    // BLE peripheral is started from loop(), never from setup(): WLED calls
    // usermod setup() before the network is up, and the BLE stack must not take
    // the radio at the same moment as WiFi.
    bool bleStartPending = true;
    bool bleActive = false;
    uint32_t bleRetryMs = 0;         // earliest next start attempt after a failure
    bool webQuiet = true;            // web interface idle, BLE may advertise
#endif

    // LumaFlow UDP transport (own socket, see readme)
    bool udpActive = false;
    uint16_t udpBoundPort = 0;       // port the open socket is bound to
    AsyncUDP* resonancerUdp = nullptr;
    // Input staging. The callback transports (UDP in the lwIP task, BLE in the
    // NimBLE host task) and the JSON route (HTTP task) run in other tasks than
    // loop(), so they only hand their bytes over through this queue; the parser
    // itself always runs in loop(), which keeps the channel state single-writer.
    struct InputChunk {
      uint16_t length;
      uint8_t data[LumaFlow::MAX_FRAME_LEN];
    };
    QueueHandle_t inputQueue = nullptr;
    // Byte stream accumulator for transports that deliver arbitrary chunks.
    uint8_t accBuffer[LumaFlow::MAX_FRAME_LEN];
    uint16_t accLength = 0;

    // Strings used more than once
    static const char _name[];
    static const char _enabled[];
    static const char _comm[];
    static const char _udpPort[];
    static const char _bleSuffix[];
    static const char _segChannel[];
    static const char _bleCoexist[];
    static const char _outputEnabled[];
    static const char _outSeg[];
    static const char _rfFreq[];
    static const char _rfPins[];
    static const char _oem[];

    // --- input helpers -----------------------------------------------------
    void updateClock();
    uint32_t currentEpoch() const;
    bool licenseExpired() const;
    void feedByte(uint8_t byte);       // parse one byte of the LumaFlow frame stream
    void onLumaFlowBytes(const uint8_t* data, size_t len);   // feed a chunk to feedByte()
    void startUdp();
    void stopUdp();
    void drainInput();       // parse the staged chunk in loop()

    // --- segment helpers ---------------------------------------------------
    bool segmentUsable(uint8_t index) const;
    void writeSegmentColor(uint8_t channel, uint8_t segIndex);
    void releaseSegment(uint8_t segIndex);
    void releaseAllSegments();
    bool anySegmentDriven() const;     // at least one segment is held by the usermod
    void restoreSegment(uint8_t segIndex);

    // --- output helpers ----------------------------------------------------
    bool outputLicensed() const;       // licence allows operation (auth + expiry + restriction)
    const char* statusText() const;
    bool anyInputSubscribed() const;   // at least one segment follows a LumaFlow channel
    bool anyOutputMapped() const;      // at least one output channel is mapped to a segment
    void refreshStrip();               // force the next frame (see RESONANCER_STRIP_TRIGGER_MS)
    const char* resetReasonText() const;
    void applyOutputConfig();          // allocate pins and configure the device
    void releaseOutputConfig();        // un-initialise and free pins
    void updateOutput();               // submit one packet when due

  public:
    ResonancerUsermod();

    // Handle one already decoded binary frame. Called by the shared parser (which
    // runs in loop()) and by the serial sink registered in setup().
    // Returns true when the frame was accepted.
    bool onLumaFlowFrame(uint8_t cmd, const uint8_t* payload, uint8_t payloadLen);

    // Hand raw bytes from any task to the parser in loop(). Returns false when the
    // staging slot could not be filled (no memory, or the chunk was empty).
    bool stageBytes(const uint8_t* data, size_t len);

    // Called by the core serial parser (registered in setup()). Only accepts
    // frames while the serial transport is selected.
    bool onSerialFrame(uint8_t cmd, const uint8_t* payload, uint8_t payloadLen);

    // Called by an input transport that forwards the payload as hex text.
    // Used by the JSON route, case insensitive.
    bool onLumaFlowFrameHex(uint8_t cmd, const char* hexData);

    // Preset commands: queued by the JSON route, served in loop(). A preset is only
    // sent while the output is running, so the outcome is reported back to the user.
    void requestOem(int8_t slot);
    void servicePendingOem();
    const char* oemResultText() const;

    // Build the data driven settings page description (see resonancer_uikit.h).
    void buildUikitPage(JsonObject& page);

    void setup() override;
    void loop() override;

    void addToJsonState(JsonObject& root) override;
    void readFromJsonState(JsonObject& root) override;
    void addToJsonInfo(JsonObject& root) override;
    void addToConfig(JsonObject& root) override;
    bool readFromConfig(JsonObject& root) override;
    void appendConfigData(Print& settingsScript) override;

    uint16_t getId() override { return USERMOD_ID_RESONANCER; }
};
// AI: end
