#include "usermod_resonancer.h"
#include "resonancer_uikit.h"

#ifdef ARDUINO_ARCH_ESP32
  #include <esp_system.h>      // esp_reset_reason(), reported on the info page
#endif

#include <AsyncUDP.h>

// The Resonancer usermod instance. REGISTER_USERMOD() places its pointer in a
// linker section that WLED scans at boot, so no manual registration is required.
static ResonancerUsermod resonancer_usermod;
REGISTER_USERMOD(resonancer_usermod);

#if RESONANCER_ENABLE_BLE
// Called by the BLE transport for every byte chunk it receives. The NimBLE
// callback runs in the host task, so the bytes are only staged here.
namespace ResonancerBle {
  void deliverBytes(const uint8_t* data, size_t len) {
    resonancer_usermod.stageBytes(data, len);
  }
}
#endif

// AI: below section was generated by an AI

// Strings used more than once, kept in PROGMEM to save RAM.
const char ResonancerUsermod::_name[]          PROGMEM = "Resonancer";
const char ResonancerUsermod::_enabled[]       PROGMEM = "enabled";
const char ResonancerUsermod::_comm[]          PROGMEM = "comm";
const char ResonancerUsermod::_udpPort[]       PROGMEM = "udpPort";
const char ResonancerUsermod::_bleSuffix[]     PROGMEM = "bleSuffix";
const char ResonancerUsermod::_segChannel[]    PROGMEM = "segChannel";
const char ResonancerUsermod::_bleCoexist[]    PROGMEM = "bleCoexist";
const char ResonancerUsermod::_outputEnabled[] PROGMEM = "outputEnabled";
const char ResonancerUsermod::_outSeg[]        PROGMEM = "outSeg";
const char ResonancerUsermod::_rfFreq[]        PROGMEM = "rfFreq";
const char ResonancerUsermod::_rfPins[]        PROGMEM = "rfPins";
const char ResonancerUsermod::_oem[]           PROGMEM = "oem";


// Server used when the firmware falls back to NTP for the wall clock.
static const char RESONANCER_NTP_SERVER[] PROGMEM = "ntp.ntsc.ac.cn";

// Output licence expiry: 2027-01-01 00:00:00 Beijing time (UTC+8) == 2026-12-31 16:00:00 UTC.
static constexpr uint32_t RESONANCER_OUTPUT_EXPIRE_UTC = 1798732800UL;

// A stream is considered lost when no frame arrived for this long. Only the
// streaming state ends: the segments keep the colour and the effect of the last
// frame until the usermod is switched off or the subscription changes.
static constexpr uint16_t RESONANCER_STREAM_TIMEOUT_MS = 2000;

// Wall clock re-read interval.
static constexpr uint32_t RESONANCER_CLOCK_REFRESH_MS = 10000;

// Self imposed floor between two forced frames. The host may stream faster than this;
// below it the extra frames would only cost CPU and mains noise.
static constexpr uint16_t RESONANCER_STRIP_TRIGGER_MS = 10;

// Shortest interval between two sync notifications. WLED's own notify path is cheap, but a
// burst from the host must not turn into a burst on the network.
static constexpr uint16_t RESONANCER_SYNC_INTERVAL_MS = 50;

// A preset command pauses the stream for this long. The output device queues a single
// packet, so the next stream packet would otherwise overwrite the preset before it is
// on the air. The guard is the fallback; a device that can report a pending preset
// (RFDevice::isOemPending()) is trusted instead, up to this hard limit.
static constexpr uint16_t RESONANCER_PRESET_GUARD_MS = 200;
static constexpr uint16_t RESONANCER_PRESET_MAX_WAIT_MS = 2000;

// Staging slots between a callback transport and loop(). Deep enough to absorb a
// burst (a datagram holding several frames, a frame split over two datagrams)
// without blocking the callback, shallow enough to stay small.
static constexpr uint8_t RESONANCER_INPUT_QUEUE_SLOTS = 4;

// Delay before a failed BLE start is retried (the radio may still be busy with
// WiFi on the first attempt).
static constexpr uint32_t RESONANCER_BLE_RETRY_MS = 5000;

// Delay before a failed output setup is retried (a pin may still be owned by
// another bus, or the device may not answer yet).
static constexpr uint32_t RESONANCER_RF_RETRY_MS = 5000;

// Minimum spacing between two submitted output packets. The implementation keeps
// only the newest packet, so this only bounds how often the segment buffer is read.
static constexpr uint16_t RESONANCER_OUTPUT_INTERVAL_MS = 25;

// Blink frequencies requested by the LumaFlow channel functions.
static constexpr uint16_t RESONANCER_BLINK_1HZ = 1;
static constexpr uint16_t RESONANCER_BLINK_2HZ = 2;
static constexpr uint16_t RESONANCER_BLINK_4HZ = 4;

static inline bool isFrameStart(uint8_t b) {
  return (b == LumaFlow::HEAD0) || (b == LumaFlow::TAIL) || (b == 0xC0) || (b == 0xC1);
}

ResonancerUsermod::ResonancerUsermod() {
  rfConfig.rf_freq = RESONANCER_DEFAULT_RF_FREQ;
  for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) {
    outChannelSegment[ch] = 0xFF;
  }
  for (uint8_t s = 0; s < MAX_NUM_SEGMENTS; s++) {
    segChannel[s] = SEGMENT_UNMAPPED;
    appliedFunction[s] = 0xFF;
    appliedColor[s] = 0xFFFFFFFF;
  }
}

// --- segment helpers -------------------------------------------------------

/** A segment is usable when it exists and spans at least one pixel. */
bool ResonancerUsermod::segmentUsable(uint8_t index) const {
  if (index >= strip.getSegmentsNum()) return false;
  const Segment& seg = strip.getSegment(index);
  return seg.stop > seg.start;   // a segment with stop <= start is invalid
}

/** Effect used for a channel function. */
static uint8_t effectForFunction(uint8_t function) {
  return (function == LumaFlow::FUNC_SOLID) ? FX_MODE_STATIC : FX_MODE_STROBE;
}

/**
 * Convert a blink frequency to the speed value of the WLED blink() helper.
 * The helper computes cycleTime = (255 - speed) * 20 + 2 * frameTime, so the
 * speed is derived from the frame time instead of being hard coded.
 */
static uint8_t speedForFrequency(uint16_t frequencyHz) {
  if (frequencyHz == 0) return 0;
  const uint32_t periodMs = 1000UL / frequencyHz;
  const uint32_t frameTime = strip.getFrameTime();
  if (periodMs <= 2 * frameTime) return 255;          // cannot be represented
  uint32_t speed = 255 - ((periodMs - 2 * frameTime) / 20);
  return (speed > 255) ? 255 : (uint8_t)speed;
}

/**
 * Write the channel colour into the segment.
 *
 * The channel colour lives in primary colour slot 0. A steady channel switches
 * the segment to a static effect; a blinking channel uses a strobe effect,
 * because a running effect would otherwise overwrite the colour in the next
 * render pass. Segment transitions are suppressed while a segment is owned by
 * the usermod and restored on release.
 *
 * @param channel  channel index (0..CHANNEL_COUNT-1)
 * @param segIndex segment that subscribes to this channel
 */
void ResonancerUsermod::writeSegmentColor(uint8_t channel, uint8_t segIndex) {
  if (!segmentUsable(segIndex)) return;
  Segment& seg = strip.getSegment(segIndex);
  const LumaFlow::Channel& ch = channels[channel];

  // The colour is written before the mode: switching the mode starts a fresh effect run,
  // and that run must never render the previous colour (a visible single frame flicker).
  const uint32_t col = RGBW32(ch.red, ch.green, ch.blue, 0);
  if (seg.colors[0] != col) {
    // setColor() flags the state as changed and restarts a transition on every call, so
    // the colour is only pushed when it really differs. Suppress the fade while the
    // segment is owned; the previous value is kept so releaseAllSegments() can restore it.
    if (savedTransition < 0) savedTransition = (int16_t)strip.getTransition();
    strip.setTransition(0);
  }
  seg.setColor(0, col);
  seg.setColor(1, BLACK);                                 // blink "off" state

  seg.setMode(effectForFunction(ch.function));            // no-op when unchanged
  if (ch.function == LumaFlow::FUNC_SOLID) {
    // Static mode fills the segment with slot 0, but its default intensity is 0
    // which would switch palette usage off. Keep a neutral intensity.
    seg.intensity = 128;
    seg.speed = 0;
  } else {
    const uint16_t hz = (ch.function == LumaFlow::FUNC_BLINK_1HZ) ? RESONANCER_BLINK_1HZ
                      : (ch.function == LumaFlow::FUNC_BLINK_2HZ) ? RESONANCER_BLINK_2HZ
                      : RESONANCER_BLINK_4HZ;
    seg.speed = speedForFrequency(hz);
  }
}

/** Restore the segment settings saved when the channel took the segment over. */
void ResonancerUsermod::restoreSegment(uint8_t segIndex) {
  if (!backup[segIndex].valid) return;
  // A segment has no stable identity: the slot may hold a different segment now
  // (the layout changed while a stream was running). Restoring the old settings
  // into it would overwrite an unrelated segment, so the snapshot is dropped
  // without writing anything in that case.
  const bool sameSegment = segmentUsable(segIndex)
    && strip.getSegment(segIndex).start == backup[segIndex].start
    && strip.getSegment(segIndex).stop  == backup[segIndex].stop;
  if (sameSegment) {
    Segment& seg = strip.getSegment(segIndex);
    seg.setMode(backup[segIndex].mode);
    seg.speed = backup[segIndex].speed;
    seg.intensity = backup[segIndex].intensity;
    seg.colors[0] = backup[segIndex].color0;
    seg.colors[1] = backup[segIndex].color1;
    seg.markForReset();
  } else {
    DEBUG_PRINTF_P(PSTR("Resonancer: segment %u changed while owned, snapshot dropped\n"), (unsigned)segIndex);
  }
  backup[segIndex].valid = false;
}

/**
 * Hand a segment back to WLED after the usermod has driven it.
 *
 * The segment -> channel subscription itself is user configuration and is
 * deliberately kept: only the segment takeover is undone, so the next frame
 * finds the same target again.
 */
void ResonancerUsermod::releaseSegment(uint8_t segIndex) {
  restoreSegment(segIndex);
  appliedFunction[segIndex] = 0xFF;
  appliedColor[segIndex] = 0xFFFFFFFF;
}

/** Release every segment the usermod may have taken over. */
void ResonancerUsermod::releaseAllSegments() {
  // Bounded by MAX_NUM_SEGMENTS rather than by the current segment count, so a
  // segment that disappeared while it was driven is restored from the backup as
  // well (restoreSegment() checks that itself).
  for (uint8_t s = 0; s < MAX_NUM_SEGMENTS; s++) releaseSegment(s);
  // The takeover pinned the transition time to 0; give the strip its time back as
  // soon as nobody is driven any more, so the user's fades work again.
  if (savedTransition >= 0) {
    strip.setTransition((uint16_t)savedTransition);
    savedTransition = -1;
  }
}

/** True while at least one segment is still driven by the usermod. */
bool ResonancerUsermod::anySegmentDriven() const {
  for (uint8_t s = 0; s < MAX_NUM_SEGMENTS; s++) if (backup[s].valid) return true;
  return false;
}

// --- input: frame handling ------------------------------------------------

/**
 * Handle one decoded LumaFlow frame.
 *
 * Only the channel state is updated here, the segments are touched from loop()
 * so that no segment callback or state broadcast runs inside a transport
 * callback (which may execute in the network task context).
 */
bool ResonancerUsermod::onLumaFlowFrame(uint8_t cmd, const uint8_t* payload, uint8_t payloadLen) {
  if (!enabled) return false;

  if (cmd == LumaFlow::CMD_STREAM) {
    // Drop an exact repeat of the previous frame (the host sends each one two to
    // four times). Only repeats inside a live stream are dropped: once the stream
    // has stopped, the same frame starts a new one and is applied again.
    if (payload != nullptr && payloadLen == LumaFlow::STREAM_PAYLOAD_LEN && inStream &&
        lastStreamValid && memcmp(lastStream, payload, LumaFlow::STREAM_PAYLOAD_LEN) == 0) {
      framesDuplicate++;
      lastFrameMs = millis();
      return true;
    }
    if (payload != nullptr && payloadLen == LumaFlow::STREAM_PAYLOAD_LEN) {
      memcpy(lastStream, payload, LumaFlow::STREAM_PAYLOAD_LEN);
      lastStreamValid = true;
    }
    if (!LumaFlow::decodeStream(payload, payloadLen, channels)) {
      framesRejected++;
      return false;
    }
    lastFrameMs = millis();
    inStream = true;
    framesReceived++;
    return true;
  }

  if (cmd == LumaFlow::CMD_AUTH) {
    LumaFlow::Auth auth;
    if (!LumaFlow::decodeAuth(payload, payloadLen, auth)) {
      framesRejected++;
      return false;
    }
    // The host time is the fallback clock source when NTP is unavailable.
    if (!clockSynced && auth.hostTime > 1700000000UL) {
      wallClock = auth.hostTime;
      wallClockMs = millis();
      clockSynced = true;
    }

    // Licence verdict. The policy lives next to the output device implementation
    // (outside this repository), so the usermod only forwards what it gets: the
    // device is told about every change and stops operating on a bad verdict.
    const AuthResult verdict = resonancerCheckLicence(auth);
    if (verdict != authResult) {
      authResult = verdict;
      DEBUG_PRINTF_P(PSTR("Resonancer: licence verdict %u\n"), (unsigned)authResult);
    }
    if (rfDevice != nullptr) rfDevice->setAuthentication(verdict);
    if (verdict == AuthResult::Ok) outputArmed = true;   // the host is alive, honour the intent

    framesReceived++;
    return true;
  }

  framesRejected++;
  return false;
}

/**
 * Feed raw transport bytes into the shared frame parser.
 *
 * Every transport hands over arbitrary chunks (a UDP datagram, a BLE write, a
 * serial read), so framing and resynchronisation happen in one place. Only the
 * selected transport is active at a time, so the parser state is never shared
 * between two feeders.
 */
void ResonancerUsermod::onLumaFlowBytes(const uint8_t* data, size_t len) {
  if (data == nullptr) return;
  for (size_t i = 0; i < len; i++) feedByte(data[i]);
}

/**
 * Entry point for the serial transport.
 *
 * The core parser always listens on the serial port, so the selected transport is
 * checked here: frames that arrive while UDP or BLE is selected are ignored.
 */
bool ResonancerUsermod::onSerialFrame(uint8_t cmd, const uint8_t* payload, uint8_t payloadLen) {
  if (commMode != COMM_SERIAL) return false;
  return onLumaFlowFrame(cmd, payload, payloadLen);
}

/**
 * Entry point for transports that forward the payload as hex text (the JSON
 * route).
 *
 * The HTTP/WS task must not touch the parser state, so the payload is wrapped
 * into a wire frame and staged like any other transport chunk; the parser picks
 * it up in loop(). Returns false when the hex text cannot be decoded.
 */
bool ResonancerUsermod::onLumaFlowFrameHex(uint8_t cmd, const char* hexData) {
  uint8_t payload[LumaFlow::MAX_PAYLOAD_LEN];
  const size_t n = LumaFlow::hexToBytes(hexData, payload, sizeof(payload));
  if (n == 0) {
    framesRejected++;
    return false;
  }

  uint8_t frame[LumaFlow::MAX_FRAME_LEN];
  size_t len = 0;
  frame[len++] = LumaFlow::HEAD0;
  frame[len++] = LumaFlow::HEAD1;
  const uint8_t length = (uint8_t)(1 + n);         // cmd + payload
  frame[len++] = length;
  frame[len++] = cmd;
  uint8_t checksum = (uint8_t)(length + cmd);
  for (size_t i = 0; i < n; i++) {
    frame[len++] = payload[i];
    checksum = (uint8_t)(checksum + payload[i]);
  }
  frame[len++] = checksum;
  frame[len++] = LumaFlow::TAIL;
  return stageBytes(frame, len);
}

/**
 * Byte stream parser, used by transports that deliver arbitrary chunks (UDP
 * datagrams may hold several frames or only part of one).
 *
 * The buffer only ever holds at most one incomplete frame. Every accepted frame
 * is handed to onLumaFlowFrame(), structurally invalid frames are dropped by
 * resynchronising on the next possible frame start.
 */
void ResonancerUsermod::feedByte(uint8_t byte) {
  if (accLength >= sizeof(accBuffer)) accLength = 0;   // defensive, should not happen
  accBuffer[accLength++] = byte;

  uint8_t processed = 0;
  while (accLength > 0 && processed < 8) {             // bound the work per byte
    // Resynchronise: the first byte must be a frame start.
    if (accBuffer[0] != LumaFlow::HEAD0) {
      if (!isFrameStart(accBuffer[0])) { accLength = 0; return; }
      // another frame's tail -> drop it and look for the next head
      memmove(accBuffer, accBuffer + 1, --accLength);
      continue;
    }
    if (accLength < 3) return;                         // need the length byte
    // length counts cmd + payload, so a whole frame is length + head(2) +
    // length byte(1) + checksum(1) + tail(1) bytes.
    const uint16_t want = (uint16_t)accBuffer[2] + 5;
    if (want > sizeof(accBuffer)) { accLength = 0; return; }
    if (accLength < want) return;                      // wait for more bytes

    LumaFlow::Frame frame;
    if (LumaFlow::decodeFrame(accBuffer, want, frame, nullptr)) {
      onLumaFlowFrame(frame.cmd, frame.payload, frame.payloadLen);
    } else {
      framesRejected++;
    }

    memmove(accBuffer, accBuffer + want, accLength - want);
    accLength -= want;
    processed++;
  }
}

// --- input: UDP transport -------------------------------------------------

/**
 * Stage raw bytes for the parser.
 *
 * Transports that run in another task than loop() hand their bytes over here
 * (UDP in the lwIP task, BLE in the NimBLE host task, the JSON route in the HTTP
 * task), which is what keeps the parser itself single-writer: it never runs
 * outside loop(). The callbacks never block: they only copy into the queue and
 * return.
 *
 * The queue is deliberately short. When it is full the oldest chunk is dropped,
 * not the newest, because the newest colour is the one worth showing; a dropped
 * chunk costs at most one frame (the host repeats every frame, and the parser
 * resynchronises on the next frame head). A chunk longer than one maximum frame
 * is truncated - a datagram that large cannot be framed correctly anyway.
 */
bool ResonancerUsermod::stageBytes(const uint8_t* data, size_t len) {
  if (inputQueue == nullptr || data == nullptr || len == 0) return false;
  InputChunk item;
  item.length = (len > LumaFlow::MAX_FRAME_LEN) ? (uint16_t)LumaFlow::MAX_FRAME_LEN : (uint16_t)len;
  memcpy(item.data, data, item.length);
  if (xQueueSend(inputQueue, &item, 0) == pdTRUE) return true;
  InputChunk dropped;
  xQueueReceive(inputQueue, &dropped, 0);      // make room, keep the order of the rest
  return xQueueSend(inputQueue, &item, 0) == pdTRUE;
}

/**
 * Attach the LumaFlow UDP socket.
 *
 * The usermod uses its own port (default 32712), so the WLED sync (21324),
 * supplemental (65506), Hyperion (19446) and NTP (2390) sockets are untouched.
 */
void ResonancerUsermod::startUdp() {
  if (udpActive) return;

  // AsyncUDP talks to lwIP through the tcpip thread, which only exists once the
  // network stack is up. Usermod setup() runs before WiFi is started, and calling
  // listen() there faults inside the tcpip mbox, so the socket is opened on the
  // first loop() pass after the network became available.
  if (!WLED_CONNECTED) return;

  // One instance for the lifetime of the usermod: deleting it while the lwIP task
  // might still be inside its callback would be a use-after-free, so stopUdp()
  // only closes the socket.
  if (resonancerUdp == nullptr) resonancerUdp = new AsyncUDP();
  if (resonancerUdp == nullptr) {
    DEBUG_PRINTLN(F("Resonancer: no memory for the UDP socket"));
    return;
  }

  if (!resonancerUdp->listen(udpPort)) {
    DEBUG_PRINTF_P(PSTR("Resonancer: UDP port %u unavailable\n"), (unsigned)udpPort);
    udpActive = false;
    return;
  }

  resonancerUdp->onPacket([](AsyncUDPPacket packet) {
    // Network task context: stage the bytes, never parse them here.
    resonancer_usermod.stageBytes(packet.data(), packet.length());
  });

  udpActive = true;
  udpBoundPort = udpPort;
  accLength = 0;                 // a new socket starts a new byte stream
  DEBUG_PRINTF_P(PSTR("Resonancer: UDP listening on %u\n"), (unsigned)udpPort);
}

void ResonancerUsermod::stopUdp() {
  if (resonancerUdp != nullptr) resonancerUdp->close();
  udpActive = false;
  udpBoundPort = 0;
  accLength = 0;
}

/**
 * Parse the staged chunks. Called from loop().
 *
 * Everything that is queued is drained, so a burst is parsed in arrival order
 * instead of one chunk per loop pass.
 */
void ResonancerUsermod::drainInput() {
  if (inputQueue == nullptr) return;
  InputChunk item;
  uint8_t passes = RESONANCER_INPUT_QUEUE_SLOTS;
  while (passes-- > 0 && xQueueReceive(inputQueue, &item, 0) == pdTRUE) {
    onLumaFlowBytes(item.data, item.length);
  }
}

// --- clock / licence ------------------------------------------------------

/** Pick up the time provided by WLED (NTP or user supplied) when available. */
void ResonancerUsermod::updateClock() {
  if (clockSynced && (millis() - wallClockMs) < RESONANCER_CLOCK_REFRESH_MS) return;
  wallClockMs = millis();

  // WLED stores the local time in localTime, it stays 0 until the first sync.
  if (localTime > 1700000000L) {          // any date after 2023 counts as valid
    wallClock = (uint32_t)localTime;
    clockSynced = true;
  }
}

/** Current unix time, or 0 when no time source is available. */
uint32_t ResonancerUsermod::currentEpoch() const {
  if (!clockSynced) return 0;
  return wallClock;
}

bool ResonancerUsermod::licenseExpired() const {
  const uint32_t now = currentEpoch();
  if (now == 0) return false;       // no time source: cannot prove expiry (hardened later)
  return now >= RESONANCER_OUTPUT_EXPIRE_UTC;
}

// --- output ---------------------------------------------------------------

/** True when the licence state permits the output to operate. */
bool ResonancerUsermod::outputLicensed() const {
  return (authResult == AuthResult::Ok) && !licenseExpired();
}

const char* ResonancerUsermod::statusText() const {
  if (!enabled || !outputEnabled)  return "Disabled";
  // The licence reason comes first: it is what the host has to fix. "Standby" only
  // means "licensed, but nothing asked for the output in this boot yet".
  if (authResult == AuthResult::NotAuthenticated) return "Not Authenticated";
  if (authResult == AuthResult::RfRestricted)     return "Restricted";
  if (authResult == AuthResult::AuthExpired || licenseExpired()) return "License Expired";
  if (authResult != AuthResult::Ok)               return "License Expired";
  if (!outputArmed)                return "Standby";        // promised, nothing started it yet
  if (rfDevice != nullptr && strcmp(rfDevice->getName(), "stub") == 0) return "No output device";
  // Two different failures end up without an initialised device: the pins could not
  // be taken (no InitConfig() at all) or the device refused to start. Keeping them
  // apart is what makes the info page useful without a serial console.
  if (!rfInitialized) return rfConfigured ? "Device init failed" : "Pins unavailable";
  return "Running";
}

/**
 * Allocate the pins and hand the configuration to the output device.
 *
 * The implementation starts the bus it is given itself, so this usermod owns all
 * six pins (PinOwner::UM_Resonancer) instead of borrowing the global WLED SPI bus.
 * The pins are free to choose, but they must not collide with a SPI based LED
 * bus; the settings page warns about that.
 */
void ResonancerUsermod::applyOutputConfig() {
  rfConfigured = false;
  rfInitialized = false;
  outputHeld = false;         // a fresh output is not held back by an old preset
  if (rfDevice == nullptr) rfDevice = createRfDevice();
  if (rfDevice == nullptr) return;

  // A device created (or re-created) after the last AUTH frame has to learn the
  // current verdict before InitConfig()/DeviceInit() are attempted.
  rfDevice->setAuthentication(authResult);

#if RESONANCER_ENABLE_RF
  // Allocate every pin, or none of them.
  const int8_t requested[6] = { rfSck, rfMiso, rfMosi, rfSs, rfGd0, rfGd2 };
  int8_t allocated = 0;
  for (uint8_t i = 0; i < 6; i++) {
    const int8_t pin = requested[i];
    if (pin < 0) continue;                       // unused pin, allowed for MISO/GDO2
    if (!PinManager::allocatePin((uint8_t)pin, true, PinOwner::UM_Resonancer)) {
      DEBUG_PRINTF_P(PSTR("Resonancer: GPIO %d is already in use\n"), (int)pin);
      // roll back the pins that were taken so far
      for (uint8_t j = 0; j < i; j++) {
        if (requested[j] >= 0) PinManager::deallocatePin((uint8_t)requested[j], PinOwner::UM_Resonancer);
      }
      return;
    }
    allocated++;
  }
  if (allocated == 0) {
    DEBUG_PRINTLN(F("Resonancer: no output pins configured"));
    return;
  }
#else
  // The stub has no pin requirements, it only needs a plausible chip select.
  if (rfSs < 0) return;
#endif

  rfDevice->changeRuntimeConfig(rfConfig);
  if (!rfDevice->InitConfig(CHANNEL_COUNT, rfSck, rfMiso, rfMosi, rfSs, rfGd0, rfGd2)) {
    DEBUG_PRINTLN(F("Resonancer: output device rejected the configuration"));
    return;
  }
  rfConfigured = true;
}

/**
 * Make the next loop pass render and show a frame.
 *
 * The bridge writes segment colours, but the effect pipeline only repaints when its own
 * frame slot has elapsed (42 fps by default), so a colour that arrives between two slots
 * waits for the next one and a stream from the host looks uneven. trigger() marks the
 * frame as due now, which lets the output follow the host cadence instead of a fixed
 * grid. The floor below keeps the loop from being driven at an unbounded rate.
 */
void ResonancerUsermod::refreshStrip() {
  const unsigned long now = millis();
  if ((unsigned long)(now - stripTriggerMs) < RESONANCER_STRIP_TRIGGER_MS) return;
  stripTriggerMs = now;
  strip.trigger();
}

/** Reset reason of this boot, short enough for an info row. */
const char* ResonancerUsermod::resetReasonText() const {
#ifdef ARDUINO_ARCH_ESP32
  switch (esp_reset_reason()) {
    case ESP_RST_POWERON:   return "power on";
    case ESP_RST_EXT:       return "external pin";
    case ESP_RST_SW:        return "software";
    case ESP_RST_PANIC:     return "panic";
    case ESP_RST_INT_WDT:   return "int watchdog";
    case ESP_RST_TASK_WDT:  return "task watchdog";
    case ESP_RST_WDT:       return "watchdog";
    case ESP_RST_DEEPSLEEP: return "deep sleep";
    case ESP_RST_BROWNOUT:  return "brownout";
    case ESP_RST_SDIO:      return "sdio";
    default:                return "unknown";
  }
#else
  return "n/a";
#endif
}

/** Un-initialise the device and return the pins owned by this usermod. */
void ResonancerUsermod::releaseOutputConfig() {
  if (rfDevice != nullptr && rfInitialized) rfDevice->DeviceUnInit();
  rfInitialized = false;
  rfConfigured = false;
  rfConfigDirty = true;        // whatever is left has to be set up again

#if RESONANCER_ENABLE_RF
  const int8_t owned[6] = { rfSck, rfMiso, rfMosi, rfSs, rfGd0, rfGd2 };
  for (uint8_t i = 0; i < 6; i++) {
    if (owned[i] >= 0) PinManager::deallocatePin((uint8_t)owned[i], PinOwner::UM_Resonancer);
  }
#endif
}

/**
 * Submit one packet built from the upstream segments.
 *
 * Every output channel reads the colour of the segment it is mapped to, taken
 * from the rendered segment buffer (not from the LumaFlow channels), which keeps
 * the output independent of the input side.
 */
void ResonancerUsermod::updateOutput() {
  if (rfDevice == nullptr || !rfConfigured || !rfInitialized) return;
  // A preset has the right of way: the device owns a single packet slot, so a stream
  // packet would overwrite it before it is on the air. The wait is bounded, so a device
  // that never reports the preset as sent cannot stall the stream forever.
  if (rfDevice->isOemPending() && (unsigned long)(millis() - oemResultMs) < RESONANCER_PRESET_MAX_WAIT_MS) return;
  // Do not pile packets onto a device that has not taken the previous one: only the
  // newest colour is worth sending, and queueing more of them only adds latency.
  if (rfDevice->isBusy()) return;
  // An executed preset pauses the input: the device stays where the preset put it.
  if (outputHeld) return;
  // Nothing to bridge: no segment follows a channel, or no output channel is mapped. Sending
  // the colours WLED renders locally would take the device back over - the output stays
  // quiet instead, which is also what keeps a preset in effect.
  if (!anyInputSubscribed() || !anyOutputMapped()) return;
  if ((millis() - lastOutputMs) < RESONANCER_OUTPUT_INTERVAL_MS) return;
  lastOutputMs = millis();

  RgbColor colors[CHANNEL_COUNT];
  for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) {
    colors[ch] = RgbColor{0, 0, 0};
    const uint8_t segIndex = outChannelSegment[ch];
    if (segIndex == 0xFF || !segmentUsable(segIndex)) continue;
    const Segment& seg = strip.getSegment(segIndex);
    // A channel the usermod drives can be blinking, and the edge already travels in the
    // function field of the packet, so what belongs in the payload is the stable "on" colour.
    // Sampling the rendered pixel instead would put the off phase into roughly every other
    // packet - the faster the blink, the more of it the device sees - and the device would
    // blink once from the function and once from the payload.
    const uint8_t srcChannelEarly = segChannel[segIndex];
    const bool driven = (srcChannelEarly < CHANNEL_COUNT) && (appliedFunction[segIndex] != 0xFF);
    const uint8_t fnEarly = driven ? (channels[srcChannelEarly].function & 0x03) : 0;
    // Read the segment's own rendered buffer through the public accessor, so the output does
    // not depend on the segment being part of the frame buffer.
    const uint32_t col = (driven && fnEarly != LumaFlow::FUNC_SOLID) ? seg.colors[0] : seg.getPixelColor(0);
    // The device format wants 4 bit per component plus the 2 bit stream function
    // (the LumaFlow protocol carries the function in a nibble, but the hardware
    // only uses 0..3). The function must not share bits with a colour component,
    // so it goes into the top of the green byte and the green nibble keeps its own
    // four bits; bits 4..5 stay unused. See resonancer_rfdevice.h for the contract.
    // The function travels with the colour, so it is taken from the channel the
    // source segment subscribes to, not from the output channel's own index. The
    // segment keeps that state after the stream ends, so the last function is sent
    // for as long as the segment is driven.
    const uint8_t fn = fnEarly;
    colors[ch].r = (uint8_t)(R(col) >> 4);
    colors[ch].g = (uint8_t)((fn << 6) | (G(col) >> 4));
    colors[ch].b = (uint8_t)(B(col) >> 4);
  }

  rfDevice->submitRGBPacket(CHANNEL_COUNT, colors);
  packetsSent++;
}

/**
 * Queue a preset command.
 *
 * Called from the JSON API, which runs in the HTTP task: the request is only recorded
 * here and served in loop(). Touching the output device from the HTTP task would race
 * with the stream, and bringing the output up is not something a button press may do.
 */
void ResonancerUsermod::requestOem(int8_t slot) {
  if (slot < 0 || slot >= (int8_t)ResonancerUi::oemKeyCount()) {
    pendingOemSlot = -1;
    oemResult = OEM_UNKNOWN;
    oemResultSlot = 0;
    oemResultMs = millis();
    return;
  }
  pendingOemSlot = slot;
  oemResultSlot = (uint8_t)slot;
  oemResultMs = millis();
  oemResult = OEM_QUEUED;
}

/**
 * Serve a queued preset command.
 *
 * A preset is only sent while the output is actually running. Pin allocation and device
 * setup are a settings action, so a click with the output down is refused with a reason
 * the page can show instead of failing silently.
 */
void ResonancerUsermod::servicePendingOem() {
  if (pendingOemSlot < 0) return;
  const uint8_t slot = (uint8_t)pendingOemSlot;
  pendingOemSlot = -1;
  oemResultSlot = slot;
  oemResultMs = millis();

  if (!enabled)                { oemResult = OEM_OFF;         return; }
  if (!outputLicensed())       { oemResult = OEM_UNLICENSED;  return; }
  if (rfDevice == nullptr || !rfInitialized || !rfDevice->isActive()) {
    oemResult = OEM_NOT_RUNNING;
    return;
  }

  rfDevice->setOemCommand(slot);
  // Let the preset go out before anything else, then pause the input: every preset is a
  // state the user asked for, and the next colour packet would undo it immediately.
  presetGuardUntilMs = millis() + RESONANCER_PRESET_GUARD_MS;
  outputHeld = true;
  oemResult = OEM_SENT;
}

/**
 * True when at least one WLED segment follows a LumaFlow channel.
 *
 * A segment that does not subscribe to a channel still holds whatever WLED renders for it,
 * and forwarding that to the output would leak the local effect into the radio link - and
 * overwrite a preset the user just sent.
 */
bool ResonancerUsermod::anyInputSubscribed() const {
  for (uint8_t s = 0; s < MAX_NUM_SEGMENTS; s++) {
    if (segChannel[s] < CHANNEL_COUNT && segmentUsable(s)) return true;
  }
  return false;
}

/** True when at least one output channel is mapped to a segment. */
bool ResonancerUsermod::anyOutputMapped() const {
  for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) {
    if (outChannelSegment[ch] != 0xFF) return true;
  }
  return false;
}

/** Result of the last preset command, as shown on the info page. */
const char* ResonancerUsermod::oemResultText() const {
  switch (oemResult) {
    case OEM_QUEUED:      return "queued";
    case OEM_SENT:        return "sent";
    case OEM_OFF:         return "usermod is off";
    case OEM_UNLICENSED:  return "not authenticated";
    case OEM_NOT_RUNNING: return "output is not running";
    case OEM_UNKNOWN:     return "unknown preset";
    default:              return "no command yet";
  }
}

// --- lifecycle ------------------------------------------------------------

void ResonancerUsermod::setup() {
  // Frames that arrive over the serial port are handed to this usermod by the core
  // parser; the core does not know the usermod type. See wled_serial.cpp.
  setSerialFrameSink([](uint8_t cmd, const uint8_t* payload, uint8_t payloadLen) {
    return resonancer_usermod.onSerialFrame(cmd, payload, payloadLen);
  });

#ifdef ARDUINO_ARCH_ESP32
  // The NTP client itself is enabled through a build flag (see
  // platformio_override.ini). Assigning the server here happens before WLED
  // creates the NTP socket, so no core header change is required.
  if (ntpEnabled) strncpy(ntpServerName, RESONANCER_NTP_SERVER, sizeof(ntpServerName) - 1);
#endif

  // Publish the preset buttons of the output implementation before the settings page
  // can be requested. An implementation without presets registers nothing.
  resonancerRegisterOemKeys();

  rfDevice = createRfDevice();
  if (rfDevice) rfDevice->changeRuntimeConfig(rfConfig);

  // The stored switch is the user's intent and survives a reboot (a "save" is a
  // promise, honoured once a licence arrives). What does *not* survive is the arm
  // state: the output is only brought up after something happened in this boot - a
  // settings save, a JSON command or an AUTH frame from the host. That keeps a
  // device whose output cannot come up (bad pin, no module, supply sag) from
  // rebooting in a loop.
  outputArmed = false;

  // Verdict before any AUTH frame arrived. Without this the licence state would stay
  // "not authenticated" until the host happens to send an AUTH frame, so a saved
  // output switch would be switched off again in the first loop() pass.
  authResult = resonancerCheckLicence(LumaFlow::Auth{});
  if (rfDevice) rfDevice->setAuthentication(authResult);

  // Staging queue for the transports that run in another task. It is created once
  // and lives for the lifetime of the usermod.
  inputQueue = xQueueCreate(RESONANCER_INPUT_QUEUE_SLOTS, sizeof(InputChunk));
  if (inputQueue == nullptr) DEBUG_PRINTLN(F("Resonancer: no memory for the input queue"));

  // The UDP socket is not opened here: lwIP is not running yet at this point.
  // loop() opens (and reopens) it once the network is available.
  initDone = true;
}

void ResonancerUsermod::loop() {
  if (!initDone) return;

#if RESONANCER_ENABLE_BLE
  // Start the BLE peripheral on the first loop pass, and keep it running only
  // while BLE is the selected transport.
  if (enabled && commMode == COMM_BLE) {
    // A failed start is retried with a delay instead of being given up on: the
    // first attempt can fail while the radio is still busy with WiFi.
    if (bleStartPending && (bleRetryMs == 0 || (int32_t)(millis() - bleRetryMs) >= 0)) {
      bleStartPending = false;
      bleActive = ResonancerBle::start(bleSuffix);
      if (!bleActive) {
        bleRetryMs = millis() + RESONANCER_BLE_RETRY_MS;
        bleStartPending = true;
        DEBUG_PRINTLN(F("Resonancer: BLE start failed, retrying"));
      } else {
        DEBUG_PRINTLN(F("Resonancer: BLE peripheral started"));
      }
    }
  } else if (bleActive) {
    ResonancerBle::stop();
    bleActive = false;
    bleStartPending = true;                    // allow a later restart
  }

  // --- Bluetooth / WiFi coexistence policy --------------------------------
  // The ESP32-S3 has a single 2.4 GHz radio, so BLE and WiFi compete for it. The
  // selected policy decides who wins instead of leaving it to the coexistence
  // scheduler, which would degrade both.
  if (bleActive) {
    // ESP-IDF aborts when the Bluetooth controller is enabled while WiFi modem
    // sleep is off, and WLED re-applies its own setting on every connect, so the
    // requirement is re-asserted here.
    ResonancerBle::keepModemSleepAlive();

    // Both non-default modes keep the device discoverable whenever the radio is
    // free; only the priority hint differs. See the option text in the settings
    // page for what each one trades away.
    if (bleCoexist == BLE_COEX_WIFI_FIRST) {
#ifdef WLED_DISABLE_WEBSOCKETS
      const bool webBusy = (realtimeMode != REALTIME_MODE_INACTIVE);
#else
      // A connected web UI keeps a web socket open for live updates, which is the
      // best available "someone is looking at the page" signal.
      const bool webBusy = (ws.count() > 0) || (realtimeMode != REALTIME_MODE_INACTIVE);
#endif
      // Pausing advertising costs only the discovery window: the host scans and
      // connects, so it finds the device again as soon as the page goes idle.
      if (webBusy != !webQuiet) {
        webQuiet = !webBusy;
        ResonancerBle::setAdvertising(webQuiet);
      }
    } else if (!webQuiet) {
      webQuiet = true;
      ResonancerBle::setAdvertising(true);
    }
  }
#endif

  // Chunks staged by the callback transports are parsed here, in the main loop.
  // They are parsed even while the usermod is off (and dropped by
  // onLumaFlowFrame()), so a frame that arrived during that time can never be
  // applied when it is switched on again.
  drainInput();

  if (!enabled) {
    // Switching the usermod off hands every driven segment back to WLED and closes
    // the input side. The subscriptions are kept, so re-enabling resumes without a
    // new setup.
    if (anySegmentDriven()) releaseAllSegments();
    inStream = false;
    pendingOemSlot = -1;          // a queued preset is dropped with the usermod
    if (udpActive) stopUdp();
    if (rfInitialized) releaseOutputConfig();
    return;
  }

  // (Re)start the UDP socket when the transport or the port changed.
  if (commMode == COMM_UDP) {
    // A port edit in the settings form only changes the variable, so the socket
    // has to be rebound explicitly.
    if (udpActive && udpBoundPort != udpPort) stopUdp();
    if (!udpActive) startUdp();
  } else if (udpActive) {
    stopUdp();
  }

  updateClock();

  // Stream watchdog. When the host stops, the segments keep what was applied last:
  // the colour and the effect of the last frame stay on the LEDs, they are not
  // handed back to WLED. Only the "streaming" state ends, so the next frame is
  // applied from scratch and the info page stops claiming a live stream.
  if (inStream && (millis() - lastFrameMs > RESONANCER_STREAM_TIMEOUT_MS)) {
    inStream = false;
  }

  if (inStream) {
    // Apply the channel state to the subscribed segments. Only differences are
    // written, so an unchanged stream does not touch the segments at all. The
    // loop runs over segments, because that is the direction the user configures
    // and several segments may subscribe to the same channel.
    const uint8_t segCount = strip.getSegmentsNum();
    bool changed = false;
    for (uint8_t s = 0; s < segCount; s++) {
      const uint8_t ch = segChannel[s];
      if (ch >= CHANNEL_COUNT || !segmentUsable(s)) continue;

      const LumaFlow::Channel& c = channels[ch];
      const uint32_t col = RGBW32(c.red, c.green, c.blue, 0);
      // Skip only when nothing changed *and* the segment still looks the way the
      // usermod left it: the user (or another client) may have picked a different
      // colour or effect while the stream kept sending the same one.
      const Segment& live = strip.getSegment(s);
      if (c.function == appliedFunction[s] && col == appliedColor[s] &&
          live.mode == effectForFunction(c.function) && live.colors[0] == col) continue;

      if (appliedFunction[s] == 0xFF) {
        // first write for this segment: remember its previous settings
        Segment& seg = strip.getSegment(s);
        backup[s].valid = true;
        backup[s].start = seg.start;
        backup[s].stop = seg.stop;
        backup[s].mode = seg.mode;
        backup[s].speed = seg.speed;
        backup[s].intensity = seg.intensity;
        backup[s].color0 = seg.colors[0];
        backup[s].color1 = seg.colors[1];
      }

      writeSegmentColor(ch, s);
      appliedFunction[s] = c.function;
      appliedColor[s] = col;
      changed = true;
    }
    if (changed) {
      // Show it now instead of waiting for the pipeline's own frame slot.
      refreshStrip();
      // Carry the change to other WLED instances through WLED's own sync layer, which honours
      // the user's settings: nothing leaves the device when "send notifications on direct
      // change" is off. stateUpdated() is the right entry point - unlike colorUpdated() it
      // does not write the legacy colour globals back into the segments.
      const unsigned long nowMs = millis();
      if ((unsigned long)(nowMs - lastSyncMs) >= RESONANCER_SYNC_INTERVAL_MS) {
        lastSyncMs = nowMs;
        stateUpdated(CALL_MODE_DIRECT_CHANGE);
      }
    }
  }

  // --- output state machine -----------------------------------------------
  // An unlicensed output simply stays down: the intent is kept, so it comes up on its
  // own once a valid AUTH frame arrives.
  const bool licensed = outputLicensed();
  // The output runs when the user wants it, the licence allows it and this boot armed
  // it. A missing licence never clears the intent, it only keeps the output down.
  const bool wantOutput = outputEnabled && licensed && outputArmed;

  if (wantOutput) {
    // A failed setup (pin taken, device not answering) is retried on an interval
    // instead of staying broken until the next reboot.
    if ((rfConfigDirty || !rfConfigured) && (rfConfigDirty || (int32_t)(millis() - rfRetryMs) >= 0)) {
      rfRetryMs = millis() + RESONANCER_RF_RETRY_MS;
      releaseOutputConfig();
      applyOutputConfig();
      rfConfigDirty = false;
    }
    if (rfConfigured && !rfInitialized) {
      rfInitialized = rfDevice->DeviceInit();
    }
    updateOutput();
  } else if (rfInitialized) {
    releaseOutputConfig();
  }

  // Queued preset commands are served here, where the output state is known and the
  // output device may be touched.
  servicePendingOem();
}

// --- JSON and configuration ----------------------------------------------

void ResonancerUsermod::addToJsonState(JsonObject& root) {
  if (!initDone) return;
  JsonObject um = root[FPSTR(_name)];
  if (um.isNull()) um = root.createNestedObject(FPSTR(_name));
  um[FPSTR(_enabled)] = enabled;
  um[FPSTR(_comm)] = commMode;
  um[FPSTR(_outputEnabled)] = outputEnabled;
}

void ResonancerUsermod::readFromJsonState(JsonObject& root) {
  if (!initDone) return;
  JsonObject um = root[FPSTR(_name)];
  if (!um.isNull()) {
    getJsonValue(um[FPSTR(_enabled)], enabled);
    bool wanted = outputEnabled;
    if (getJsonValue(um[FPSTR(_outputEnabled)], wanted)) {
      // The switch is the user's intent: it is stored even while the licence does not
      // allow operation, and the output comes up by itself once the licence arrives.
      outputEnabled = wanted;
      if (wanted) outputArmed = true;
    }
    // Explicit resume: {"Resonancer":{"stream":true}} lifts the hold a preset set, which is
    // the programmatic counterpart of toggling the output switch.
    bool resume = false;
    if (getJsonValue(um[F("stream")], resume) && resume) outputHeld = false;

    // Preset command: {"Resonancer":{"oem":"red"}} uses the stable key of the button,
    // {"Resonancer":{"oem":3}} the slot it happens to have. Both are queued and served
    // in loop(); nothing is sent from the HTTP task.
    JsonVariant oem = um[FPSTR(_oem)];
    if (oem.is<const char*>())      requestOem(ResonancerUi::oemKeyIndex(oem.as<const char*>()));
    else if (oem.is<int>())         requestOem((int8_t)oem.as<int>());
  }

  // Transport for LumaFlow frames forwarded as hex text (HTTP/WS/MQTT clients).
  JsonObject lf = root["lumaflow"];
  if (!lf.isNull()) {
    const char* cmd = lf["cmd"] | "";
    const char* data = lf["data"] | "";
    const uint8_t cmdId = (strcmp(cmd, "stream") == 0) ? LumaFlow::CMD_STREAM
                        : (strcmp(cmd, "auth") == 0) ? LumaFlow::CMD_AUTH : 0;
    if (cmdId != 0) onLumaFlowFrameHex(cmdId, data);
  }
}

void ResonancerUsermod::addToJsonInfo(JsonObject& root) {
  JsonObject user = root["u"];
  if (user.isNull()) user = root.createNestedObject("u");

  char buf[144];
  snprintf_P(buf, sizeof(buf), PSTR("%s, %lu frames, %lu dup, %lu errors"),
             enabled ? "active" : "inactive",
             (unsigned long)framesReceived, (unsigned long)framesDuplicate,
             (unsigned long)framesRejected);
  JsonArray arr = user.createNestedArray(FPSTR(_name));
  arr.add(buf);


  if (inStream) arr.add(F(" streaming"));
#if RESONANCER_ENABLE_BLE
  if (commMode == COMM_BLE) {
    JsonArray ble = user.createNestedArray(F("BLE"));
    ble.add(ResonancerBle::isConnected() ? F("connected")
           : bleActive ? F("advertising") : F("off"));
    // A usermod row is rendered as value + unit, and anything beyond that is dropped, so the
    // policy and the forced modem sleep share the unit slot.
    char policy[64];
    snprintf_P(policy, sizeof(policy), PSTR(", %s%s"),
               bleCoexist == BLE_COEX_WIFI_FIRST ? "WiFi first"
               : bleCoexist == BLE_COEX_BLE_FIRST ? "BLE first" : "both",
               ResonancerBle::isModemSleepForced() ? ", WiFi sleep on" : "");
    ble.add(policy);
  }
#endif

  // Output rows. Only a build with an output implementation shows them: in a build without one
  // the reference backend still runs (and can be driven through the JSON API), but there is
  // nothing here a user should read as a device.
#if RESONANCER_ENABLE_RF
  // The info page renders a usermod row as value + unit and drops everything beyond that, so
  // this row has exactly two elements: the bare state (which the settings page tests to decide
  // whether a preset may run) and a unit that carries the details and the switch. "held by
  // preset" and "idle, nothing mapped" are surfaced because they explain an output that is up
  // but silent.
  JsonArray out = user.createNestedArray(F("Output"));
  const char* device = (rfDevice != nullptr) ? rfDevice->getName() : "unavailable";
  out.add(FPSTR(statusText()));
  const char* note = !outputEnabled ? ""
                   : outputHeld ? ", held by preset"
                   : (!anyInputSubscribed() || !anyOutputMapped()) ? ", idle, nothing mapped" : "";
  char detail[96];
  snprintf_P(detail, sizeof(detail), PSTR(", %s, %lu packets%s"),
             device, (unsigned long)packetsSent, note);

  // Manual switch: starts an output that is only promised (switch on, nothing started it in
  // this boot) and toggles the switch otherwise, so one click is always the action the user
  // expects from what the row shows.
  const bool postOn = !outputEnabled || !outputArmed;
  String unit = detail;
  unit += F("<button class=\"btn btn-xs\" onclick=\"requestJson({Resonancer:{outputEnabled:");
  unit += postOn ? F("true}});\">") : F("false}});\">");
  unit += outputEnabled ? F("<i class=\"icons on\">&#xe08f;</i>") : F("<i class=\"icons off\">&#xe08f;</i>");
  unit += F("</button>");
  out.add(unit);

  // Result of the last preset command, added only once there was one: the settings page polls
  // this row, and the row is what makes a click verifiable instead of a promise. A row that
  // only ever says "nothing happened yet" is noise.
  if (oemResult != OEM_NONE) {
    JsonArray pre = user.createNestedArray(F("Preset"));
    const ResonancerUi::OemKey* lastKey = ResonancerUi::oemKeyAt(oemResultSlot);
    char res[64];
    if ((oemResult == OEM_SENT || oemResult == OEM_QUEUED) && lastKey != nullptr) snprintf_P(res, sizeof(res), PSTR("%s: %s"), oemResultText(), lastKey->label);
    else snprintf_P(res, sizeof(res), PSTR("%s"), oemResultText());
    pre.add(res);
  }

  // Radio diagnostics. transmitted/submitted shows whether the radio keeps up, the queue wait
  // how stale a packet is when it goes on the air, and the bring-ups whether the output is
  // being rebuilt. One string: the info page only renders value + unit.
  if (rfDevice != nullptr) {
    const uint32_t txUs = rfDevice->lastTxMicros();
    const uint32_t configs = rfDevice->configCount();
    if (txUs > 0 || configs > 0) {
      JsonArray rf = user.createNestedArray(F("RF"));
      char txt[160];
      const uint32_t late = rfDevice->txTimeouts();
      snprintf_P(txt, sizeof(txt), PSTR("%lu/%lu pkt, %lu pkt/s, tx %lu ms, queue %lu ms, %lu bring-ups%s"),
                 (unsigned long)rfDevice->txCount(), (unsigned long)packetsSent,
                 (unsigned long)rfDevice->txRate(),
                 (unsigned long)(txUs / 1000), (unsigned long)rfDevice->lastQueueMs(),
                 (unsigned long)configs, late > 0 ? ", late" : "");
      rf.add(txt);
    }
  }
#endif  // RESONANCER_ENABLE_RF

  // Boot row: the reset reason is what tells "the strip flashed" apart from "the device
  // rebooted", which is the first question when the output hardware is on the same rail.
  JsonArray boot = user.createNestedArray(F("Boot"));
  char bootTxt[48];
  snprintf_P(bootTxt, sizeof(bootTxt), PSTR("%s, %lu s up"),
             resetReasonText(), (unsigned long)(millis() / 1000));
  boot.add(bootTxt);
}

void ResonancerUsermod::addToConfig(JsonObject& root) {
  JsonObject top = root.createNestedObject(FPSTR(_name));
  top[FPSTR(_enabled)] = enabled;
  top[FPSTR(_comm)] = commMode;
  top[FPSTR(_udpPort)] = udpPort;
  top[FPSTR(_bleSuffix)] = bleSuffix;
  top[FPSTR(_bleCoexist)] = bleCoexist;

  // One entry per existing WLED segment holding the subscribed LumaFlow channel,
  // -1 = the segment keeps its own effect. The list therefore grows and shrinks
  // with the segment layout; the next save after adding segments writes the new
  // rows and the settings page shows them from then on.
  JsonArray map = top.createNestedArray(FPSTR(_segChannel));
  const uint8_t segCount = strip.getSegmentsNum();
  for (uint8_t s = 0; s < segCount; s++) {
    map.add((segChannel[s] < CHANNEL_COUNT) ? (int)segChannel[s] : -1);
  }

  // Output half. Serialised only when the output half is compiled in: without it
  // the settings page must not show any output option at all, and omitting the
  // fields is what keeps them out of both the page and the stored configuration.
#if RESONANCER_ENABLE_RF
  // The key order is the order of the settings page, so the output channel
  // mapping is serialised last: it ends up between the pins and the OEM control.
  top[FPSTR(_outputEnabled)] = outputEnabled;
  top[FPSTR(_rfFreq)] = rfConfig.rf_freq;
  JsonArray pins = top.createNestedArray(FPSTR(_rfPins));
  pins.add((int)rfSck); pins.add((int)rfMiso); pins.add((int)rfMosi);
  pins.add((int)rfSs);  pins.add((int)rfGd0);  pins.add((int)rfGd2);
  JsonArray outMap = top.createNestedArray(FPSTR(_outSeg));
  for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) {
    outMap.add((outChannelSegment[ch] == 0xFF) ? -1 : (int)outChannelSegment[ch]);
  }
#endif
}

bool ResonancerUsermod::readFromConfig(JsonObject& root) {
  JsonObject top = root[FPSTR(_name)];
  if (top.isNull()) return false;
  bool complete = true;

  // A key is only read when it is present. getJsonValue(key, dest, default) assigns the
  // default for a missing key, which would turn a partial write (a POST carrying only
  // some of the fields) into a reset of everything it does not mention.
  if (top.containsKey(FPSTR(_enabled)))    getJsonValue(top[FPSTR(_enabled)], enabled);       else complete = false;
  if (top.containsKey(FPSTR(_comm)))       getJsonValue(top[FPSTR(_comm)], commMode);         else complete = false;
  if (top.containsKey(FPSTR(_udpPort)))    getJsonValue(top[FPSTR(_udpPort)], udpPort);       else complete = false;
  if (top.containsKey(FPSTR(_bleCoexist))) getJsonValue(top[FPSTR(_bleCoexist)], bleCoexist); else complete = false;

  // getJsonValue() cannot assign into a fixed size char array, so the string is read
  // explicitly and copied with a bound.
  if (top.containsKey(FPSTR(_bleSuffix))) {
    const char* suffix = top[FPSTR(_bleSuffix)] | "";
    strncpy(bleSuffix, suffix, sizeof(bleSuffix) - 1);
    bleSuffix[sizeof(bleSuffix) - 1] = '\0';
  } else {
    complete = false;
  }

  // Rebuild the subscriptions from scratch so removed entries cannot survive. Segments
  // that are currently driven by the usermod are handed back first, otherwise their
  // original settings would be dropped with the backup and they would keep the usermod
  // effect forever. The rebuild only happens when the list is part of the write.
  if (top.containsKey(FPSTR(_segChannel))) {
    outputHeld = false;       // the user reconfigured the bridge: resume streaming
    releaseAllSegments();
    for (uint8_t s = 0; s < MAX_NUM_SEGMENTS; s++) {
      segChannel[s] = SEGMENT_UNMAPPED;
      appliedFunction[s] = 0xFF;
      appliedColor[s] = 0xFFFFFFFF;
    }
    JsonArray map = top[FPSTR(_segChannel)];
    const uint8_t n = (map.size() < MAX_NUM_SEGMENTS) ? (uint8_t)map.size() : MAX_NUM_SEGMENTS;
    for (uint8_t s = 0; s < n; s++) {
      const int ch = map[s] | -1;
      if (ch >= 0 && ch < CHANNEL_COUNT) segChannel[s] = (uint8_t)ch;
    }
  } else {
    complete = false;
  }

  // Output half. Serialised only when the output half is compiled in, so it is read
  // back under the same condition.
#if RESONANCER_ENABLE_RF
  // A settings save stores the user's intent only. It deliberately does not start the
  // output: a save must never reset a device whose output cannot come up. Starting is
  // always an explicit action (the info page button or the JSON API) or the host's
  // AUTH frame.
  if (top.containsKey(FPSTR(_outputEnabled))) getJsonValue(top[FPSTR(_outputEnabled)], outputEnabled); else complete = false;

  float freq = rfConfig.rf_freq;
  if (top.containsKey(FPSTR(_rfFreq))) {
    getJsonValue(top[FPSTR(_rfFreq)], freq);
  } else {
    complete = false;
  }
  if (freq <= 0.0f) { freq = RESONANCER_DEFAULT_RF_FREQ; complete = false; }
  // The device holds the frequency it was set up with, so a change has to be pushed
  // through changeRuntimeConfig() in loop().
  if (freq != rfConfig.rf_freq) rfConfigDirty = true;
  rfConfig.rf_freq = freq;

  if (top.containsKey(FPSTR(_outSeg))) {
    for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) outChannelSegment[ch] = 0xFF;
    JsonArray outMap = top[FPSTR(_outSeg)];
    const uint8_t n = (outMap.size() < CHANNEL_COUNT) ? (uint8_t)outMap.size() : CHANNEL_COUNT;
    for (uint8_t ch = 0; ch < n; ch++) {
      const int seg = outMap[ch] | -1;
      // Stored as a byte, so an out of range entry would wrap onto another segment.
      // Entries that do not name an existing segment are dropped.
      if (seg >= 0 && seg < MAX_NUM_SEGMENTS) outChannelSegment[ch] = (uint8_t)seg;
    }
  } else {
    complete = false;
  }

  if (top.containsKey(FPSTR(_rfPins))) {
    JsonArray pins = top[FPSTR(_rfPins)];
    if (pins.size() < 6) {
      complete = false;
    } else {
      int values[6];
      for (uint8_t i = 0; i < 6; i++) values[i] = pins[i] | -1;
      rfSck = values[0]; rfMiso = values[1]; rfMosi = values[2];
      rfSs  = values[3]; rfGd0  = values[4]; rfGd2  = values[5];
      rfConfigDirty = true;         // pins changed, rebuild in loop()
    }
  } else {
    complete = false;
  }
#endif

  return complete;
}

/** Adapter between the library's callback and the member function that fills it. */
static void buildPageTrampoline(JsonObject& page, void* ctx) {
  static_cast<ResonancerUsermod*>(ctx)->buildUikitPage(page);
}

/**
 * Settings page metadata.
 *
 * Since the page is data driven (see resonancer_uikit.js and resonancer_uikit.cpp) this
 * is only the hand-off: build the page description and let the engine decorate the form
 * WLED generated. The previous implementation emitted the decoration as hand written
 * JavaScript from here, which made every field name appear in three places.
 */
void ResonancerUsermod::appendConfigData(Print& settingsScript) {
  ResonancerUi::emit(settingsScript, buildPageTrampoline, this);
}

/**
 * Describe the settings page: components, restricting rules, hints and checks.
 *
 * Field names come from the constants above, so a field cannot be renamed in one place
 * and stay stale here. Ids are relative; the engine prefixes them with the usermod name
 * and adds the '[]' suffix of repeated fields. An id starting with '#' belongs to a
 * widget this usermod draws itself and has no config field behind it.
 */
void ResonancerUsermod::buildUikitPage(JsonObject& page) {
  using namespace ResonancerUi;

  page[F("prefix")] = _name;
  page[F("anchor")] = _outputEnabled;

  // --- input half ---------------------------------------------------------
  component(page, _enabled, "input");

  JsonObject proto = component(page, _comm, "input", W_DROPDOWN);
  proto[F("label")] = F("Protocol");
  option(proto, "Serial", COMM_SERIAL);
  option(proto, "UDP", COMM_UDP);
#if RESONANCER_ENABLE_BLE
  option(proto, "BLE", COMM_BLE);
#else
  option(proto, "BLE (not compiled in)", COMM_BLE, true);
#endif

  // Only the selected transport shows its own settings.
  rule(page, _comm, OP_NE, "1", _udpPort,    PROP_VISIBLE, false, "UDP only");
  rule(page, _comm, OP_NE, "2", _bleSuffix,  PROP_VISIBLE, false, "BLE only");
  rule(page, _comm, OP_NE, "2", _bleCoexist, PROP_VISIBLE, false, "BLE only");
  rule(page, _comm, OP_EQ, "2", _bleSuffix,  PROP_REQUIRED, true, "BLE needs a suffix");

#if RESONANCER_ENABLE_RF
  hint(page, _comm, -1, HINT_INFO,
       "<b>One transport at a time.</b> The output half is independent and keeps running.");
#else
  hint(page, _comm, -1, HINT_INFO,
       "<b>One transport at a time.</b> The other transports stay idle while one is selected.");
#endif

  component(page, _udpPort, "input")[F("label")] = F("UDP port");
  hint(page, _udpPort, -1, HINT_INFO,
       "The host sends to <b>32712</b> and rejects any other port. Independent of the WLED ports (sync, NTP, Hyperion).");

  component(page, _bleSuffix, "input")[F("label")] = F("BLE suffix");
  hint(page, _bleSuffix, -1, HINT_INFO,
       "Advertised as <b>LumaFlow&lt;suffix&gt;</b>, e.g. <b>LumaFlow-66CCFF</b>. Give each device its own suffix.");

  JsonObject coex = component(page, _bleCoexist, "input", W_DROPDOWN);
  coex[F("label")] = F("BLE / WiFi");
  option(coex, "Allow both (WiFi + BLE share the radio)", BLE_COEX_ALLOW_BOTH);
  option(coex, "WiFi first (pause BLE advertising while the web UI is open)", BLE_COEX_WIFI_FIRST);
  option(coex, "BLE first (keep advertising while streaming)", BLE_COEX_BLE_FIRST);
  // The trade-off is made explicit instead of being implicit.
  hint(page, _bleCoexist, -1, HINT_WARN,
       "One 2.4 GHz radio for both. Pausing BLE advertising only delays discovery: the host finds the device again once the web UI is idle.");
  // Hard requirement, not a policy: the ESP32 aborts when the Bluetooth controller
  // starts while WiFi modem sleep is off, and WLED disables modem sleep by default.
  hint(page, _bleCoexist, -1, HINT_ERROR,
       "<b>WiFi modem sleep is forced on while BLE is selected</b> - the ESP32 aborts without it. The web UI stays usable, just slightly slower.");

  // Subscription of each WLED segment to a LumaFlow channel: one row per segment.
  JsonObject segRows = arrayComponent(page, _segChannel, "input", W_DROPDOWN);
  segRows[F("heading")] = F("Input mapping");
  segRows[F("captionEach")] = F("SEG$i");
  option(segRows, "-", -1);
  for (uint8_t ch = 0; ch < CHANNEL_COUNT; ch++) {
    char label[12];
    snprintf_P(label, sizeof(label), PSTR("CH%u"), (unsigned)ch);
    option(segRows, label, (int16_t)ch);
  }

  // --- output half --------------------------------------------------------
  // Only emitted when the output half is compiled in. Without it the settings page must
  // not show any output option at all, which is handled by addToConfig() omitting the
  // fields in that case.
#if RESONANCER_ENABLE_RF
  component(page, _outputEnabled, "input")[F("heading")] = F("Output");

  // Everything that needs the output hardware follows the switch. The preset grid below
  // is deliberately not part of this: it stays visible and simply refuses to run while
  // the output is off, so one click can never start a device by accident.
  rule(page, _outputEnabled, OP_FALSE, nullptr, _rfFreq,   PROP_VISIBLE, false, "Output is off");
  rule(page, _outputEnabled, OP_FALSE, nullptr, _rfPins,   PROP_VISIBLE, false, "Output is off");
  rule(page, _outputEnabled, OP_FALSE, nullptr, _outSeg,   PROP_VISIBLE, false, "Output is off");
  rule(page, _outputEnabled, OP_FALSE, nullptr, "#outFold", PROP_VISIBLE, false, "Output is off");

  component(page, _rfFreq, "input");
  checkRange(page, _rfFreq, 300.0f, 1000.0f, "Outside the usable band");

  static const char* const PIN_CAPTIONS[] = { "SCK", "MISO", "MOSI", "SS", "GDO0", "GDO2" };
  JsonObject pins = arrayComponent(page, _rfPins, "input", W_PIN);
  JsonArray captions = pins.createNestedArray(F("captions"));
  for (uint8_t i = 0; i < 6; i++) captions.add(PIN_CAPTIONS[i]);
  checkValidator(page, _rfPins, "distinct", "The same pin is used twice");

  // Channel -> segment mapping. The output reads the rendered colour of a segment, so it
  // keeps running without a stream.
  JsonObject outRows = arrayComponent(page, _outSeg, "input", W_DROPDOWN);
  outRows[F("captionEach")] = F("CH$i");
  option(outRows, "-", -1);
  for (uint8_t s = 0; s < strip.getSegmentsNum(); s++) {
    const Segment& seg = strip.getSegment(s);
    char label[28];
    snprintf_P(label, sizeof(label), PSTR("SEG%u (%u-%u)"), (unsigned)s,
               (unsigned)seg.start, (unsigned)(seg.stop > seg.start ? seg.stop - 1 : seg.start));
    option(outRows, label, (int16_t)s);
  }
  hint(page, _outSeg, -1, HINT_INFO,
       "<b>Mirror of the input half.</b> Each output channel sends the colour of one segment, so the output also runs without a stream.");

  // Unmapped rows stay in the form (their value is submitted either way) and a small
  // control brings them back, so the list stays short without losing the ability to map
  // a channel.
  JsonObject fold = component(page, "#outFold", "display", W_FOLD);
  fold.createNestedArray(F("members")).add(_outSeg);
  foldLabels(fold, "+ $n unused", "- hide unused");
#endif

  // --- preset control and live status -------------------------------------
  // Both belong to the output half and read the info rows that are compiled in under the same
  // condition. The grid additionally needs published preset keys.
#if RESONANCER_ENABLE_RF
  if (oemKeyCount() > 0) {
    JsonObject grid = oemGrid(page, "#oem", nullptr, "oem");
    grid[F("heading")] = F("OEM preset control");
    // A preset can only be sent while the output is actually running.
    rule(page, "status", OP_NE, "Running", "#oem", PROP_EDITABLE, false, "The output is not running");
  }

  // Live device state: shown to the user and fed back into the rules above.
  JsonObject status = component(page, "#status", "display", W_STATUS);
  pollField(status, "Output", "u.Output.0", "status");
  pollField(status, "Preset", "u.Preset.0");
#endif
}
// AI: end